import {z} from 'zod';
import {AppError,type Principal,type PrincipalStore} from '../../contracts/src/index.js';
import {assertCapability,assertCompanyScope,reauthorize} from '../../policy/src/index.js';
import {ReadSelectionContinuation,supportsSelectionMrtr} from '../../durable-read-jobs/src/interactive.js';
export const companySelectionSchema=z.object({query:z.string().trim().min(1).max(100),selected_id:z.number().int().nonnegative().safe().optional()}).strict();
const companySchema=z.object({id:z.number().int().nonnegative().safe(),name:z.string().max(200)}).strict();
export const companySelectionOutput=z.object({status:z.enum(['selected','requires_selection','not_found','cancelled']),company:companySchema.nullable(),candidates:z.array(companySchema).max(20),completeness:z.object({complete:z.boolean(),next_cursor:z.string().nullable()}),limitations:z.array(z.string())}).strict();
export interface SelectionInteraction {protocol:string;capabilities:unknown;requestState?:string;inputResponses?:Record<string,unknown>}
export type SelectionInvoke=(p:Principal,name:'at_query'|'at_get',args:unknown)=>Promise<any>;
/** Native candidates come only from the current authorized query service. This never approves or dispatches writes. */
export class CompanySelection {
 constructor(private continuation:ReadSelectionContinuation,private principals:PrincipalStore,private invoke:SelectionInvoke,private options:{mrtrEnabled?:boolean}={}){}
 private async current(p:Principal){const fresh=await reauthorize(p,this.principals);assertCapability(fresh,'operational.read');return fresh;}
 private async candidates(p:Principal,query:string,selected?:number){const result=await this.invoke(p,'at_query',{entity:'Companies',filter:{op:'and',conditions:[{field:'companyName',op:'contains',value:query},...(selected===undefined?[]:[{field:'id',op:'eq',value:selected}])]},fields:['id','companyName'],page_size:20});if(!['succeeded','partial'].includes(result?.status)||result?.data?.entity!=='Companies'||!Array.isArray(result.data.items)||result.data.items.length>20||typeof result.completeness?.complete!=='boolean'||!(result.completeness.next_cursor===null||typeof result.completeness.next_cursor==='string'))throw new AppError('dependency_unavailable','Company selection query returned incomplete metadata.');const rows=result.data.items.map((r:any)=>{const row=companySchema.parse({id:r.id,name:r.companyName});assertCompanyScope(p,row.id);return row;});if(new Set(rows.map((r:{id:number})=>r.id)).size!==rows.length)throw new AppError('dependency_unavailable','Company selection query returned duplicate IDs.');return{rows,complete:result.completeness.complete&&result.completeness.next_cursor===null};}
 private async selected(p:Principal,query:string,id:number){p=await this.current(p);assertCompanyScope(p,id);const matches=await this.candidates(p,query,id);if(!matches.complete||matches.rows.length!==1||matches.rows[0].id!==id)throw new AppError('not_found_or_inaccessible','Selected company no longer matches the requested lookup.');const result=await this.invoke(p,'at_get',{entity:'Companies',id,fields:['id','companyName']});if(result?.status!=='succeeded'||result?.data?.entity!=='Companies')throw new AppError('not_found_or_inaccessible','Selected company is unavailable.');const row=companySchema.parse({id:result.data.item?.id,name:result.data.item?.companyName});p=await this.current(p);assertCompanyScope(p,row.id);if(row.id!==id||row.name!==matches.rows[0].name)throw new AppError('conflict','Selected company changed during confirmation.');return{p,row};}
 private result(status:'selected'|'requires_selection'|'not_found'|'cancelled',rows:{id:number;name:string}[]=[],complete=true,company:{id:number;name:string}|null=null){return{status,company,candidates:rows,completeness:{complete,next_cursor:null},limitations:complete?[]:['Candidate results are bounded. Narrow the query before selecting; no complete company count is implied.']};}
 async run(p:Principal,input:unknown,interaction?:SelectionInteraction){const a=companySelectionSchema.parse(input);p=await this.current(p);const enabled=this.options.mrtrEnabled===true&&supportsSelectionMrtr({'io.modelcontextprotocol/protocolVersion':interaction?.protocol,'io.modelcontextprotocol/clientCapabilities':interaction?.capabilities});
  if(interaction?.requestState!==undefined||interaction?.inputResponses!==undefined){if(!enabled||!interaction.requestState||!interaction.inputResponses||Object.keys(interaction.inputResponses).some(k=>k!=='selection')||!Object.hasOwn(interaction.inputResponses,'selection')||a.selected_id!==undefined)throw new AppError('invalid_input','Selection continuation envelope is unsupported or incomplete.');let selected:{id:number;name:string}|undefined;const resumed=await this.continuation.resume(p,'at_select_company',{query:a.query},interaction.requestState,interaction.inputResponses.selection,async id=>{if(!/^(0|[1-9][0-9]*)$/.test(id)||!Number.isSafeInteger(Number(id)))throw new AppError('invalid_input','Invalid selected company ID.');const fresh=await this.selected(p,a.query,Number(id));selected=fresh.row;return fresh.p;});return resumed.status==='cancelled'?this.result('cancelled'):this.result('selected',[],true,selected!);}
  if(a.selected_id!==undefined){const selected=await this.selected(p,a.query,a.selected_id);return this.result('selected',[],true,selected.row);}
  const found=await this.candidates(p,a.query);p=await this.current(p);for(const row of found.rows)assertCompanyScope(p,row.id);if(!found.complete)return this.result('requires_selection',found.rows,false);if(found.rows.length===0)return this.result('not_found');if(found.rows.length===1){const selected=await this.selected(p,a.query,found.rows[0].id);return this.result('selected',[],true,selected.row);}
  const offer=await this.continuation.offer(p,'at_select_company',{query:a.query},found.rows.map((r:{id:number;name:string})=>({id:String(r.id),label:r.name})),enabled);return offer.mode==='mrtr'?offer.result:this.result('requires_selection',found.rows);
 }
}
