import {createCipheriv,createDecipheriv,randomBytes} from 'node:crypto';
import {z} from 'zod';
export const RETENTION_MS=168*60*60*1000,MAX_EVENT_BYTES=65536;
export type Row=Record<string,any>;
export type DiagnosticOutcome='succeeded'|'failed'|'rejected'|'partial'|'accepted_unverified'|'unknown_outcome';
export interface DiagnosticCall {callId:string;traceId:string;parentId?:string;requestId?:string;tenantId?:string;actorId?:string;resourceId?:number;tool:string;requestedTool?:string;source:string;startedAt:string;endedAt?:string;durationMs?:number;lifecycle:'started'|'finished'|'interrupted';outcome?:DiagnosticOutcome;errorOrigin?:string;errorCode?:string;recordId?:string;operationId?:string;jobId?:string;serverRelease:string;metadataDigest?:string;instanceId:string;expiresAt:string}
export interface DiagnosticEvent {eventId:string;traceId:string;callId?:string;spanId?:string;parentId?:string;type:string;occurredAt:string;expiresAt:string;tenantId?:string;actorId?:string;instanceId:string;schemaVersion:1;details:Row;call?:DiagnosticCall}
export interface DiagnosticQuery {tenantId:string;from?:string;to?:string;actorId?:string;tool?:string;outcome?:string;errorOrigin?:string;errorCode?:string;recordId?:string;operationId?:string;jobId?:string;traceId?:string;serverRelease?:string;limit?:number;after?:{startedAt:string;callId:string}}
export interface DiagnosticStore {append(event:DiagnosticEvent):Promise<void>;list(query:DiagnosticQuery,now?:number):Promise<DiagnosticCall[]>;detail(tenantId:string,callId:string,now?:number):Promise<{call:DiagnosticCall;events:DiagnosticEvent[];children:DiagnosticCall[]}|undefined>;cleanup(now?:number,limit?:number):Promise<number>;abandoned(instanceId:string,before:string,now?:number):Promise<DiagnosticCall[]>;ping():Promise<void>;heartbeat(instanceId:string,now?:number):Promise<void>}
const uuid=z.string().uuid(),time=z.iso.datetime({offset:true});
export const diagnosticEventSchema=z.object({eventId:uuid,traceId:z.string().min(1).max(128),callId:uuid.optional(),spanId:z.string().max(128).optional(),parentId:uuid.optional(),type:z.string().min(1).max(80),occurredAt:time,expiresAt:time,tenantId:z.string().max(128).optional(),actorId:z.string().max(256).optional(),instanceId:z.string().max(128),schemaVersion:z.literal(1),details:z.record(z.string(),z.unknown()),call:z.any().optional()}).strict();
/** Separate diagnostic key ring and AAD domain; no workflow intent envelope reuse. */
export class DiagnosticCipher {
 private active:string;private keys:Record<string,Buffer>;
 constructor(key:Buffer|{active:string;keys:Record<string,Buffer>}){this.active=Buffer.isBuffer(key)?'1':key.active;this.keys=Buffer.isBuffer(key)?{'1':Buffer.from(key)}:key.keys;if(!/^[A-Za-z0-9_-]{1,32}$/.test(this.active)||!this.keys[this.active]||Object.values(this.keys).some(k=>k.length!==32))throw new Error('Invalid diagnostic key ring.');}
 seal(value:unknown,binding:string){const nonce=randomBytes(12),cipher=createCipheriv('aes-256-gcm',this.keys[this.active]!,nonce);cipher.setAAD(Buffer.from(`mcp:diagnostics:v1:${binding}`));const data=Buffer.from(JSON.stringify(value));if(data.length>MAX_EVENT_BYTES)throw new Error('Diagnostic event exceeds bound.');return['d1',this.active,nonce.toString('base64url'),Buffer.concat([cipher.update(data),cipher.final()]).toString('base64url'),cipher.getAuthTag().toString('base64url')].join('.');}
 open(value:string,binding:string):any{const [version,keyId,nonce,body,tag,...extra]=value.split('.');if(version!=='d1'||!keyId||!this.keys[keyId]||extra.length||!nonce||!body||!tag||value.length>MAX_EVENT_BYTES*2)throw new Error('Diagnostic ciphertext invalid.');const decipher=createDecipheriv('aes-256-gcm',this.keys[keyId]!,Buffer.from(nonce,'base64url'));decipher.setAAD(Buffer.from(`mcp:diagnostics:v1:${binding}`));decipher.setAuthTag(Buffer.from(tag,'base64url'));return JSON.parse(Buffer.concat([decipher.update(Buffer.from(body,'base64url')),decipher.final()]).toString());}
}
