import {randomUUID} from 'node:crypto';
import {diagnosticEvidence,currentExecution} from '../../execution/src/index.js';
import {sanitizeError,attachmentShape} from './sanitize.js';
export {attachmentShape};
export const FILE_URL_POLICY_VERSION='oai-download-hosts-v1';
export type UrlRule='url_missing'|'url_wrong_type'|'url_parse_failed'|'scheme_not_https'|'embedded_credentials'|'nonstandard_port'|'hostname_not_allowed';
export function inspectFileUrl(value:unknown){const failed:UrlRule[]=[];if(value===undefined||value===null||value==='')return{failed:['url_missing'] as UrlRule[],parse_success:false,input_type:typeof value};if(typeof value!=='string')return{failed:['url_wrong_type'] as UrlRule[],parse_success:false,input_type:typeof value};let url:URL;try{url=new URL(value);}catch{return{failed:['url_parse_failed'] as UrlRule[],parse_success:false,input_type:'string'};}if(url.protocol!=='https:')failed.push('scheme_not_https');if(url.username||url.password)failed.push('embedded_credentials');if(url.port&&url.port!=='443')failed.push('nonstandard_port');if(!(url.hostname==='files.oaiusercontent.com'||url.hostname.endsWith('.oaiusercontent.com')))failed.push('hostname_not_allowed');const hostname=url.hostname.toLowerCase().slice(0,253);return{failed,parse_success:true,input_type:'string',hostname,scheme_category:url.protocol==='https:'?'https':url.protocol==='http:'?'http':'other',port_category:url.port&&url.port!=='443'?'nonstandard':'default',embedded_credentials:!!(url.username||url.password)};}
/** Payloads here contain reviewed summaries only. Raw provider data must never be passed to this helper. */
export async function fileEvidence(stage:'received'|'url_validation'|'download'|'staging',details:Record<string,unknown>){await diagnosticEvidence('attachment',{stage,...details});}
export async function verificationEvidence(details:{operation_id?:string;kind:'note'|'time';native_id:number;ticket_id:number;outcome:'not_attempted'|'readback_failed'|'mismatched'|'verified';expected_fields?:string[];matched_fields?:string[];mismatched_fields?:string[];missing_fields?:string[];record_id_check?:boolean;parent_ticket_check?:boolean;author_check?:boolean;duration_ms?:number},error?:unknown){await diagnosticEvidence('verification',{...details,verification_attempt_id:randomUUID(),...(currentExecution()?.lastProviderAttemptId?{provider_attempt_id:currentExecution()!.lastProviderAttemptId}:{}),...(error!==undefined?{error:sanitizeError(error)}:{})});}
