import {mkdir,open,opendir,readdir,readFile,rename,unlink,statfs,stat,writeFile} from 'node:fs/promises';
import {join} from 'node:path';
import {createHash,randomUUID} from 'node:crypto';
import {DiagnosticCipher,MAX_EVENT_BYTES,RETENTION_MS,type DiagnosticEvent,type DiagnosticStore} from './contracts.js';
const HEADER=40,MAX_FRAME=MAX_EVENT_BYTES*2;
export class DiagnosticSpool {
 private serialized:Promise<unknown>=Promise.resolve();
 readonly owner=randomUUID();private initialized=false;private initializing?:Promise<void>;private torn=0;
 constructor(readonly directory:string,readonly cipher:DiagnosticCipher,readonly options={maxConcurrent:64,minFreeBytes:1048576}){}
 private async syncDirectory(){const dir=await open(this.directory,'r');try{await dir.sync();}finally{await dir.close();}}
 private serial<T>(run:()=>Promise<T>):Promise<T>{const result=this.serialized.then(run,run);this.serialized=result.catch(()=>{});return result;}
 async initialize(){if(this.initialized)return;if(this.initializing)return this.initializing;this.initializing=(async()=>{await mkdir(this.directory,{recursive:true,mode:0o700});await this.heartbeat();await this.syncDirectory();await this.recover();this.initialized=true;})().finally(()=>{this.initializing=undefined;});return this.initializing;}
 private async heartbeat(){await writeFile(join(this.directory,this.owner+'.owner'),String(Date.now()),{mode:0o600});}
 private frame(e:DiagnosticEvent){const payload=Buffer.from(this.cipher.seal(e,'spool:event')),header=Buffer.alloc(HEADER);header.write('DGS1');header.writeUInt32BE(payload.length,4);createHash('sha256').update(payload).digest().copy(header,8);return Buffer.concat([header,payload]);}
 private decode(data:Buffer):DiagnosticEvent{if(data.length<HEADER||data.toString('ascii',0,4)!=='DGS1')throw new Error('Torn diagnostic frame.');const size=data.readUInt32BE(4);if(size>MAX_FRAME||data.length!==HEADER+size||!createHash('sha256').update(data.subarray(HEADER)).digest().equals(data.subarray(8,40)))throw new Error('Torn diagnostic frame.');return this.cipher.open(data.subarray(HEADER).toString(),'spool:event') as DiagnosticEvent;}
 async capacity(terminal=false){await this.initialize();const space=await statfs(this.directory),free=Number(space.bavail)*Number(space.bsize),reserved=this.options.maxConcurrent*(MAX_FRAME+HEADER);return{freeBytes:free,reservedBytes:reserved,available:free>this.options.minFreeBytes+(terminal?MAX_FRAME:reserved+MAX_FRAME)};}
 async append(e:DiagnosticEvent,terminal=false){await this.initialize();return this.serial(async()=>{if(!(await this.capacity(terminal)).available)throw new Error('Diagnostic spool headroom unavailable.');await this.heartbeat();const name=`${this.owner}-${Date.parse(e.occurredAt)}-${e.eventId}`,writing=join(this.directory,name+'.writing'),pending=join(this.directory,name+'.pending'),file=await open(writing,'wx',0o600);try{await file.writeFile(this.frame(e));await file.sync();}finally{await file.close();}await rename(writing,pending);await this.syncDirectory();});}
 async recover(now=Date.now()){let expired=0,recovered=0,quarantined=0;for(const name of await readdir(this.directory)){const path=join(this.directory,name),metadata=await stat(path);if(name.endsWith('.torn')){const timestamp=Number(name.slice(37).split('-')[0]);if((Number.isFinite(timestamp)&&timestamp>0?timestamp:metadata.mtimeMs)+RETENTION_MS<=now){await unlink(path);expired++;await this.syncDirectory();}continue;}if(name.endsWith('.pending')){try{const event=this.decode(await readFile(path));if(Date.parse(event.expiresAt)<=now){await unlink(path);expired++;}}catch{await rename(path,join(this.directory,name.replace(/\.pending$/,'.torn')));this.torn++;quarantined++;}continue;}if(!name.endsWith('.writing'))continue;const owner=name.slice(0,36);let live=false;try{live=(await stat(join(this.directory,owner+'.owner'))).mtimeMs>now-120000;}catch{}if(live||metadata.mtimeMs>now-120000)continue;try{this.decode(await readFile(path));await rename(path,join(this.directory,name.replace(/\.writing$/,'.pending')));recovered++;}catch{await rename(path,join(this.directory,name.replace(/\.writing$/,'.torn')));this.torn++;quarantined++;}}await this.syncDirectory();return{expired,recovered,quarantined};}

 async *iterate(now=Date.now()):AsyncGenerator<DiagnosticEvent>{await this.initialize();const directory=await opendir(this.directory);for await(const item of directory){if(!item.name.endsWith('.pending'))continue;try{const event=this.decode(await readFile(join(this.directory,item.name)));if(Date.parse(event.expiresAt)>now)yield event;}catch{/* Retained corrupt frame is visible in health and blocks admission. */}}}
 async events(now=Date.now()):Promise<DiagnosticEvent[]>{const events:DiagnosticEvent[]=[];for await(const event of this.iterate(now))events.push(event);return events;}

 async drain(store:DiagnosticStore,now=Date.now(),limit=500){await this.initialize();return this.serial(async()=>{let delivered=0,expired=0;for(const name of (await readdir(this.directory)).sort()){if(!name.endsWith('.pending')||delivered+expired>=limit)continue;const path=join(this.directory,name),event=this.decode(await readFile(path));if(Date.parse(event.expiresAt)<=now)expired++;else{await store.append(event);delivered++;}await unlink(path);await this.syncDirectory();}return{delivered,expired};});}
 async health(now=Date.now()){await this.initialize();let bytes=0,events=0,oldest:number|undefined,torn=0;for(const name of await readdir(this.directory)){if(name.endsWith('.torn')){torn++;continue;}if(!name.endsWith('.pending'))continue;const path=join(this.directory,name);bytes+=(await stat(path)).size;events++;try{const e=this.decode(await readFile(path));const time=Date.parse(e.occurredAt);oldest=oldest===undefined?time:Math.min(oldest,time);}catch{torn++;}}return{backlogBytes:bytes,backlogEvents:events,oldestPendingAt:oldest===undefined?null:new Date(oldest).toISOString(),backlogAgeMs:oldest===undefined?0:Math.max(0,now-oldest),tornFrames:torn,...await this.capacity()};}
}
