import {test} from 'node:test';import assert from 'node:assert/strict';
import {createExecution,withExecution} from '../packages/execution/src/index.js';import {summarizeArguments,summarizeResult,summarizeError,attachmentShape} from '../packages/diagnostics/src/sanitize.js';import {inspectFileUrl} from '../packages/diagnostics/src/evidence.js';import {resolveUploadInput} from '../packages/artifacts/src/file-input.js';
import {AppError,actorKey} from '../packages/contracts/src/index.js';import {reauthorize} from '../packages/policy/src/index.js';import {IntentCipher,MemoryJournal,MemoryPrincipalStore} from '../packages/storage/src/index.js';import {FixtureAutotaskAdapter,fixturePrincipals} from '../packages/workflows/src/fixtures.js';import {TicketWorkflows} from '../packages/workflows/src/index.js';import {TicketWriteWorkflows} from '../packages/workflows/src/write-workflows.js';
const secret='SECRET_CANARY_8482';
async function capture<T>(run:()=>Promise<T>){const events:{kind:string;details:Record<string,any>}[]=[],context=createExecution(new AbortController().signal);context.diagnosticEvidence=async(kind,details)=>{events.push({kind,details});};const result=await withExecution(context,run);assert.ok(!JSON.stringify(events).includes(secret));return{result,events};}
test('diagnostic summaries preserve cancellation presence and reviewed selectors without content',()=>{const a=summarizeArguments('ticket_update',{ticket:{kind:'id',id:1001},fields:{status:'Canceled',resolution:'',title:secret},expected:{status:5},password:secret,download_url:`https://files.oaiusercontent.com/${secret}`});assert.equal((a.summary as any).fields.resolution.blank,true);assert.equal((a.summary as any).fields.status,'Canceled');const absent=summarizeArguments('ticket_update',{fields:{status:'Canceled'}});assert.equal(Object.hasOwn((absent.summary as any).fields,'resolution'),false);for(const value of [a,absent,summarizeResult('ticket_note_add',{status:'accepted_unverified',data:{note_id:30105805,description:secret},notes:[{text:secret}]}),summarizeError(new AppError('dependency_unavailable',secret,false,{reason:'http_error',http_status:500}))])assert.ok(!JSON.stringify(value).includes(secret));assert.equal(attachmentShape({file:secret}).source_kind,'bare_file_id');assert.equal(attachmentShape({file:{file_id:secret},content_base64:secret}).source_kind,'conflicting_sources');});
test('URL rule evidence records only parsed hostname and every failed rule',async()=>{for(const [url,rule]of [['bad '+secret,'url_parse_failed'],['http://user:'+secret+'@evil.example:444/'+secret+'?token='+secret+'#'+secret,'scheme_not_https'],['https://files.oaiusercontent.com.evil.example/'+secret,'hostname_not_allowed']]){let fetched=false;const {events}=await capture(async()=>{await assert.rejects(resolveUploadInput({file:{file_id:secret,download_url:url!}},1000,new AbortController().signal,async()=>{fetched=true;throw Error();}));});assert.equal(fetched,false);assert.ok(events.some(e=>e.details.failed?.includes(rule)));}const validation=inspectFileUrl('http://u:p@evil.example:444/path');assert.deepEqual(validation.failed,['scheme_not_https','embedded_credentials','nonstandard_port','hostname_not_allowed']);});
test('208 KiB file references use separate download and never retain signed URL or filename',async()=>{const file={file_id:secret,file_name:secret+'.pdf',download_url:'https://files.oaiusercontent.com/'+secret+'?token='+secret+'#'+secret},bytes=Buffer.alloc(208*1024,65);const {result,events}=await capture(()=>resolveUploadInput({file},300000,new AbortController().signal,async()=>new Response(bytes,{headers:{'content-length':String(bytes.length),'content-type':'application/pdf'}})));assert.equal(Buffer.from(result.content_base64,'base64').length,bytes.length);assert.equal(events.at(-1)!.details.outcome,'downloaded');assert.equal(events.at(-1)!.details.received_bytes,bytes.length);});
for(const [name,fetcher,expected]of [
 ['http',async()=>new Response(secret,{status:403}),'http_error'],
 ['empty',async()=>new Response(''),'empty_body'],
 ['declared',async()=>new Response('x',{headers:{'content-length':'9999'}}),'declared_oversize'],
 ['streamed',async()=>new Response('x'.repeat(101)),'streamed_oversize'],
 ['redirect',async()=>{throw new TypeError(secret,{cause:new Error('unexpected redirect')});},'redirect_rejected'],
 ['interrupted',async()=>new Response(new ReadableStream({start(c){c.enqueue(new Uint8Array([1]));c.error(new Error(secret));}})),'stream_interrupted']
] as const)test(`download diagnostics classify ${name}`,async()=>{const {events}=await capture(async()=>{await assert.rejects(resolveUploadInput({file:{file_id:secret,file_name:'f.pdf',download_url:'https://files.oaiusercontent.com/'+secret}},100,new AbortController().signal,fetcher as typeof fetch));});assert.equal(events.at(-1)!.details.outcome,expected);});
function writes(){const p=fixturePrincipals()[0]!,store=new MemoryPrincipalStore([p]),adapter=new FixtureAutotaskAdapter(p=>reauthorize(p,store)),journal=new MemoryJournal(),core=new TicketWorkflows(adapter,store,journal),flow=new TicketWriteWorkflows(core,new IntentCipher(Buffer.alloc(32,5)));return{p,adapter,journal,flow};}
for(const mode of ['verified','read_failed','title','description','noteType','publish','id','ticketID','creatorResourceID','missing'] as const)test(`accepted note diagnostics distinguish ${mode} without changing replay`,async()=>{const s=writes(),original=s.adapter.getTicketNote.bind(s.adapter);s.adapter.getTicketNote=async(...args)=>{if(mode==='read_failed')throw new AppError('dependency_unavailable',secret,false,{reason:'http_error',http_status:503});const row=await original(...args);if(mode==='missing')delete row.description;else if(mode!=='verified')(row as Record<string,unknown>)[mode]=['title','description'].includes(mode)?secret+'changed':999;return row;};const input={ticket:{kind:'id',id:1001},note:{title:secret,text:secret,audience:'internal'},request_key:'incident-'+mode};const {result,events}=await capture(()=>s.flow.noteAdd(s.p,input));assert.equal(result.status,mode==='verified'?'succeeded_verified':'accepted_unverified');const evidence=events.filter(e=>e.kind==='verification').at(-1)!.details;assert.equal(evidence.outcome,mode==='verified'?'verified':mode==='read_failed'?'readback_failed':'mismatched');assert.equal(evidence.operation_id,result.operation_id);assert.equal(evidence.native_id,result.data.note_id);if(mode==='missing')assert.ok(evidence.missing_fields.includes('description'));if(['title','description','noteType','publish'].includes(mode))assert.ok(evidence.mismatched_fields.includes(mode));if(mode==='id')assert.equal(evidence.record_id_check,false);if(mode==='ticketID')assert.equal(evidence.parent_ticket_check,false);if(mode==='creatorResourceID')assert.equal(evidence.author_check,false);if(mode==='read_failed'){assert.equal(evidence.error.http_status,503);assert.equal((await s.journal.get(result.operation_id,actorKey(s.p)))!.state,'accepted_unverified');}await s.flow.noteAdd(s.p,input);assert.equal(s.adapter.calls.filter(c=>c.kind==='create'&&c.entity==='TicketNotes').length,1);});
test('diagnostic observer failure cannot change accepted note outcome or create a retry',async()=>{const s=writes(),context=createExecution(new AbortController().signal);let unhealthy=0;context.diagnosticEvidence=async()=>{throw Error(secret);};context.diagnosticFailure=()=>{unhealthy++;};const result=await withExecution(context,()=>s.flow.noteAdd(s.p,{ticket:{kind:'id',id:1001},note:{title:'Title',text:'Text',audience:'internal'},request_key:'observer-outage'}));assert.equal(result.status,'succeeded_verified');assert.ok(unhealthy>=2);assert.equal(s.adapter.calls.filter(c=>c.kind==='create').length,1);});

test('native ticket changes retain reviewed Canceled label and explicit absent resolution',()=>{const s=summarizeArguments('ticket_update',{changes:{status:{kind:'name',name:'Canceled'}}});assert.equal((s.summary as any).changes.status.name,'Canceled');assert.equal((s.field_presence as any).resolution.present,false);});
