import {test} from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
const source=await readFile('apps/console/public/diagnostics.js','utf8');
const {renderDiagnostics,diagnosticQuery}=await import(`data:text/javascript;base64,${Buffer.from(source).toString('base64')}`);
class Element {[key:string]:any;children:Element[]=[];listeners:Record<string,Function>={};textContent='';value='';disabled=false;constructor(readonly tag:string,text?:unknown){if(text!==undefined)this.textContent=String(text);}append(...items:Element[]){this.children.push(...items);}replaceChildren(...items:Element[]){this.children=items;}setAttribute(key:string,value:string){this[key]=value;}addEventListener(event:string,fn:Function){this.listeners[event]=fn;}set innerHTML(_v:string){throw Error('HTML rendering is prohibited');}}
const node=(tag:string,text?:unknown)=>new Element(tag,text);
const descendants=(root:Element):Element[]=>[root,...root.children.flatMap(descendants)];
const text=(root:Element):string=>descendants(root).map(n=>n.textContent).join('\n');
test('diagnostic query bounds date range and safely encodes every filter and cursor',()=>{assert.throws(()=>diagnosticQuery({from:'2026-01-01',to:'2026-01-09'}),/seven days/);assert.throws(()=>diagnosticQuery({from:'bad',to:'bad'}));const q=new URLSearchParams(diagnosticQuery({from:'2026-01-01',to:'2026-01-02',tool:'x&actorId=other',traceId:'trace'},'opaque&cursor'));assert.equal(q.get('tool'),'x&actorId=other');assert.equal(q.get('actorId'),null);assert.equal(q.get('cursor'),'opaque&cursor');assert.equal(q.get('limit'),'50');});
test('tool-call UI renders evidence inertly, offers audited copy, and preserves cursor filters',async()=>{const root=node('main'),calls:string[]=[],notices:string[]=[],copied:string[]=[],canary='<img src=x onerror=alert(1)>',call={callId:'call-1',traceId:'trace-1',tool:canary,actorId:'actor',startedAt:'2026-09-20T00:00:00Z',durationMs:12,lifecycle:'finished',outcome:'failed',errorOrigin:'provider',serverRelease:'release'},detail={call,events:[{occurredAt:call.startedAt,type:'validation',details:{message:canary,omitted:true}}],children:[]};const api=async(path:string)=>{calls.push(path);if(path==='api/diagnostics/health')return{ready:true,backlogEvents:0};if(path.endsWith('/export'))return{...detail,sanitized:true};if(path==='api/diagnostics/call-1')return detail;return{items:[call],next_cursor:path.includes('cursor=')?null:'opaque-cursor'};};const helpers={api,node,notice:(message:string)=>notices.push(message),copy:async(value:string)=>{copied.push(value);},button:(label:string,fn:Function)=>{const b=node('button',label);b.listeners.click=fn;return b;},panel:(title:string,description:string)=>{const p=node('section');p.append(node('h2',title),node('p',description));return p;},table:(heads:string[],rows:any[],project:Function)=>{const table=node('table');for(const title of heads)table.append(node('th',title));for(const row of rows){const tr=node('tr');for(const cell of project(row))tr.append(cell instanceof Element?cell:node('td',cell));table.append(tr);}return table;}};await renderDiagnostics(root,helpers);assert.match(text(root),/Tool calls/);assert.match(text(root),/Unavailable/);assert(text(root).includes(canary));assert.equal(descendants(root).some(n=>n.tag==='img'),false);const button=(label:string)=>descendants(root).find(n=>n.tag==='button'&&n.textContent===label)!;await button('View details').listeners.click!();assert(text(root).includes('"omitted": true'));await button('Copy sanitized JSON').listeners.click!();assert(calls.includes('api/diagnostics/call-1/export'));assert.equal(JSON.parse(copied[0]!).sanitized,true);await button('Next page').listeners.click!();const paged=calls.find(p=>p.includes('cursor='))!;assert.equal(new URLSearchParams(paged.split('?')[1]).get('cursor'),'opaque-cursor');assert.match(notices.at(-1)!,/copied/);assert(!descendants(root).some(n=>n.tag==='a'));assert(!/innerHTML|insertAdjacentHTML|eval\(/.test(source));});
