import test from 'node:test';
import assert from 'node:assert/strict';
import {createServer} from 'node:http';
import {once} from 'node:events';
import {mkdtemp,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {randomBytes} from 'node:crypto';
import {createFixtureSystem} from '../apps/server/src/fixture-system.js';
import {createApplication} from '../apps/server/src/app.js';
import {createNodeHandler} from '../apps/server/src/ingress.js';
import {DiagnosticCipher} from '../packages/diagnostics/src/contracts.js';
import {MemoryDiagnosticStore} from '../packages/diagnostics/src/store.js';
import {DiagnosticSpool} from '../packages/diagnostics/src/spool.js';
import {DurableDiagnostics} from '../packages/diagnostics/src/service.js';
import {AppError} from '../packages/contracts/src/index.js';
async function setup(t:any){const directory=await mkdtemp(join(tmpdir(),'diagnostics-http-'));let handle:ReturnType<typeof createNodeHandler>;const server=createServer((req,res)=>handle(req,res));server.listen(0,'127.0.0.1');await once(server,'listening');const base=`http://127.0.0.1:${(server.address() as any).port}`,f=createFixtureSystem(base),store=new MemoryDiagnosticStore(),cipher=new DiagnosticCipher(randomBytes(32)),spool=new DiagnosticSpool(directory,cipher),diagnostics=new DurableDiagnostics(store,spool,{instanceId:'http-fixture',serverRelease:'test',cipher,principals:f.store});await diagnostics.initialize();f.runtime.options.diagnostics=diagnostics;const app=createApplication({publicUrl:base,authenticate:f.authenticate,workflows:f.core,writes:f.writes,runtime:f.runtime,diagnostics});handle=createNodeHandler(app);t.after(async()=>{await app.close();await f.app.close();server.closeAllConnections();await new Promise<void>(r=>server.close(()=>r()));await rm(directory,{recursive:true,force:true});});let sequence=0;const call=async(name:string,args:unknown)=>{const response=await fetch(base+'/mcp',{method:'POST',headers:{authorization:`Bearer ${f.tokens[0]!.token}`,'content-type':'application/json',accept:'application/json, text/event-stream','mcp-protocol-version':'2025-11-25'},body:JSON.stringify({jsonrpc:'2.0',id:++sequence,method:'tools/call',params:{name,arguments:args}})}),text=await response.text();const json=JSON.parse(text.startsWith('event:')||text.startsWith('data:')?text.split('\n').filter(l=>l.startsWith('data:')).at(-1)!.slice(5):text);return{response,json};};return{f,store,spool,diagnostics,call,base};}
test('HTTP diagnostics captures successful, unknown and pre-SDK attachment calls before returning responses',async t=>{const s=await setup(t);const success=await s.call('at_whoami',{});assert(success.json.result?.structuredContent);assert.equal(s.store.calls.size,1);assert.equal([...s.store.calls.values()][0]!.lifecycle,'finished');const unknown=await s.call('not_a_real_tool',{});assert(unknown.json.error||unknown.json.result?.isError);const bad=await s.call('at_file_stage',{ticket:{kind:'id',id:1001},file:'RAW_FILE_ID_CANARY'});assert(bad.json.error||bad.json.result?.isError);assert.equal(s.store.calls.size,3);assert([...s.store.calls.values()].every(c=>c.lifecycle==='finished'));assert.equal([...s.store.calls.values()].filter(c=>c.outcome==='rejected').length,2);assert.doesNotMatch(JSON.stringify([...s.store.events.values()]),/RAW_FILE_ID_CANARY/);assert.equal(s.f.adapter.calls.filter(c=>c.kind==='create'||c.kind==='patch').length,0);});
test('HTTP admission rejects execution when neither durable sink can record its start',async t=>{const s=await setup(t);s.store.append=async()=>{throw Error('offline');};s.spool.append=async()=>{throw Error('disk offline');};const denied=await s.call('ticket_context',{ticket:{kind:'id',id:1001},purpose:'custom',collections:['notes']});assert(denied.json.error||denied.json.result?.isError||denied.json.error);assert.equal(s.f.adapter.calls.length,0);assert.equal(s.diagnostics.ready(),false);assert.equal((await fetch(s.base+'/health/ready')).status,503);});
test('HTTP terminal storage failure preserves accepted write result and blocks subsequent admission',async t=>{const s=await setup(t);s.f.adapter.getTicketNote=async()=>{throw new AppError('dependency_unavailable','Synthetic readback failed.');};const append=s.store.append.bind(s.store),spoolAppend=s.spool.append.bind(s.spool);s.store.append=async e=>{if(e.type==='call.finished')throw Error('terminal store offline');return append(e);};s.spool.append=async(e,terminal)=>{if(e.type==='call.finished')throw Error('terminal spool offline');return spoolAppend(e,terminal);};const accepted=await s.call('ticket_note_add',{ticket:{kind:'id',id:1001},note:{title:'Synthetic title',text:'Synthetic text',audience:'internal'},request_key:'http-terminal-failure'});assert.equal(accepted.json.result.structuredContent.status,'accepted_unverified');assert(accepted.json.result.structuredContent.operation_id);assert.equal(s.f.adapter.calls.filter(c=>c.kind==='create'&&c.entity==='TicketNotes').length,1);assert.equal(s.diagnostics.ready(),false);const before=s.f.adapter.calls.length;await s.call('ticket_context',{ticket:{kind:'id',id:1001},purpose:'custom',collections:['notes']});assert.equal(s.f.adapter.calls.length,before);s.store.append=append;s.spool.append=spoolAppend;await s.diagnostics.maintenance();assert.equal([...s.store.calls.values()][0]!.outcome,'accepted_unverified');});

test('HTTP at_invoke has one incoming root and one correlated logical child',async t=>{const s=await setup(t),result=await s.call('at_invoke',{operation:'ticket_context',arguments:{ticket:{kind:'id',id:1001},purpose:'custom',collections:['assets']}});assert(result.json.result?.structuredContent);const calls=[...s.store.calls.values()],root=calls.find(c=>c.source==='mcp')!,child=calls.find(c=>c.source==='nested')!;assert.equal(calls.length,2);assert.equal(root.tool,'at_invoke');assert.equal(root.requestedTool,'ticket_context');assert.equal(child.parentId,root.callId);assert.equal(child.traceId,root.traceId);assert.equal(child.lifecycle,'finished');assert.equal(root.lifecycle,'finished');});
