import {test} from 'node:test';import assert from 'node:assert/strict';import {readFile} from 'node:fs/promises';import {PGlite} from '@electric-sql/pglite';
import {IntentCipher} from '../packages/storage/src/index.js';import {fixturePrincipals} from '../packages/workflows/src/fixtures.js';
import {DurableReadReports,DurableReadWorker} from '../packages/durable-read-jobs/src/index.js';import {MemoryReadJobStore,PostgresReadJobStore,type ReadJobStore} from '../packages/durable-read-jobs/src/store.js';
function setup(store:ReadJobStore=new MemoryReadJobStore()){const p=fixturePrincipals()[0]!,cipher=new IntentCipher(Buffer.alloc(32,7));let now=Date.now();const principals={get:async()=>p},reports=new DurableReadReports(store,cipher,principals,async(_p,input,{guard})=>{await guard();return{company:input.company_id,secret:'fixture report content'};},()=>now);return{p,store,cipher,reports,advance:(ms:number)=>{now+=ms;},now:()=>now};}
for(const sql of [false,true])test(`durable read ${sql?'Postgres':'memory'}: reserve, fence, cancel, restart, expiry`,async()=>{
 const db=sql?new PGlite():undefined;if(db){await db.exec('CREATE TABLE schema_migrations(version text PRIMARY KEY)');await db.exec(await readFile('packages/storage/migrations/018_durable_read_jobs.sql','utf8'));}const s=setup(db?new PostgresReadJobStore(db):undefined);
 try{const a={company_id:10,request_key:'report-one'},j=await s.reports.start(s.p,a);assert.equal((await s.reports.start(s.p,a)).report_id,j.report_id);await assert.rejects(s.reports.start(s.p,{...a,max_items:1}),/different/);
 const first=await s.store.claim('first',s.now(),100);assert.ok(first);s.advance(101);const second=await s.store.claim('second',s.now(),100);assert.ok(second);assert.equal(second.fence,first.fence+1);assert.equal(await s.store.finish(first,s.now(),'completed','stale',null),false);assert.equal(await s.store.renew(first,s.now(),100),false);assert.equal(await s.store.renew(second,s.now(),100),true);
 await s.reports.cancel(s.p,j.report_id);assert.equal(await s.store.finish(second,s.now(),'completed','late',null),false);assert.equal((await s.reports.status(s.p,j.report_id)).state,'cancelled');
 const other=await s.reports.start(s.p,{company_id:10,request_key:'report-two'});await new DurableReadWorker(s.reports).tick();const result=await s.reports.result(s.p,other.report_id);assert.equal(result.state,'completed');assert.deepEqual(result.data,{company:10,secret:'fixture report content'});const raw=await s.store.get(s.p.tenantId,s.p.objectId,other.report_id,s.now());assert.ok(raw&&!raw.input.includes('company_id')&&!raw.result!.includes('fixture report content'));
 await assert.rejects(s.reports.result({...s.p,objectId:'another'},other.report_id),/unavailable/);s.p.companyIds=[];await assert.rejects(s.reports.result(s.p,other.report_id));s.p.companyIds=[10];s.advance(86400001);await assert.rejects(s.reports.result(s.p,other.report_id),/expired/);await s.store.purge(s.now());if(db)assert.equal((await db.query('SELECT * FROM durable_read_jobs')).rows.length,0);
 }finally{await db?.close();}
});
test('four pending report quota and restart attempt exhaustion',async()=>{const s=setup();for(let n=0;n<4;n++)await s.reports.start(s.p,{company_id:10,request_key:`request-${n}`});await assert.rejects(s.reports.start(s.p,{company_id:10,request_key:'request-extra'}),/Four pending/);const j=await s.store.claim('a',s.now(),1);assert.ok(j);s.advance(2);await s.store.claim('b',s.now(),1);s.advance(2);await s.store.claim('c',s.now(),1);s.advance(2);await s.store.claim('d',s.now(),1);assert.equal((await s.reports.status(s.p,j.id)).state,'failed');});
test('report deadline bounds a noncooperative read and preserves no successful result',async()=>{const s=setup(),reports=new DurableReadReports(s.store,s.cipher,{get:async()=>s.p},async()=>new Promise(()=>{}));const job=await reports.start(s.p,{company_id:10,request_key:'deadline-test'}),worker=new DurableReadWorker(reports,30,60);const keepAlive=setTimeout(()=>{},500);try{await worker.tick();assert.equal((await reports.status(s.p,job.report_id)).state,'failed');}finally{clearTimeout(keepAlive);await worker.close();}});
test('report result access rechecks section permissions after completion',async()=>{const s=setup();s.p.capabilities.push('rmm.read');const job=await s.reports.start(s.p,{company_id:10,request_key:'rmm-report',sections:['devices']});await new DurableReadWorker(s.reports).tick();s.p.capabilities=s.p.capabilities.filter(c=>c!=='rmm.read');await assert.rejects(s.reports.result(s.p,job.report_id));});
test('renewal retains ownership during a read longer than its initial lease',async()=>{const s=setup(),reports=new DurableReadReports(s.store,s.cipher,{get:async()=>s.p},async()=>{await new Promise(r=>setTimeout(r,160));return{ok:true};});const job=await reports.start(s.p,{company_id:10,request_key:'renewal-report'}),worker=new DurableReadWorker(reports,60,240);const running=worker.tick();await new Promise(r=>setTimeout(r,95));assert.equal(await s.store.claim('competitor',Date.now(),60),undefined);await running;assert.equal((await reports.status(s.p,job.report_id)).state,'completed');await worker.close();});
