import {test} from 'node:test';
import assert from 'node:assert/strict';
import {createServer} from 'node:http';
import {once} from 'node:events';
import {setTimeout as delay} from 'node:timers/promises';
import {createApplication,streamingResponse,type ApplicationOptions} from '../apps/server/src/app.js';
import {createNodeHandler} from '../apps/server/src/ingress.js';
import {createFixtureSystem} from '../apps/server/src/fixture-system.js';
import {createExecution,currentExecution,providerFetch,withExecution,withReconciliation,type ExecutionContext} from '../packages/execution/src/index.js';
function deferred<T=void>(){let resolve!:(value:T)=>void;const promise=new Promise<T>(r=>resolve=r);return{promise,resolve};}
const deadline=<T>(p:Promise<T>)=>Promise.race([p,delay(2500).then(()=>{throw Error('Timed out waiting for test lifecycle');})]);
async function serverFixture(options:Partial<ApplicationOptions>={}){let handler:ReturnType<typeof createNodeHandler>;const server=createServer((a,b)=>handler(a,b));server.listen(0,'127.0.0.1');await once(server,'listening');const address=server.address();assert(address&&typeof address!=='string');const base=`http://127.0.0.1:${address.port}`,s=createFixtureSystem(base),app=createApplication({publicUrl:base,authenticate:s.authenticate,workflows:s.core,writes:s.writes,runtime:s.runtime,maxConcurrent:1,...options});handler=createNodeHandler(app);const request=(signal?:AbortSignal,method='tools/call')=>fetch(base+'/mcp',{signal,method:'POST',headers:{authorization:`Bearer ${s.tokens[0]!.token}`,'content-type':'application/json',accept:'application/json, text/event-stream','mcp-protocol-version':'2025-11-25'},body:JSON.stringify({jsonrpc:'2.0',id:1,method,params:method==='tools/call'?{name:'at_whoami',arguments:{},_meta:{progressToken:'test-progress'}}:{}})});return{s,app,request,async close(){await app.close();await s.app.close();await s.worker.close();server.closeAllConnections();await new Promise<void>(r=>server.close(()=>r()));}};}
test('actual HTTP disconnect reaches SDK execution and provider read signal',async t=>{const f=await serverFixture();t.after(()=>f.close());const entered=deferred(),aborted=deferred();let context:ExecutionContext|undefined;const tool=f.s.runtime.tools.find(t=>t.name==='at_whoami')!,original=tool.run;const provider=providerFetch('fixture',async(_url,init)=>{assert(init?.signal);entered.resolve();await new Promise<void>(resolve=>{init.signal!.addEventListener('abort',()=>{aborted.resolve();resolve();},{once:true});});throw new DOMException('Cancelled','AbortError');});tool.run=async(p,a)=>{context=currentExecution();await provider('https://fixture.test/api/devices/private-id');return original(p,a);};const abort=new AbortController(),pending=f.request(abort.signal);await deadline(entered.promise);const response=await deadline(pending);assert.equal(response.status,200);abort.abort();await deadline(aborted.promise);assert.equal(context?.signal.aborted,true);});
test('disconnected native mutation retains admission until its verification finishes',async t=>{const f=await serverFixture();t.after(()=>f.close());const entered=deferred(),release=deferred(),verified=deferred(),cancelled=deferred();let count=0;const provider=providerFetch('fixture',async(_url,init)=>{if(init?.method==='POST'){assert.equal(init.signal,undefined,'Client cancellation must not abort possibly accepted mutation');entered.resolve();await release.promise;}else verified.resolve();count++;return Response.json({id:1});});const tool=f.s.runtime.tools.find(t=>t.name==='at_whoami')!,original=tool.run;tool.run=async(p,a)=>{currentExecution()!.signal.addEventListener('abort',()=>cancelled.resolve(),{once:true});await provider('https://fixture.test/Tickets',{method:'POST'});await withReconciliation(()=>provider('https://fixture.test/Tickets/1'));return original(p,a);};const abort=new AbortController(),pending=f.request(abort.signal);try{await deadline(entered.promise);await deadline(pending);abort.abort();await deadline(cancelled.promise);const busy=await f.request(undefined,'tools/list');assert.equal(busy.status,429);release.resolve();await deadline(verified.promise);for(let i=0;i<30;i++){const next=await f.request(undefined,'tools/list');if(next.status===200){await next.text();assert.equal(count,2);return;}assert.equal(next.status,429);await delay(10);}assert.fail('Admission was not released after mutation settled');}finally{release.resolve();}});
test('stream cancellation and byte overflow clean up exactly once',async()=>{let closed=0,cancelled=0;const source=new ReadableStream<Uint8Array>({pull(c){c.enqueue(new Uint8Array(4*1024*1024+1));},cancel(){cancelled++;}}),response=streamingResponse(new Response(source,{headers:{'content-type':'text/event-stream','content-length':'999'}}),new AbortController().signal,async()=>{closed++;});assert.equal(response.headers.get('content-length'),null);await assert.rejects(response.body!.getReader().read(),/bounded stream limit/);await delay(0);assert.equal(cancelled,1);assert.equal(closed,1);});
test('stream deadline cancels pending source and preserves explicit no-store headers',async()=>{let closed=0;const context=createExecution(new AbortController().signal,{timeoutMs:20}),response=streamingResponse(new Response(new ReadableStream<Uint8Array>({start(){}}),{headers:{'content-type':'text/event-stream'}}),context.signal,async()=>{closed++;});assert.equal(response.headers.get('cache-control'),'no-store');await assert.rejects(deadline(response.body!.getReader().read()),/cancelled or expired/);await delay(0);assert.equal(closed,1);});
test('provider Request input query/auth are cancellable reads and Request signal is preserved',async()=>{const context=createExecution(new AbortController().signal),controller=new AbortController();let signal:AbortSignal|undefined;const provider=providerFetch('Datto RMM',async(_url,init)=>{signal=init?.signal??undefined;return Response.json({});});await withExecution(context,()=>provider('https://zinfandel-api.centrastage.net/auth/oauth/token',{method:'POST'}));assert.equal(context.effectStarted,false,'Credential token exchange is not a business mutation');await withExecution(context,()=>provider(new Request('https://fixture.test/Tickets/query',{method:'POST',signal:controller.signal})));assert.equal(context.effectStarted,false,'POST query Request must remain a read');controller.abort();assert.equal(signal?.aborted,true);});
test('synchronously serialized trace sink has status but no credentials, native IDs or bodies',async()=>{const serialized:string[]=[],context=createExecution(new AbortController().signal,{sink:event=>serialized.push(JSON.stringify(event))}),provider=providerFetch('fixture',async()=>Response.json({secret:'BODY_SECRET'},{status:201}));await withExecution(context,()=>provider('https://fixture.test/Tickets/NATIVE_ID?token=QUERY_SECRET',{headers:{authorization:'Bearer HEADER_SECRET'},method:'POST',body:'BODY_SECRET'}));const raw=serialized.join('');assert.match(raw,/"http_status":201/);assert.doesNotMatch(raw,/BODY_SECRET|HEADER_SECRET|QUERY_SECRET|NATIVE_ID|fixture\.test/);});
test('actual HTTP request deadline ends progress stream and aborts outstanding read',async t=>{const f=await serverFixture({requestTimeoutMs:1000});t.after(()=>f.close());const entered=deferred(),aborted=deferred();const tool=f.s.runtime.tools.find(t=>t.name==='at_whoami')!,original=tool.run;const provider=providerFetch('fixture',async(_url,init)=>{entered.resolve();await new Promise<void>(resolve=>{if(init?.signal?.aborted){aborted.resolve();resolve();}else init?.signal?.addEventListener('abort',()=>{aborted.resolve();resolve();},{once:true});});throw new DOMException('Deadline','AbortError');});tool.run=async(p,a)=>{await withReconciliation(()=>provider('https://fixture.test/Tickets/1'));return original(p,a);};const pending=f.request();await deadline(entered.promise);const response=await deadline(pending),reader=response.body!.getReader();const first=await reader.read();assert.match(new TextDecoder().decode(first.value),/notifications\/progress/);await deadline(aborted.promise);await assert.rejects(deadline((async()=>{while(!(await reader.read()).done){}})()));});
test('unconsumed streaming response applies bounded pull backpressure',async()=>{let pulls=0;const source=new ReadableStream<Uint8Array>({pull(c){pulls++;c.enqueue(new Uint8Array(8192));}}),response=streamingResponse(new Response(source),new AbortController().signal,async()=>{});await delay(20);assert(pulls<=4,`Unconsumed source pulled ${pulls} chunks`);await response.body!.cancel();});
