import test from 'node:test';
import assert from 'node:assert/strict';
import {InvestigationService,investigationOutput} from '../packages/investigations/src/index.js';
import {fixturePrincipals} from '../packages/workflows/src/fixtures.js';
import {AppError,type Principal} from '../packages/contracts/src/index.js';
type Row=Record<string,any>;
function setup(){const p={...fixturePrincipals()[0]!,capabilities:['operational.read','rmm.read']} as Principal,state={p,moved:false,unavailable:false,denied:false},calls:Row[]=[];
 const invoke=async(_p:Principal,tool:string,args:unknown)=>{calls.push({tool,args});if(tool==='rmm_device_get')return{data:{uid:'device-a',siteUid:state.moved?'site-b':'site-a'},completeness:{complete:true}};if(tool==='rmm_device_audit_get'){if(state.denied)throw new AppError('forbidden','denied');if(state.unavailable)throw new AppError('dependency_unavailable','offline');return{data:{bios:{serialNumber:'123'}},completeness:{complete:true},provenance:{fetched_at:'2026-09-18T00:00:00Z'}};}if(tool==='rmm_device_alert_list')return{data:{alerts:[{id:1},{id:2}]},completeness:{complete:false,next_cursor:'alerts-next'},provenance:{fetched_at:'2026-09-18T00:00:00Z'}};if(tool==='ticket_context')return{data:{ticket:{id:1001,companyID:10},collections:{}},completeness:{complete:true}};if(tool==='ticket_environment_context')return{data:{rmm:{complete:false,continuations:[{cursor:'rmm-next'}]}},completeness:{complete:false}};if(tool==='ticket_search')return{data:{tickets:[{id:1001,title:'Exact title'}]},completeness:{complete:true}};if(tool==='client_inventory_compare')return{data:{candidates:[],limitations:['No verified identities']},completeness:{complete:false}};throw Error(tool);};return{p,state,calls,service:new InvestigationService({get:async()=>state.p},invoke)};}
test('one device investigation returns independent source evidence, original timestamps and drilldowns',async()=>{const f=setup(),r=await f.service.run(f.p,'device_investigate',{device_uid:'device-a',max_items:1});assert(investigationOutput.safeParse(r).success);assert.equal(r.status,'partial');const audit=r.data.sections.find(s=>s.section==='audit')!;assert.deepEqual(audit.provenance,{fetched_at:'2026-09-18T00:00:00Z'});const alerts=r.data.sections.find(s=>s.section==='alerts')!;assert.equal((alerts.evidence as Row).alerts.length,1);assert.equal(alerts.continuations[0]!.cursor,'alerts-next');assert.equal(alerts.drill_down.tool,'rmm_device_alert_list');assert.equal(f.calls.filter(c=>c.tool==='rmm_device_get').length,2);});
test('provider failure is independent but permission failure and moved device fail closed',async()=>{const f=setup();f.state.unavailable=true;assert.equal((await f.service.run(f.p,'device_investigate',{device_uid:'device-a'})).data.sections.find(s=>s.section==='audit')!.status,'unavailable');f.state.denied=true;await assert.rejects(()=>f.service.run(f.p,'device_investigate',{device_uid:'device-a'}),{code:'forbidden'});const g=setup(),original=g.service.invoke;const service=new InvestigationService(g.service.principals,async(p,n,a)=>{const r=await original(p,n,a);if(n==='rmm_device_alert_list')g.state.moved=true;return r;});await assert.rejects(()=>service.run(g.p,'device_investigate',{device_uid:'device-a'}),{code:'conflict'});});
test('client overview keeps requested company filters and skips unselected provider sections',async()=>{const f=setup(),r=await f.service.run(f.p,'client_overview',{company:10,sections:['tickets']});assert.equal(r.data.sections.length,1);assert.equal(f.calls.length,1);assert.deepEqual(f.calls[0]!.args.company,{kind:'id',id:10});assert.equal(f.calls[0]!.args.open_only,true);await assert.rejects(()=>f.service.run(f.p,'client_overview',{company:999}));assert.equal(f.calls.length,1);});
test('ticket investigation returns partial context as evidence without claiming absent findings',async()=>{const f=setup(),r=await f.service.run(f.p,'ticket_investigate',{ticket:{kind:'id',id:1001}});assert(investigationOutput.safeParse(r).success);assert.equal(r.status,'partial');assert.equal(r.data.sections.length,2);assert(r.limitations.some(s=>s.includes('not evidence of absence')));});

test('all investigation contracts execute against real scoped ToolRuntime primitives',async t=>{
 const {createFixtureSystem}=await import('../apps/server/src/fixture-system.js');const f=createFixtureSystem();t.after(()=>f.app.close());const old=f.principals[0]!,p={...old,capabilities:[...old.capabilities,'rmm.read' as const,'documentation.read' as const,'platform.manage' as const],mappingVersion:old.mappingVersion+1};await f.controlStore.saveMember(old,p,old.mappingVersion,new Date().toISOString());
 const r=f.runtime.options.rmm!;await r.configure(p,{version:0,platform:'zinfandel',key:'key',secret:'secret',enabled:false,jobs_enabled:false});await r.test(p);await r.configure(p,{version:2,platform:'zinfandel',enabled:true,jobs_enabled:false});await r.mapSite(p,{version:3,site_uid:'example-site',enabled:true});
 const original=r.port.request.bind(r.port);r.port.request=async(c,path,q={},...rest)=>{if(path.endsWith('/alerts/open'))return{alerts:[],pageDetails:{nextPageUrl:null}};if(path.endsWith('/example-device')&&path.includes('/audit/'))return{bios:{serialNumber:'FIXTURE-001'}};return original(c,path,q,...rest);};
 const glue=f.runtime.options.itglue!;await glue.configure(p,{version:0,region:'us',key:'fixture-glue-key',enabled:false,writes_enabled:false});await glue.mapOrganization(p,{version:1,company:10,organization_id:'100',enabled:true});await glue.configure(p,{version:2,region:'us',enabled:true,writes_enabled:false});
 const service=new InvestigationService(f.store,(p,n,a)=>f.runtime.invoke(p,n,a));
 for(const [name,args]of [['ticket_investigate',{ticket:{kind:'id',id:1001}}],['client_overview',{company:10}],['device_investigate',{device_uid:'example-device'}]] as const){const result=await f.runtime.invoke(p,name,args) as Row;assert(investigationOutput.safeParse(result).success,name);assert(result.data.sections.length>0);}
});
