import {test} from 'node:test';
import assert from 'node:assert/strict';
import {randomBytes} from 'node:crypto';
import {isInputRequiredResult} from '@modelcontextprotocol/server';
import type {Principal} from '../packages/contracts/src/index.js';
import {IntentCipher} from '../packages/storage/src/intent-cipher.js';
import {MemorySelectionReplayStore,ReadSelectionContinuation} from '../packages/durable-read-jobs/src/interactive.js';
import {CompanySelection,companySelectionOutput,type SelectionInteraction} from '../packages/read-selection/src/index.js';
const interaction:SelectionInteraction={protocol:'2026-07-28',capabilities:{elicitation:{form:{}}}};
function fixture(enabled=true){const p:Principal={tenantId:'tenant',objectId:'actor',resourceId:1,mappingVersion:1,policyVersion:'v1',capabilities:['operational.read'],companyIds:[10,20],active:true,resourceVerifiedAt:new Date().toISOString()},rows=[{id:10,companyName:'Example North'},{id:20,companyName:'Example South'}],calls:{name:string;args:any}[]=[];let partial=false;const service=new CompanySelection(new ReadSelectionContinuation(new IntentCipher(randomBytes(32)),new MemorySelectionReplayStore()),{get:async()=>p},async(_p,name,args:any)=>{calls.push({name,args});if(name==='at_query'){const id=args.filter.conditions.find((f:any)=>f.field==='id')?.value,query=args.filter.conditions.find((f:any)=>f.field==='companyName').value;return{status:partial?'partial':'succeeded',data:{entity:'Companies',items:rows.filter(r=>(id===undefined||r.id===id)&&r.companyName.includes(query))},completeness:{complete:!partial,next_cursor:partial?'native-cursor':null}};}return{status:'succeeded',data:{entity:'Companies',item:rows.find(r=>r.id===args.id)}};},{mrtrEnabled:enabled});return{p,rows,calls,service,setPartial:(v:boolean)=>partial=v};}
test('company selection uses only server-owned scoped queries and ordinary host fallback',async()=>{const {p,service,calls}=fixture();const r=await service.run(p,{query:'Example'},{protocol:'2025-11-25',capabilities:{}});assert(companySelectionOutput.safeParse(r).success);assert.equal((r as any).status,'requires_selection');assert.equal((r as any).candidates.length,2);assert.equal(calls[0]?.name,'at_query');assert.deepEqual(calls[0]?.args.fields,['id','companyName']);await assert.rejects(service.run(p,{query:'Example',candidates:[{id:999,label:'injected'}]}));});
test('opt-in modern selection yields SDK marker and freshly validates accepted company once',async()=>{const {p,service,calls}=fixture();const offered=await service.run(p,{query:'Example'},interaction);assert(isInputRequiredResult(offered));const resumed=await service.run(p,{query:'Example'},{...interaction,requestState:offered.requestState,inputResponses:{selection:{action:'accept',content:{selected_id:'20'}}}});assert.equal((resumed as any).status,'selected');assert.deepEqual((resumed as any).company,{id:20,name:'Example South'});assert(calls.some(c=>c.name==='at_get'&&c.args.id===20));await assert.rejects(service.run(p,{query:'Example'},{...interaction,requestState:offered.requestState,inputResponses:{selection:{action:'accept',content:{selected_id:'20'}}}}),/already used/);assert(calls.every(c=>['at_get','at_query'].includes(c.name)));});
test('host flag false never emits MRTR even when capabilities are advertised',async()=>{const {p,service}=fixture(false);const offered=await service.run(p,{query:'Example'},interaction);assert.equal(isInputRequiredResult(offered),false);assert.equal((offered as any).status,'requires_selection');});
test('changed query, scope revocation and changed candidate block resumed selection',async()=>{for(const change of ['query','scope','name'] as const){const {p,service,rows}=fixture();const offered=await service.run(p,{query:'Example'},interaction);assert(isInputRequiredResult(offered));if(change==='scope')p.companyIds=[10];if(change==='name')rows[1]!.companyName='Unrelated';await assert.rejects(service.run(p,{query:change==='query'?'North':'Example'},{...interaction,requestState:offered.requestState,inputResponses:{selection:{action:'accept',content:{selected_id:'20'}}}}));}});
test('partial candidate lists never imply unique match or MRTR completeness',async()=>{const {p,service,setPartial}=fixture();setPartial(true);const r=await service.run(p,{query:'North'},interaction);assert.equal(isInputRequiredResult(r),false);assert.equal((r as any).status,'requires_selection');assert.equal((r as any).completeness.complete,false);assert.equal((r as any).completeness.next_cursor,null);assert.match((r as any).limitations[0],/Narrow/);});
test('ordinary exact selection verifies matching query and cancellation consumes without record action',async()=>{const {p,service,calls}=fixture();const selected=await service.run(p,{query:'Example',selected_id:10});assert.equal((selected as any).company.id,10);await assert.rejects(service.run(p,{query:'North',selected_id:20}),/no longer matches/);const offered=await service.run(p,{query:'Example'},interaction);assert(isInputRequiredResult(offered));const before=calls.length;const cancelled=await service.run(p,{query:'Example'},{...interaction,requestState:offered.requestState,inputResponses:{selection:{action:'cancel'}}});assert.equal((cancelled as any).status,'cancelled');assert.equal(calls.length,before);});
