import test from 'node:test';
import assert from 'node:assert/strict';
import {randomBytes} from 'node:crypto';
import {readFile} from 'node:fs/promises';
import {PGlite} from '@electric-sql/pglite';
import {RmmService} from '../packages/rmm/src/service.js';
import {MemoryRmmStore,PostgresRmmStore,emptyConfig,type RmmConfig,type Row} from '../packages/rmm/src/store.js';
import {RmmClient,type RmmPort} from '../packages/rmm/src/client.js';
import {IntentCipher} from '../packages/storage/src/intent-cipher.js';
import {fixturePrincipals} from '../packages/workflows/src/fixtures.js';
import {actorKey,type Principal} from '../packages/contracts/src/index.js';
import {rmmOutput,schemas} from '../packages/rmm/src/contracts.js';
class Port implements RmmPort {
 calls:string[]=[];dispatches=0;payloads:unknown[]=[];futureComponents:Row[]=[];site='site-a';company='10';unknown=false;changed=false;next=false;foreign=false;
 component={uid:'component-a',name:'Diagnostics',description:'Reviewed diagnostic',credentialsRequired:false,variables:[]};
 async request(c:RmmConfig,path:string,q:Row={},body?:unknown,guard?:()=>Promise<void>,beforeWrite?:()=>Promise<void>):Promise<Row>{await guard?.();this.calls.push(path);if(body){await beforeWrite?.();this.dispatches++;this.payloads.push(structuredClone(body));if(this.unknown)throw new Error('lost response');return{job:{uid:'job-a'}};}
 if(path==='/v2/account')return{uid:'account-a'};
 if(path==='/v2/account/components')return{components:[{...this.component,...(this.changed?{name:'Changed'}:{})},...this.futureComponents],pageDetails:{nextPageUrl:null}};
 if(path==='/v2/account/sites')return{sites:[{uid:'site-a',name:'Client A',autotaskCompanyId:'10'}],pageDetails:{nextPageUrl:null}};
 if(path==='/v2/site/site-a'||path==='/v2/site/site-b')return{uid:path.split('/')[3],autotaskCompanyId:this.company,name:'Client A'};
 if(path.endsWith('/devices'))return{devices:[{uid:'device-a',siteUid:this.foreign?'site-b':'site-a',hostname:'PC-01',unknownSecret:'LEAK'}],pageDetails:{nextPageUrl:this.next?'https://evil.invalid':'',totalCount:200}};
 if(path.endsWith('/software'))return{software:[],pageDetails:{nextPageUrl:null}};
 if(path.endsWith('/patches'))return{patches:[],pageDetails:{nextPageUrl:null}};
 if(path.endsWith('/filters'))return{filters:[],pageDetails:{nextPageUrl:null}};
 if(path.endsWith('/network-interface'))return{devices:[],pageDetails:{nextPageUrl:null}};
 if(path.includes('/alerts/'))return{alerts:[],pageDetails:{nextPageUrl:null}};
 if(path==='/v2/alert/alert-a')return{alertUid:'alert-a',alertSourceInfo:{deviceUid:'device-a',siteUid:'site-a'},resolved:false};
 if(path==='/v2/audit/device/device-a')return{systemInfo:{},logicalDisks:[]};
 if(path==='/v2/device/device-a')return{uid:'device-a',siteUid:this.site,hostname:'PC-01',deviceClass:'device',online:true,secret:'LEAK'};
 if(path==='/v2/job/job-a')return{uid:'job-a',status:'completed'};
 if(path==='/v2/job/job-a/results/device-a')return{jobUid:'job-a',deviceUid:'device-a',jobDeploymentStatus:'Success',componentResults:[]};
 if(path.endsWith('/stdout'))return[{componentUid:'component-a',stdData:'password=SECRET token=TOKEN Done'}] as any;
 throw new Error('Unexpected route '+path);
 }
}
function setup(){const p:Principal={...fixturePrincipals()[0]!,capabilities:['operational.read','platform.manage','rmm.read','rmm.execute'],resourceVerifiedAt:new Date().toISOString()},state={principal:p},store=new MemoryRmmStore(),port=new Port(),cipher=new IntentCipher(randomBytes(32));const service=new RmmService(store,port,{get:async()=>state.principal},cipher);return{p,state,store,port,cipher,service};}
async function enabled(){const s=setup();await s.service.configure(s.p,{version:0,platform:'zinfandel',key:'API_KEY',secret:'API_SECRET',enabled:false,jobs_enabled:false});await s.service.test(s.p);await s.service.configure(s.p,{version:2,platform:'zinfandel',enabled:true,jobs_enabled:true});await s.service.mapSite(s.p,{version:3,site_uid:'site-a',enabled:true});await s.service.approve(s.p,{version:4,component_uid:'component-a',approved:true,variables:{}});return s;}
test('RMM credentials are write-only; connection verification and native company mappings required',async()=>{const s=setup();await assert.rejects(()=>s.service.configure(s.p,{version:0,platform:'zinfandel',key:'API_KEY',secret:'API_SECRET',enabled:true,jobs_enabled:false}));await s.service.configure(s.p,{version:0,platform:'zinfandel',key:'API_KEY',secret:'API_SECRET',enabled:false,jobs_enabled:false});assert.doesNotMatch(JSON.stringify(await s.service.status(s.p)),/API_KEY|API_SECRET/);await assert.rejects(()=>s.service.configure(s.p,{version:0,platform:'zinfandel',enabled:false,jobs_enabled:false}));await s.service.test(s.p);s.port.company='20';await assert.rejects(()=>s.service.mapSite(s.p,{version:2,site_uid:'site-a',enabled:true}));});
test('RMM scoped reads project known fields and reject foreign site and revoked access',async()=>{const s=await enabled();const r=await s.service.run(s.p,'rmm_device_get',{device_uid:'device-a'});assert.equal(r.data.hostname,'PC-01');assert.doesNotMatch(JSON.stringify(r),/LEAK/);assert(rmmOutput.safeParse(r).success);s.port.site='foreign';await assert.rejects(()=>s.service.run(s.p,'rmm_device_get',{device_uid:'device-a'}));s.port.site='site-a';s.state.principal={...s.p,capabilities:[]};await assert.rejects(()=>s.service.run(s.p,'rmm_device_get',{device_uid:'device-a'}));});
test('RMM continuation is bound to actor, filter and configuration; never follows supplied URL',async()=>{const s=await enabled();s.port.next=true;const r=await s.service.run(s.p,'rmm_device_search',{site_uid:'site-a'});assert.equal(r.status,'partial');assert(r.completeness.next_cursor);await s.service.run(s.p,'rmm_device_search',{site_uid:'site-a',cursor:r.completeness.next_cursor});assert(!s.port.calls.some(p=>p.includes('evil')));await assert.rejects(()=>s.service.run(s.p,'rmm_device_search',{site_uid:'site-a',hostname:'different',cursor:r.completeness.next_cursor}));s.port.foreign=true;await assert.rejects(()=>s.service.run(s.p,'rmm_device_search',{site_uid:'site-a'}));});
test('quick jobs require approval, reject changed metadata and never replay an uncertain dispatch',async()=>{const s=await enabled(),a={device_uid:'device-a',component_uid:'component-a',job_name:'Diagnostics',request_key:'request-12345'};s.port.changed=true;await assert.rejects(()=>s.service.run(s.p,'rmm_quickjob_run',a));assert.equal(s.port.dispatches,0);s.port.changed=false;s.port.unknown=true;const r=await s.service.run(s.p,'rmm_quickjob_run',a);assert.equal(r.status,'unknown_outcome');const retry=await s.service.run(s.p,'rmm_quickjob_run',a);assert.equal(retry.status,'unknown_outcome');assert.equal(s.port.dispatches,1);await assert.rejects(()=>s.service.run(s.p,'rmm_quickjob_run',{...a,job_name:'Other'}));});
test('all-component access includes future non-credential components with their defaults',async()=>{const s=await enabled();s.port.futureComponents=[{uid:'component-future',name:'Future maintenance',credentialsRequired:false,variables:[{name:'Mode',defaultVal:'Datto default'}]},{uid:'component-secret',name:'Credentialed action',credentialsRequired:true,variables:[]}];const before=await s.service.catalogue(s.p,'components',{page:0});assert.equal(before.items.find(v=>v.uid==='component-future')!.approved,false);await s.service.configure(s.p,{version:5,platform:'zinfandel',enabled:true,jobs_enabled:true,all_components_enabled:true});const after=await s.service.catalogue(s.p,'components',{page:0});assert.equal(after.items.find(v=>v.uid==='component-future')!.approved,true);assert.equal(after.items.find(v=>v.uid==='component-secret')!.approved,false);await s.service.run(s.p,'rmm_quickjob_run',{device_uid:'device-a',component_uid:'component-future',job_name:'Future maintenance',request_key:'future-component-1'});assert.deepEqual((s.port.payloads[0] as any).jobComponent.variables,[{name:'Mode',value:'Datto default'}]);await assert.rejects(()=>s.service.run(s.p,'rmm_quickjob_run',{device_uid:'device-a',component_uid:'component-secret',job_name:'Credentialed action',request_key:'credential-component-1'}));assert.equal(s.port.dispatches,1);});
test('accepted jobs have separate result/output reads; moved devices cannot read old job output',async()=>{const s=await enabled();const r=await s.service.run(s.p,'rmm_quickjob_run',{device_uid:'device-a',component_uid:'component-a',job_name:'Diagnostics',request_key:'request-12345'});assert.equal(r.status,'accepted');const args={operation_id:r.data.operation_id};assert.equal((await s.service.run(s.p,'rmm_job_result_get',args)).data.jobDeploymentStatus,'Success');const output=await s.service.run(s.p,'rmm_job_output_get',{...args,stream:'stdout'});assert.doesNotMatch(JSON.stringify(output),/SECRET|TOKEN/);s.port.site='foreign';await assert.rejects(()=>s.service.run(s.p,'rmm_job_output_get',{...args,stream:'stdout'}));});
test('credential replacement clears approvals and mappings and disables untested connection',async()=>{const s=await enabled();await s.service.configure(s.p,{version:5,platform:'zinfandel',key:'NEW_KEY',secret:'NEW_SECRET',enabled:false,jobs_enabled:false});const c=await s.service.status(s.p);assert.deepEqual(c.sites,{});assert.deepEqual(c.approvals,{});assert.equal(c.account_uid,null);await assert.rejects(()=>s.service.run(s.p,'rmm_site_list',{}));});
test('RMM PostgreSQL encrypts credentials and job payloads; versions and duplicate keys are atomic',async()=>{const db=new PGlite(),cipher=new IntentCipher(randomBytes(32));try{await db.exec('CREATE TABLE schema_migrations(version text PRIMARY KEY)');await db.exec(await readFile('packages/storage/migrations/014_rmm.sql','utf8'));const store=new PostgresRmmStore(db,cipher),c={...emptyConfig(),version:1,key:'PRIVATE_KEY',secret:'PRIVATE_SECRET'};await store.save('tenant','actor',c,0,'connection.saved');assert.equal((await store.config('tenant')).secret,c.secret);assert.doesNotMatch(JSON.stringify((await db.query('SELECT * FROM rmm_connections')).rows),/PRIVATE/);await store.save('tenant','actor',{...c,version:2},1,'connection.saved');await assert.rejects(()=>store.save('tenant','actor',{...c,version:2},1,'connection.saved'));assert.equal((await store.events('tenant')).length,2);const j={id:'00000000-0000-4000-8000-000000000001',actor:'actor',requestKey:'request-1',hash:'abc',connectionVersion:2,accountUid:'account-a',deviceUid:'d',siteUid:'s',companyId:10,componentUid:'c',state:'reserved' as const,createdAt:new Date().toISOString()};assert.equal((await store.reserve('tenant',j)).created,true);assert.equal((await store.reserve('tenant',j)).created,false);assert.equal((await store.jobs('other','actor')).length,0);assert.equal((await store.jobs('tenant','actor'))[0]?.id,j.id);}finally{await db.close();}});
test('transport uses pinned host, OAuth form and cached tokens; blocks redirects and throttling',async()=>{let requests:Request[]=[],now=1000;const client=new RmmClient(async(url,init)=>{const r=new Request(url,init);requests.push(r);return r.url.includes('/auth/')?Response.json({access_token:'token',expires_in:3600}):Response.json({uid:'account-a'});},()=>now);const c={...emptyConfig(),version:1,key:'key',secret:'secret'};await client.request(c,'/v2/account');await client.request(c,'/v2/account');assert.equal(requests.length,3);assert.equal(requests[0]!.url,'https://zinfandel-api.centrastage.net/auth/oauth/token');assert.match(await requests[0]!.text(),/grant_type=password/);assert.equal(requests[1]!.redirect,'error');await assert.rejects(()=>client.request({...c,platform:'evil.invalid'},'/v2/account'));const throttled=new RmmClient(async url=>String(url).includes('/auth/')?Response.json({access_token:'token'}):new Response('',{status:429}),()=>now);await assert.rejects(()=>throttled.request(c,'/v2/account'));await assert.rejects(()=>throttled.request(c,'/v2/account'));assert.equal(Object.keys(schemas).length,55);});
test('console RMM routes enforce administrator access and CSRF; runtime honors capabilities and write pause',async t=>{
 const {createFixtureSystem}=await import('../apps/server/src/fixture-system.js');const s=createFixtureSystem();t.after(()=>s.app.close());const base='http://127.0.0.1:3030';
 const login=async(i:number)=>{const r=await s.app.fetch(new Request(base+'/admin/auth/fixture',{method:'POST',headers:{origin:base,'content-type':'application/json'},body:JSON.stringify({token:s.tokens[i]!.token})}));return{cookie:r.headers.getSetCookie()[0]!.split(';')[0]!,csrf:(await r.json()).csrf};};
 const admin=await login(0),peer=await login(1);const request=(path:string,session=admin,body?:unknown,csrf=true)=>s.app.fetch(new Request(base+'/admin/api/rmm/'+path,{method:body?'POST':'GET',headers:{cookie:session.cookie,origin:base,'content-type':'application/json',...(csrf?{'x-csrf-token':session.csrf}:{})},...(body?{body:JSON.stringify(body)}:{})}));
 assert.equal((await request('status',peer)).status,403);assert.equal((await request('connection',admin,{},false)).status,403);
 const config=await request('connection',admin,{version:0,platform:'zinfandel',key:'FIXTURE_KEY',secret:'FIXTURE_SECRET',enabled:false,jobs_enabled:false});assert.equal(config.status,200);assert.doesNotMatch(await config.text(),/FIXTURE_KEY|FIXTURE_SECRET/);
 assert.equal((await request('test',admin,{})).status,200);assert.equal((await request('connection',admin,{version:2,platform:'zinfandel',enabled:true,jobs_enabled:true})).status,200);assert.equal((await request('mapping',admin,{version:3,site_uid:'example-site',enabled:true})).status,200);assert.equal((await request('approval',admin,{version:4,component_uid:'example-diagnostics',approved:true,variables:{}})).status,200);
 const old=s.principals[0]!,p={...old,capabilities:[...old.capabilities,'rmm.read' as const,'rmm.execute' as const],mappingVersion:old.mappingVersion+1};await s.controlStore.saveMember(old,p,old.mappingVersion,new Date().toISOString());
 const available=await s.runtime.available(p);assert(available.some(v=>v.name==='rmm_device_get'));assert.equal((await s.runtime.invoke(p,'rmm_device_get',{device_uid:'example-device'}) as Row).data.hostname,'EXAMPLE-PC');
 const controls=await s.controlStore.getControls(p.tenantId);await s.controlStore.saveControls(p,{...controls,version:controls.version+1,writePaused:true},controls.version,new Date().toISOString());assert(!(await s.runtime.available(p)).some(v=>v.name==='rmm_quickjob_run'));await assert.rejects(()=>s.runtime.invoke(p,'rmm_quickjob_run',{device_uid:'example-device',component_uid:'example-diagnostics',job_name:'Demo',request_key:'console-test-1'}));
});
test('approved fixed variables cannot be overridden through MCP input',async()=>{const s=await enabled();s.port.component.variables=[{name:'Command',type:'string'}] as any;await s.service.approve(s.p,{version:5,component_uid:'component-a',approved:true,variables:{Command:'reviewed'}});await assert.rejects(()=>s.service.run(s.p,'rmm_quickjob_run',{device_uid:'device-a',component_uid:'component-a',job_name:'Diagnostics',request_key:'request-fixed',variables:{Command:'arbitrary'}}));assert.equal(s.port.dispatches,0);await s.service.approve(s.p,{version:6,component_uid:'component-a',approved:false});await assert.rejects(()=>s.service.run(s.p,'rmm_quickjob_run',{device_uid:'device-a',component_uid:'component-a',job_name:'Diagnostics',request_key:'request-fixed'}));});
test('connection replacement prevents old job receipts crossing account boundaries',async()=>{const s=await enabled();await s.service.run(s.p,'rmm_quickjob_run',{device_uid:'device-a',component_uid:'component-a',job_name:'Diagnostics',request_key:'receipt-test'});const c=await s.store.config(s.p.tenantId);await s.store.save(s.p.tenantId,actorKey(s.p),{...c,version:c.version+1,accountUid:'different-account'},c.version,'connection.saved');assert.deepEqual((await s.service.run(s.p,'rmm_job_list',{})).data,[]);});

test('all first-release read tools use their reviewed routes and valid envelopes',async()=>{const s=await enabled();for(const [name,args] of Object.entries({rmm_site_list:{},rmm_device_search:{site_uid:'site-a'},rmm_device_get:{device_uid:'device-a'},rmm_device_audit_get:{device_uid:'device-a'},rmm_device_software_list:{device_uid:'device-a'},rmm_device_patch_list:{device_uid:'device-a'},rmm_site_patch_list:{site_uid:'site-a'},rmm_device_alert_list:{device_uid:'device-a'},rmm_site_alert_list:{site_uid:'site-a'},rmm_alert_get:{alert_uid:'alert-a'},rmm_site_network_list:{site_uid:'site-a'},rmm_site_filter_list:{site_uid:'site-a'},rmm_component_list:{},rmm_job_list:{}})){const result=await s.service.run(s.p,name as keyof typeof schemas,args);assert(rmmOutput.safeParse(result).success,name);assert.equal(result.status,'succeeded',name);}const job=await s.service.run(s.p,'rmm_quickjob_run',{device_uid:'device-a',component_uid:'component-a',job_name:'Diagnostics',request_key:'all-read-test'});assert.equal((await s.service.run(s.p,'rmm_job_get',{operation_id:job.data.operation_id})).data.uid,'job-a');});
test('administrator permission revoked after page load cannot change RMM settings',async()=>{const s=await enabled();s.state.principal={...s.p,capabilities:['operational.read','rmm.read']};await assert.rejects(()=>s.service.configure(s.p,{version:5,platform:'zinfandel',enabled:false,jobs_enabled:false}));assert.equal((await s.store.config(s.p.tenantId)).enabled,true);});

test('device search crosses only authorized sites and continues after empty filtered pages',async()=>{
 const s=await enabled();await s.service.mapSite(s.p,{version:5,site_uid:'site-b',enabled:true});
 const c=await s.store.config(s.p.tenantId);await s.store.save(s.p.tenantId,actorKey(s.p),{...c,version:c.version+1,sites:{...c.sites,foreign:{companyId:999,name:'Foreign'}}},c.version,'mapping.saved');
 const original=s.port.request.bind(s.port),requests:{path:string,page:number}[]=[];
 s.port.request=async(config,path,q={},...rest)=>{
  if(path.endsWith('/devices')){requests.push({path,page:q.page});const siteUid=path.split('/')[3];return{devices:[{uid:`${siteUid}-${q.page}`,siteUid,hostname:'LAPTOP',lastLoggedInUser:siteUid==='site-b'?'ACME\\Jane.Doe':'Someone Else',online:false}],pageDetails:{nextPageUrl:siteUid==='site-a'&&q.page===0?'https://untrusted.invalid':null}};}
  return original(config,path,q,...rest);
 };
 const args={last_logged_in_user:'JANE',online:false,page_size:1};
 const first=await s.service.run(s.p,'rmm_device_search',args);assert.deepEqual(first.data.devices,[]);assert.equal(first.status,'partial');
 const second=await s.service.run(s.p,'rmm_device_search',{...args,cursor:first.completeness.next_cursor});assert.deepEqual(second.data.devices,[]);assert.equal(second.status,'partial');
 const third=await s.service.run(s.p,'rmm_device_search',{...args,cursor:second.completeness.next_cursor});assert.equal(third.data.devices[0].lastLoggedInUser,'ACME\\Jane.Doe');assert.equal(third.completeness.complete,true);
 assert.deepEqual(requests.map(r=>[r.path,r.page]),[['/v2/site/site-a/devices',0],['/v2/site/site-a/devices',1],['/v2/site/site-b/devices',0]]);
 await assert.rejects(()=>s.service.run(s.p,'rmm_device_search',{...args,last_logged_in_user:'other',cursor:first.completeness.next_cursor}));
 await assert.rejects(()=>s.service.run(s.p,'rmm_device_search',{site_uid:'foreign'}));
 s.state.principal={...s.p,companyIds:[]};await assert.rejects(()=>s.service.run(s.p,'rmm_device_search',{...args,cursor:first.completeness.next_cursor}));
 assert.deepEqual((await s.service.run(s.state.principal,'rmm_device_search',args)).data.devices,[]);
});

test('device search general query uses projected fields and typed filters together',async()=>{
 const s=await enabled(),original=s.port.request.bind(s.port);
 s.port.request=async(c,path,q={},...rest)=>path.endsWith('/devices')?{devices:[{uid:'device-a',siteUid:'site-a',hostname:'PC-01',lastLoggedInUser:'DOMAIN\\Alex',intIpAddress:'10.0.0.10',online:false,antivirus:{antivirusProduct:'Defender'},patchManagement:{patchesInstalled:0},unknownSecret:'hidden-value'}],pageDetails:{nextPageUrl:null}}:original(c,path,q,...rest);
 assert.equal((await s.service.run(s.p,'rmm_device_search',{query:'alex',internal_ip_address:'10.0.0.10',antivirus_product:'defend',patches_installed:0,online:false})).data.devices.length,1);
 assert.equal((await s.service.run(s.p,'rmm_device_search',{query:'hidden-value'})).data.devices.length,0);
 assert.equal((await s.service.run(s.p,'rmm_device_search',{internal_ip_address:'10.0.0.1'})).data.devices.length,0);
 assert.equal((await s.service.run(s.p,'rmm_device_search',{last_logged_in_user:'alex',online:true})).data.devices.length,0);
});
