import {AppError,type Principal} from '../../../packages/contracts/src/index.js';
import {currentExecution,type ExecutionContext} from '../../../packages/execution/src/index.js';
import {summarizeArguments,summarizeResult,sanitizeError} from '../../../packages/diagnostics/src/sanitize.js';
import type {DiagnosticOutcome} from '../../../packages/diagnostics/src/contracts.js';
import type {DurableDiagnostics} from '../../../packages/diagnostics/src/service.js';
import {SERVER_RELEASE,toolFileMetadata} from './publication.js';
import {OutputContractError} from './output-validation.js';
export const diagnosticToolName=(name:unknown)=>typeof name==='string'&&/^[a-z][a-z0-9_]{0,99}$/.test(name)?name:'invalid_tool_name';
const uuid=(v:unknown)=>typeof v==='string'&&/^[0-9a-f-]{36}$/i.test(v)?v:undefined;
function businessValue(value:any){return value?.operation&&value?.result?value.result:value;}
function outcome(raw:any,error:unknown):DiagnosticOutcome{const value=businessValue(raw);if(['unknown_outcome','dispatching','reserved','uncertain'].includes(value?.status))return'unknown_outcome';if(['accepted_unverified','accepted'].includes(value?.status))return'accepted_unverified';if(value?.status==='partial'||value?.completeness?.complete===false)return'partial';if(error)return error instanceof AppError&&['invalid_input','forbidden','unsupported_operation','not_found_or_inaccessible'].includes(error.code)?'rejected':'failed';if(value?.error||value?.isError||value?.status==='failed'||value?.status==='output_contract_error')return'failed';return'succeeded';}
function byteSize(value:unknown){try{return Buffer.byteLength(JSON.stringify(value)??'');}catch{return undefined;}}
function recordReference(input:any){const value=input?.ticket_id??input?.ticket?.id??input?.ticket?.number??input?.ticket;return typeof value==='number'&&Number.isSafeInteger(value)&&value>=0?String(value):typeof value==='string'&&/^T[0-9]{8}\.[0-9]{4,10}$/.test(value)?value:undefined;}

export async function beginDiagnostic(diagnostics:DurableDiagnostics,context:ExecutionContext,principal:Principal,tool:unknown,input:unknown,options:{source?:string;parentId?:string;metadataDigest?:string;jobId?:string}={}){
 const name=diagnosticToolName(tool),inner=name==='at_invoke'||name==='at_read_invoke'?diagnosticToolName((input as any)?.operation):undefined;
 const start=await diagnostics.start({traceId:context.traceId,tenantId:principal.tenantId,actorId:principal.objectId,resourceId:principal.resourceId,recordId:recordReference(input),tool:name,requestedTool:inner,source:options.source??'mcp',parentId:options.parentId,serverRelease:SERVER_RELEASE,metadataDigest:options.metadataDigest,jobId:options.jobId,details:{request_bytes:byteSize(input),arguments:summarizeArguments(name,input),...(name==='at_file_stage'||name==='opportunity_file_stage'?{published_contract:{file_params:toolFileMetadata(name)?.['openai/fileParams']??[],file_properties:['file_id','download_url','file_name','mime_type'],required_file_properties:['file_id','download_url']}}:{})}});
 let finished=false;const started=performance.now();context.diagnosticCallId=start.callId;
 context.diagnosticFailure=()=>diagnostics.markFailure();
 context.diagnosticEvidence=async(type,details)=>{await diagnostics.record({spanId:currentExecution()?.spanId??context.spanId,traceId:context.traceId,callId:currentExecution()?.diagnosticCallId??start.callId,tenantId:principal.tenantId,actorId:principal.objectId,type,details});};
 const complete=async(result?:unknown,error?:unknown)=>{if(finished)return;finished=true;const value=businessValue(result),safe=error?sanitizeError(error):value?.error?.code?sanitizeError(new AppError(value.error.code,'Omitted.')):undefined;try{await diagnostics.finish(start,{outcome:outcome(value,error),durationMs:performance.now()-started,errorOrigin:error instanceof OutputContractError?'output_validation':safe?.origin as string|undefined,errorCode:safe?.code as string|undefined,operationId:uuid(value?.operation_id),jobId:options.jobId??uuid(value?.job_id)??uuid(value?.report_id),recordId:typeof value?.data?.ticket_id==='number'?String(value.data.ticket_id):start.call?.recordId,details:{response_bytes:byteSize(result),result:summarizeResult(value),...(safe?{error:safe}:{}),...(error instanceof OutputContractError?{safe_to_redispatch:false}:{}),effect_dispatched:context.effectStarted}});}catch{diagnostics.markFailure();}};
 context.completeDiagnostic=complete;return{start,complete,get finished(){return finished;}};
}
/** Consume complete SSE frames before forwarding them so rejected pre-handler calls are durably finished. */
export function observeDiagnosticResponse(response:Response,complete:(result?:unknown,error?:unknown)=>Promise<void>):Response{
 if(!response.body)return response;const sse=response.headers.get('content-type')?.includes('text/event-stream'),decoder=new TextDecoder(),encoder=new TextEncoder();let buffer='';
 const process=async(raw:string)=>{try{const payload=sse?raw.split('\n').filter(l=>l.startsWith('data:')).map(l=>l.slice(5).trimStart()).join('\n'):raw;if(!payload)return;const rpc=JSON.parse(payload);if(rpc.error){const code=rpc.error.code===-32602?'invalid_input':rpc.error.code===-32601?'unsupported_operation':'dependency_unavailable';await complete(undefined,new AppError(code,'Protocol rejected the tool call.'));}else if(rpc.result){if(rpc.result.isError&&!rpc.result.structuredContent)await complete(undefined,new AppError('invalid_input','SDK rejected the tool arguments before dispatch.'));else await complete(rpc.result.structuredContent??rpc.result);}}catch{/* Malformed transport response is recorded at finalization, never copied to diagnostics. */}};
 const stream=response.body.pipeThrough(new TransformStream<Uint8Array,Uint8Array>({async transform(chunk,c){buffer+=decoder.decode(chunk,{stream:true});if(Buffer.byteLength(buffer)>4*1024*1024)throw new AppError('dependency_unavailable','Diagnostic response observer exceeded the stream bound.');if(sse){let index;while((index=buffer.search(/\r?\n\r?\n/))>=0){const size=buffer[index]==='\r'?4:2;const frame=buffer.slice(0,index+size);buffer=buffer.slice(index+size);await process(frame);c.enqueue(encoder.encode(frame));}}},async flush(c){buffer+=decoder.decode();if(buffer){await process(buffer);c.enqueue(encoder.encode(buffer));buffer='';}}}));
 const headers=new Headers(response.headers);headers.delete('content-length');return new Response(stream,{status:response.status,statusText:response.statusText,headers});
}
