import type {DurableDiagnostics} from '../../../packages/diagnostics/src/service.js';
import {CompanySelection} from '../../../packages/read-selection/src/index.js';
import {ReadSelectionContinuation,MemorySelectionReplayStore} from '../../../packages/durable-read-jobs/src/interactive.js';
import {MemoryReadJobStore} from '../../../packages/durable-read-jobs/src/store.js';
import {createReadReports} from './read-reports.js';
import {ItGlueService} from '../../../packages/itglue/src/service.js';
import {FixtureItGluePort} from '../../../packages/itglue/src/fixtures.js';
import {MemoryItGlueStore} from '../../../packages/itglue/src/store.js';
import {AutotaskConfiguration} from '../../../packages/autotask-config/src/service.js';
import {MemoryStore as MemoryAutotaskConfigStore} from '../../../packages/autotask-config/src/store.js';
import {MemoryHandoff} from '../../../packages/autotask-config/src/handoff.js';
import {fromEnvironment} from '../../../packages/autotask-config/src/model.js';
import {RmmService} from '../../../packages/rmm/src/service.js';
import {MemoryRmmStore} from '../../../packages/rmm/src/store.js';
import {FixtureRmmPort} from '../../../packages/rmm/src/fixtures.js';
import { randomBytes, timingSafeEqual } from 'node:crypto';
import { AppError, actorKey, type PrincipalStore } from '../../../packages/contracts/src/index.js';
import { reauthorize } from '../../../packages/policy/src/index.js';
import { IntentCipher, MemoryJournal } from '../../../packages/storage/src/index.js';
import { FixtureAutotaskAdapter, fixturePrincipals } from '../../../packages/workflows/src/fixtures.js';
import { TicketWorkflows } from '../../../packages/workflows/src/index.js';
import { TicketWriteWorkflows } from '../../../packages/workflows/src/write-workflows.js';
import { TechnicianWorkflows } from '../../../packages/workflows/src/technician-workflows.js';
import { TechnicianDomain } from '../../../packages/technician/src/index.js';
import { FixtureTechnicianPort } from '../../../packages/technician/src/fixtures.js';
import { SchedulingWorkflows } from '../../../packages/scheduling/src/index.js';
import { FixtureSchedulingPort } from '../../../packages/scheduling/src/fixtures.js';
import { PlaybookService } from '../../../packages/playbooks/src/index.js';
import { ControlPlaneService } from '../../../packages/control-plane/src/index.js';
import { MemoryControlPlaneStore } from '../../../packages/control-plane/src/memory.js';
import { ExecutionControls } from '../../../packages/control-plane/src/execution.js';
import { AdminSessions } from '../../../packages/identity/src/admin-session.js';
import { ToolRuntime, operationCatalog } from './tool-runtime.js';
import { createAdminRoutes } from './admin.js';
import { createApplication } from './app.js';
import { JobWorker } from './job-worker.js';
import { ArtifactService } from '../../../packages/artifacts/src/index.js';

export function createFixtureSystem(publicUrl='http://127.0.0.1:3030',options:{diagnostics?:DurableDiagnostics}={}){
  const principals=fixturePrincipals(),journal=new MemoryJournal(),cipher=new IntentCipher(randomBytes(32));
  const controlStore=new MemoryControlPlaneStore(principals,journal,async()=>journal.inspectAll());
  const control=new ControlPlaneService(controlStore,{bootstrapIdentityKeys:[actorKey(principals[0]!)],cipher,operations:operationCatalog,verifyResource:async(tenant,id)=>principals.some(p=>p.tenantId===tenant&&p.resourceId===id),safeConfig:{mode:'fixture',liveQualified:false,databaseConfigured:false,intentKeyConfigured:true}});
  const execution=new ExecutionControls(control),baseStore:PrincipalStore={get:(tenantId,objectId)=>controlStore.getMember({tenantId,objectId})},store=execution.principalStore(baseStore);
  if(options.diagnostics)options.diagnostics.options.principals=baseStore;
  const check=async(p:typeof principals[number])=>reauthorize(p,store);
  const adapter=new FixtureAutotaskAdapter(check),core=new TicketWorkflows(adapter,store,journal),writes=new TicketWriteWorkflows(core,cipher);
  const technicianPort=new FixtureTechnicianPort(adapter,store),domain=new TechnicianDomain(technicianPort,store,{ticketHosts:['ww1.autotask.net']}),schedulingPort=new FixtureSchedulingPort(adapter,store),scheduling=new SchedulingWorkflows(core,schedulingPort,cipher);
  const artifacts=new ArtifactService(core,{projectRoot:process.cwd(),encryptionKey:randomBytes(32)});
  const itglue=new ItGlueService(new MemoryItGlueStore(),new FixtureItGluePort(),store,cipher);
  itglue.artifacts=artifacts;
  const rmm=new RmmService(new MemoryRmmStore(),new FixtureRmmPort(),store,cipher,async p=>{await control.snapshot(p);});
  const selection=new CompanySelection(new ReadSelectionContinuation(cipher,new MemorySelectionReplayStore()),baseStore,(p,name,args)=>runtime.invoke(p,name,args),{mrtrEnabled:false});
  const {reports,readWorker}=createReadReports(new MemoryReadJobStore(),cipher,baseStore,()=>runtime);
  const technician=new TechnicianWorkflows(core,writes,domain,scheduling,cipher),playbooks=new PlaybookService(store),runtime=new ToolRuntime({diagnostics:options.diagnostics,selection,reports,discoveryCipher:cipher,itglue,rmm,core,writes,technician,scheduling,playbooks,control,execution,artifacts});
  const tokens=principals.map((principal,i)=>({name:i===0?'Example technician (company 10, ticket work)':'Sample reader (company 20)',token:randomBytes(32).toString('base64url'),principal}));
  const authenticate=async(token:string)=>{const supplied=Buffer.from(token),match=tokens.find(t=>{const expected=Buffer.from(t.token);return supplied.length===expected.length&&timingSafeEqual(supplied,expected);});if(!match)throw new AppError('unauthenticated','Invalid fixture token.');const current=await baseStore.get(match.principal.tenantId,match.principal.objectId);if(!current)throw new AppError('identity_mapping_invalid','Fixture employee unavailable.');return check(current);};
  const sessions=new AdminSessions({publicUrl,fixtureAuthenticate:authenticate});
  const configurationHandoff=new MemoryHandoff();
  const autotaskConfiguration=new AutotaskConfiguration(new MemoryAutotaskConfigStore(),principals[0]!.tenantId,{id:'fixture-current',createdAt:new Date().toISOString(),config:fromEnvironment({AUTOTASK_BASE_URL:'https://webservices1.autotask.net/atservicesrest/v1.0/',AUTOTASK_USERNAME:'fixture@example.test',AUTOTASK_SECRET:'fixture-secret',AUTOTASK_INTEGRATION_CODE:'fixture-code'})},{authorize:async actor=>{await control.snapshot(actor);},handoff:configurationHandoff,reloadAvailable:false});
  const admin=createAdminRoutes({autotaskConfiguration,publicUrl,sessions,control,operations:operationCatalog,runtime,principal:async actor=>{const p=await baseStore.get(actor.tenantId,actor.objectId);if(!p)throw new AppError('identity_mapping_invalid','Employee mapping unavailable.');return check(p);},recover:(p,action,id)=>execution.run(p,[action==='resume'?'at_operation_resume':'at_operation_reconcile'],()=>runtime.recover(p,action,id))});
  const app=createApplication({diagnostics:options.diagnostics,publicUrl,authenticate,workflows:core,writes,runtime,admin});
  const worker=new JobWorker(runtime,Date.now,readWorker);
  return{app,worker,runtime,autotaskConfiguration,control,controlStore,execution,principals,store,journal,adapter,core,writes,domain,technician,technicianPort,scheduling,schedulingPort,tokens,authenticate,sessions,artifacts};
}
