import {withReconciliation} from '../../execution/src/index.js';
import type {ArtifactService} from '../../artifacts/src/index.js';
import {createDocumentImage} from './media.js';
import {readSupplement,type SupplementTool} from './related.js';
import {createHash,randomUUID} from 'node:crypto';
import {z} from 'zod';
import {AppError,actorKey,type Principal,type PrincipalStore} from '../../contracts/src/index.js';
import {reauthorize,assertCapability,assertCompanyScope} from '../../policy/src/index.js';
import {IntentCipher} from '../../storage/src/intent-cipher.js';
import {schemas,id,isWrite,type ItGlueTool} from './contracts.js';
import type {ItGluePort} from './client.js';
import {project,plain} from './projection.js';
import {emptyConfig,type ItGlueConfig,type ItGlueStore,type ItGlueReceipt,type Row} from './store.js';
const canonical=(v:any):string=>Array.isArray(v)?'['+v.map(canonical).join(',')+']':v&&typeof v==='object'?'{'+Object.keys(v).sort().map(k=>JSON.stringify(k)+':'+canonical(v[k])).join(',')+'}':JSON.stringify(v);
const hash=(v:any)=>createHash('sha256').update(canonical(v)).digest('hex');
const bad=()=>new AppError('not_found_or_inaccessible','IT Glue record is unmapped or outside your company scope.');
const entity:Record<string,string>={organization:'organizations',configuration:'configurations',contact:'contacts',flexible_asset:'flexible_assets',document:'documents',checklist:'checklists'};
export class ItGlueService {
 private companyDiscoveryCache=new Map<string,{expires:number;result:{version:number;items:Array<{id:string;name:string;companyId:number}>;next_offset:number|null}}>();
 artifacts?:ArtifactService;
 constructor(readonly store:ItGlueStore,readonly port:ItGluePort,readonly principals:PrincipalStore,readonly cipher:IntentCipher){}
 async enabled(t:string){const c=await this.store.config(t);return{reads:c.enabled&&!!c.key,writes:c.enabled&&c.writesEnabled};}
 async administrator(p:Principal){assertCapability(await reauthorize(p,this.principals),'platform.manage');}
 async discoverOrganizations(p:Principal,input:unknown){
  const a=z.object({offset:z.number().int().nonnegative().default(0)}).strict().parse(input);
  await this.administrator(p);const c=await this.store.config(p.tenantId);
  if(!c.key)throw new AppError('precondition_failed','Save IT Glue credentials before loading companies.');
  const companies=[...new Set(p.companyIds)].sort((a,b)=>a-b),items:Array<{id:string;name:string;companyId:number}>=[];
  const guard=async()=>{await this.administrator(p);if((await this.store.config(p.tenantId)).version!==c.version)throw new AppError('conflict','IT Glue connection changed. Reload companies.');};
  const cacheKey=hash({actor:actorKey(p),region:c.region,key:c.key,companies,offset:a.offset});
  const cached=this.companyDiscoveryCache.get(cacheKey);if(cached&&cached.expires>Date.now()){await guard();return{...structuredClone(cached.result),version:c.version};}
  for(const company of companies.slice(a.offset,a.offset+10)){
   for(let page=1;page<=20;page++){
    await guard();assertCompanyScope(await reauthorize(p,this.principals),company);
    const r=await this.port.request(c,'/organizations',{'filter[psa_id]':String(company),'filter[psa_integration_type]':'autotask','page[size]':100,'page[number]':page},undefined,guard);
    const pages=r.meta?.['total-pages'];
    if(!Array.isArray(r.data)||r.data.length>100||!Number.isInteger(pages)||pages<0||pages>20)throw new AppError('dependency_unavailable','IT Glue company listing is incomplete.');
    for(const row of r.data){if(row.type!=='organizations'||!id.safeParse(String(row.id)).success||typeof row.attributes?.name!=='string')throw new AppError('dependency_unavailable','IT Glue returned an invalid organization.');items.push({id:String(row.id),name:row.attributes.name,companyId:company});}
    if(page>=pages)break;
   }
  }
  await guard();for(const item of items)assertCompanyScope(await reauthorize(p,this.principals),item.companyId);
  const result={version:c.version,items,next_offset:a.offset+10<companies.length?a.offset+10:null};
  if(this.companyDiscoveryCache.size>=100)this.companyDiscoveryCache.delete(this.companyDiscoveryCache.keys().next().value!);
  this.companyDiscoveryCache.set(cacheKey,{expires:Date.now()+60000,result:structuredClone(result)});return result;
 }
 async status(p:Principal){await this.administrator(p);const c=await this.store.config(p.tenantId);return{version:c.version,region:c.region,configured:!!c.key,enabled:c.enabled,writes_enabled:c.writesEnabled,organizations:c.organizations};}
 async configure(p:Principal,input:unknown){await this.administrator(p);const a=z.object({version:z.number().int().nonnegative(),region:z.enum(['us','eu','au']),key:z.string().min(1).max(4096).optional(),enabled:z.boolean(),writes_enabled:z.boolean()}).strict().parse(input),old=await this.store.config(p.tenantId),changed=a.key!==undefined||old.region!==a.region;if(changed&&a.enabled)throw new AppError('precondition_failed','Save changed credentials disabled, then verify organization mappings.');if(a.writes_enabled&&!a.enabled)throw new AppError('invalid_input','Enable reads before writes.');const c={...old,version:a.version+1,region:a.region,key:a.key??old.key,enabled:a.enabled,writesEnabled:a.writes_enabled,...(changed?{organizations:{}}:{})};if(c.enabled&&(!c.key||!Object.keys(c.organizations).length))throw new AppError('precondition_failed','Verify an organization mapping before enabling IT Glue.');await this.administrator(p);await this.store.save(p.tenantId,c,a.version);return this.status(p);}
 async disconnect(p:Principal,input:unknown){await this.administrator(p);const a=z.object({version:z.number().int().nonnegative()}).strict().parse(input);await this.store.save(p.tenantId,{...emptyConfig(),version:a.version+1},a.version);return this.status(p);}
 async mapOrganization(p:Principal,input:unknown){await this.administrator(p);const a=z.object({version:z.number().int().nonnegative(),organization_id:id,company:z.number().int().nonnegative(),enabled:z.boolean()}).strict().parse(input),c=await this.store.config(p.tenantId);assertCompanyScope(await reauthorize(p,this.principals),a.company);if(a.enabled){const r=await this.port.request(c,'/organizations',{'filter[id]':a.organization_id,'filter[psa_id]':String(a.company),'filter[psa_integration_type]':'autotask','page[size]':2},undefined,()=>this.administrator(p));if(!Array.isArray(r.data)||r.data.length!==1||String(r.data[0]?.id)!==a.organization_id||r.data[0]?.type!=='organizations')throw new AppError('precondition_failed','Organization must have the matching native Autotask company association.');c.organizations[a.organization_id]={companyId:a.company,verifiedAt:new Date().toISOString(),evidence:'native-autotask-association'};}else delete c.organizations[a.organization_id];await this.administrator(p);await this.store.save(p.tenantId,{...c,version:a.version+1},a.version);return this.status(p);}
 async guard(p:Principal,c:ItGlueConfig,company:number,write=false){const fresh=await reauthorize(p,this.principals);assertCapability(fresh,'documentation.read');if(write)assertCapability(fresh,'documentation.write');assertCompanyScope(fresh,company);const now=await this.store.config(p.tenantId);if(now.version!==c.version)throw new AppError('conflict','IT Glue connection or mapping changed.');if(!now.enabled||(write&&!now.writesEnabled))throw new AppError('forbidden','IT Glue operation is disabled.');}
 private async call(p:Principal,c:ItGlueConfig,company:number,path:string,q:Row={}){await this.guard(p,c,company);const r=await this.port.request(c,path,q,undefined,()=>this.guard(p,c,company));await this.guard(p,c,company);return r;}
 private async organization(p:Principal,c:ItGlueConfig,company:number,org:string){if(c.organizations[org]?.companyId!==company)throw bad();const matches=(await this.call(p,c,company,'/organizations',{'filter[id]':org,'filter[psa_id]':String(company),'filter[psa_integration_type]':'autotask','page[size]':2})).data;if(!Array.isArray(matches)||matches.length!==1||String(matches[0]?.id)!==org||matches[0]?.type!=='organizations')throw bad();const r=(await this.call(p,c,company,`/organizations/${org}`)).data;if(String(r?.id)!==org||r?.type!=='organizations')throw bad();return r;}
 private async record(p:Principal,c:ItGlueConfig,company:number,org:string,path:string,recordId:string){const r=(await this.call(p,c,company,path)).data;if(!r||String(r.id)!==recordId||r.type!==path.split('/')[1]!.replaceAll('_','-')||String(r.attributes?.['organization-id'])!==org)throw bad();return r;}
 private envelope(company:number,org:string,data:any,next:string|null=null,filters:Row={},limitations:string[]=[]){return{status:next?'partial':'succeeded',data,scope:{company_id:company,organization_id:org},applied_filters:filters,completeness:{complete:!next,next_cursor:next},provenance:{source:'IT Glue' as const,fetched_at:new Date().toISOString()},limitations};}
 private binding(p:Principal,c:ItGlueConfig,name:string,a:Row){const {cursor,...rest}=a;return hash({actor:actorKey(p),mapping:p.mappingVersion,policy:p.policyVersion,version:c.version,name,args:rest});}
 private page(p:Principal,c:ItGlueConfig,name:string,a:Row){if(!a.cursor)return 1;const v=this.cipher.open(a.cursor,`itg:cursor:${actorKey(p)}`) as Row;if(v.binding!==this.binding(p,c,name,a)||v.expires<Date.now()||!Number.isInteger(v.page)||v.page<1||v.page>1000)throw new AppError('conflict','IT Glue cursor expired or scope changed.');return v.page;}
 private next(p:Principal,c:ItGlueConfig,name:string,a:Row,page:number,raw:Row){if(!raw.meta||!Number.isInteger(raw.meta['total-pages'])||raw.meta['total-pages']<0)throw new AppError('dependency_unavailable','IT Glue pagination metadata is missing.');if(page>=raw.meta['total-pages'])return null;if(page>=1000)throw new AppError('dependency_unavailable','IT Glue pagination bound reached.');return this.cipher.seal({binding:this.binding(p,c,name,a),page:page+1,expires:Date.now()+900000},`itg:cursor:${actorKey(p)}`);}
 async run(p:Principal,name:ItGlueTool,input:unknown):Promise<any>{const a=schemas[name].parse(input) as Row,c=await this.store.config(p.tenantId);await this.guard(p,c,a.company,isWrite(name));const matches=Object.keys(c.organizations).filter(k=>c.organizations[k]!.companyId===a.company),org=a.organization_id??(matches.length===1?matches[0]:undefined);if(!org)throw new AppError('precondition_failed','Select an explicitly mapped organization.');await this.organization(p,c,a.company,org);
  let result:any;
  if(name==='itg_operation_get'){const r=await this.store.get(p.tenantId,actorKey(p),a.operation_id);if(!r||r.companyId!==a.company||r.organizationId!==org||r.connectionVersion!==c.version)throw bad();result=this.receipt(a.company,org,r);}
  else if(name==='itg_document_image_create'){if(!this.artifacts)throw new AppError('precondition_failed','Artifact storage is unavailable.');const receipt=await createDocumentImage({store:this.store,port:this.port,artifacts:this.artifacts,config:c,organizationId:org,guard:async()=>{await this.guard(p,c,a.company,true);await this.organization(p,c,a.company,org);await this.record(p,c,a.company,org,`/documents/${a.document_id}`,a.document_id);}},p,a);result=this.receipt(a.company,org,receipt);}
  else if(isWrite(name))result=await this.write(p,c,name,a,org);
  else result=await this.read(p,c,name,a,org);
  const finalScope=async()=>{await this.organization(p,c,a.company,org);await this.guard(p,c,a.company,isWrite(name));};if(isWrite(name))await withReconciliation(finalScope);else await finalScope();const serialized=JSON.stringify(result);if(Buffer.byteLength(serialized)>512000)throw new AppError('dependency_unavailable','IT Glue output exceeds limit. Use smaller pages.');return JSON.parse(serialized.split(c.key).join('[redacted]'));
 }
 private async read(p:Principal,c:ItGlueConfig,name:ItGlueTool,a:Row,org:string){const key=name.slice(4).replace(/_(search|get)$/,''),kind=entity[key],page=this.page(p,c,name,a),q:Row={'page[number]':page,'page[size]':a.page_size??50};let raw:Row,path:string;
  if(['itg_related_items_get','itg_expiration_search','itg_reference_search'].includes(name)){const result=await readSupplement(name as SupplementTool,a,org,page,(path,q)=>this.call(p,c,a.company,path,q));const response=this.envelope(a.company,org,result.data,this.next(p,c,name,a,page,result.raw),{},result.limitations);if(!result.complete){response.status='partial';response.completeness.complete=false;}return response;}
  if(name==='itg_organization_get'){if(a.id!==org)throw bad();return this.envelope(a.company,org,project(await this.organization(p,c,a.company,org)));}
  if(name==='itg_organization_search'){const r=await this.organization(p,c,a.company,org);return this.envelope(a.company,org,!a.filters.name||r.attributes?.name===a.filters.name?[project(r)]:[],null,a.filters);}
  if(name==='itg_document_get'){const doc=await this.record(p,c,a.company,org,`/documents/${a.document_id}`,a.document_id);raw=await this.call(p,c,a.company,`/documents/${a.document_id}/relationships/sections`,q);if(!Array.isArray(raw.data)||raw.data.length>(a.page_size??50)||raw.data.some((r:Row)=>r.type!=='document-sections'||(r.attributes?.['document-id']!==undefined&&String(r.attributes['document-id'])!==a.document_id)))throw bad();await this.record(p,c,a.company,org,`/documents/${a.document_id}`,a.document_id);return this.envelope(a.company,org,{document:project(doc),sections:raw.data.map(project)},this.next(p,c,name,a,page,raw),{},['Section content is plain text; images and active HTML are omitted. Follow cursors for remaining sections.']);}
  if(name==='itg_flexible_asset_schema_get'){raw=await this.call(p,c,a.company,`/flexible_asset_types/${a.flexible_asset_type_id}/relationships/flexible_asset_fields`,q);if(!Array.isArray(raw.data))throw bad();return this.envelope(a.company,org,raw.data.map(project),this.next(p,c,name,a,page,raw),{},['Reference schema is account-wide; it does not authorize asset access.']);}
  if(name==='itg_flexible_asset_get'){const r=await this.record(p,c,a.company,org,`/flexible_assets/${a.id}`,a.id),type=String(r.attributes?.['flexible-asset-type-id']??'');id.parse(type);const schema=await this.call(p,c,a.company,`/flexible_asset_types/${type}/relationships/flexible_asset_fields`,{'page[size]':100,'page[number]':1});if(!Array.isArray(schema.data)||schema.meta?.['total-pages']!==1)throw new AppError('precondition_failed','Flexible asset schema is incomplete.');const safe=project(r);safe.attributes.traits=Object.fromEntries(Object.entries(r.attributes?.traits??{}).filter(([k,v])=>{const field=schema.data.find((f:Row)=>f.attributes?.['name-key']===k);return field&&['Text','Textbox','Number','Checkbox','Date'].includes(field.attributes?.kind??field.attributes?.['data-type'])&&(v===null||['string','number','boolean'].includes(typeof v));}).map(([k,v])=>[k,typeof v==='string'?plain(v):v]));return this.envelope(a.company,org,safe,null,{},['Only reviewed primitive traits are included. Password and reference traits are omitted.']);}
  if(name.endsWith('_get'))return this.envelope(a.company,org,project(await this.record(p,c,a.company,org,`/${kind}/${a.id}`,a.id)),null,{},key==='flexible_asset'?['Traits omitted from ordinary reads because fields may contain secrets.']:[]);
  if(kind==='documents'||kind==='checklists')path=`/organizations/${org}/relationships/${kind}`;else{path=`/${kind}`;q['filter[organization_id]']=org;}
  for(const [k,v] of Object.entries(a.filters??{})){if(kind==='checklists')throw new AppError('invalid_input','Checklist name/archived native filters are not supported.');q[`filter[${k}]`]=v;}
  if(a.flexible_asset_type_id)q['filter[flexible_asset_type_id]']=a.flexible_asset_type_id;
  if(kind==='documents'){q['filter[document_folder_id]']=a.folder_id??(a.all_folders?'null':'0');}
  raw=await this.call(p,c,a.company,path,q);if(!Array.isArray(raw.data)||raw.data.length>(a.page_size??50)||raw.data.some((r:Row)=>r.type!==kind!.replaceAll('_','-')||String(r.attributes?.['organization-id'])!==org))throw bad();return this.envelope(a.company,org,raw.data.map(project),this.next(p,c,name,a,page,raw),a.filters??{},kind==='flexible_assets'?['Traits omitted from ordinary reads because fields may contain secrets.']:[]);
 }
 private async unsynced(p:Principal,c:ItGlueConfig,company:number,org:string,recordId:string){const r=(await this.call(p,c,company,`/configurations/${recordId}`,{include:'adapters_resources'})).data;if(String(r?.id)!==recordId||String(r.attributes?.['organization-id'])!==org)throw bad();const links=r.relationships?.['adapters-resources']?.data;if(!Array.isArray(links)||links.length)throw new AppError('precondition_failed','Configuration sync ownership is not verified as empty; edit it through its authoritative provider.');}
 private receipt(company:number,org:string,r:ItGlueReceipt){return{...this.envelope(company,org,{operation_id:r.id,state:r.state,steps:r.steps}),status:r.state,limitations:['Receipts never replay requests. Read-before-write checks are not atomic upstream compare-and-swap.']};}
 private expected(row:Row,fields:Row,expected:Row){for(const [k]of Object.entries(fields)){const native=k.replaceAll('_','-');if(!Object.hasOwn(expected,k)||canonical(expected[k])!==canonical(row.attributes?.[native]))throw new AppError('conflict',`Expected value differs for ${k}.`);}}
 private async write(p:Principal,c:ItGlueConfig,name:ItGlueTool,a:Row,org:string){const previous=await this.store.find(p.tenantId,actorKey(p),a.request_key);if(previous){if(previous.hash!==hash({name,a,version:c.version}))throw new AppError('conflict','Request key already identifies a different write.');return this.receipt(a.company,org,previous);}if((a.sections??[a.fields??{}]).some((section:Row)=>typeof section.content==='string'&&/<(?:script|iframe|object|embed|svg|video|audio|link|meta|style)\b|\bon\w+\s*=|javascript\s*:/i.test(section.content)))throw new AppError('invalid_input','Active HTML is not permitted in document sections.');for(const section of a.sections??[a.fields??{}]){if(typeof section.content!=='string')continue;for(const tag of section.content.match(/<img\b[^>]*>/gi)??[]){const match=tag.match(/\bsrc\s*=\s*(["'])(.*?)\1/i);if(!a.document_id||!match||!/^[^<>]*$/.test(match[2]!)||!new RegExp(`^/${org}/docs/${a.document_id}/developer/images/[1-9][0-9]*$`).test(match[2]!)||/\bsrcset\s*=/i.test(tag))throw new AppError('invalid_input','Document images must use a verified same-document relative image reference.');}}const key=name.slice(4).replace(/_(create|update|publish)$/,''),kind=key==='document_section'?'documents':entity[key],creating=name.endsWith('_create');let path=`/${kind}`,current:Row|undefined,fields:Row={...a.fields};
  const target=a.document_id??a.id;if(!creating){path+=`/${target}`;current=await this.record(p,c,a.company,org,path,target);if(key==='document_section'){path+=`/relationships/sections/${a.section_id}`;const r=(await this.call(p,c,a.company,path)).data;if(String(r?.id)!==a.section_id||(r.attributes?.['document-id']!==undefined&&String(r.attributes['document-id'])!==a.document_id))throw bad();current=r;}}
  if(key==='configuration'){if(!creating)await this.unsynced(p,c,a.company,org,a.id);if(creating){const type=(await this.call(p,c,a.company,`/configuration_types/${a.configuration_type_id}`)).data;if(String(type?.id)!==a.configuration_type_id||type?.type!=='configuration-types')throw new AppError('precondition_failed','Configuration type could not be verified.');fields={...fields,name:a.name,'configuration-type-id':a.configuration_type_id};}}
  if(key==='flexible_asset'){const type=a.flexible_asset_type_id??String(current?.attributes?.['flexible-asset-type-id']??'');id.parse(type);const schema=await this.call(p,c,a.company,`/flexible_asset_types/${type}/relationships/flexible_asset_fields`,{'page[size]':100,'page[number]':1});if(!Array.isArray(schema.data)||schema.meta?.['total-pages']!==1)throw new AppError('precondition_failed','Flexible asset schema is incomplete.');for(const k of Object.keys(a.traits)){const f=schema.data.find((r:Row)=>r.attributes?.['name-key']===k);if(!f||!['Text','Textbox','Number','Checkbox','Date'].includes(f.attributes?.kind??f.attributes?.['data-type']))throw new AppError('precondition_failed','Only reviewed primitive, non-secret flexible asset fields are writable.');const value=a.traits[k],kind=f.attributes.kind??f.attributes['data-type'];if(value!==null&&((kind==='Number'&&typeof value!=='number')||(kind==='Checkbox'&&typeof value!=='boolean')||(['Text','Textbox'].includes(kind)&&typeof value!=='string')||(kind==='Date'&&(typeof value!=='string'||(!/^\d{4}-\d{2}-\d{2}$/.test(value)||Number.isNaN(Date.parse(value))||new Date(value).toISOString().slice(0,10)!==value)))))throw new AppError('invalid_input','Flexible asset value does not match native field type.');}if(creating&&schema.data.some((f:Row)=>f.attributes?.required&&(!Object.hasOwn(a.traits,f.attributes['name-key'])||a.traits[f.attributes['name-key']]===null||a.traits[f.attributes['name-key']]==='')))throw new AppError('invalid_input','Required flexible asset field missing.');if(!creating&&Object.keys(current!.attributes.traits??{}).some(k=>{const f=schema.data.find((f:Row)=>f.attributes?.['name-key']===k);return !f||!['Text','Textbox','Number','Checkbox','Date'].includes(f.attributes?.kind??f.attributes?.['data-type']);}))throw new AppError('precondition_failed','Asset has secret or unreviewed traits; native replacement is not safe.');fields={traits:creating?a.traits:{...current!.attributes.traits,...a.traits},...(creating?{'flexible-asset-type-id':type}:{})};}
  if(name==='itg_document_create')fields={name:a.name};
  if(!creating){if(name==='itg_document_publish'){if(!Object.keys(a.expected).length)throw new AppError('invalid_input','Publishing requires expected document values.');fields={};this.expected(current!,a.expected,a.expected);path+='/publish';}else{if(!Object.keys(fields).length)throw new AppError('invalid_input','Supply changed fields.');this.expected(current!,fields,a.expected);}}
  const reservation=await this.store.reserve(p.tenantId,{id:randomUUID(),actor:actorKey(p),requestKey:a.request_key,hash:hash({name,a,version:c.version}),organizationId:org,companyId:a.company,connectionVersion:c.version,state:'reserved',steps:[],intent:{name,args:a},createdAt:new Date().toISOString()}),receipt=reservation.receipt;if(receipt.hash!==hash({name,a,version:c.version}))throw new AppError('conflict','Request key already identifies a different write.');if(!reservation.created)return this.receipt(a.company,org,receipt);
  let dispatched=false;const guard=async()=>{await this.guard(p,c,a.company,true);await this.organization(p,c,a.company,org);if(!creating){if(key==='configuration')await this.unsynced(p,c,a.company,org,a.id);const fresh=await this.record(p,c,a.company,org,`/${kind}/${target}`,target);if(key==='document_section'){const section=(await this.call(p,c,a.company,`/documents/${target}/relationships/sections/${a.section_id}`)).data;if(String(section?.id)!==a.section_id||(section.attributes?.['document-id']!==undefined&&String(section.attributes['document-id'])!==a.document_id))throw bad();this.expected(section,fields,a.expected);}else this.expected(fresh,name==='itg_document_publish'?a.expected:fields,a.expected);}};
  const dispatch=async(route:string,type:string,attrs:Row,method:'POST'|'PATCH')=>{await guard();receipt.state='dispatching';await this.store.finish(p.tenantId,receipt);const body={data:{type,attributes:attrs}};const r=await this.port.request(c,route,{},body,()=>this.guard(p,c,a.company,true),async()=>{await guard();if(creating&&route.includes('/relationships/sections')){const documentId=route.split('/')[2]!;await this.record(p,c,a.company,org,`/documents/${documentId}`,documentId);}dispatched=true;},method);if(!id.safeParse(String(r.data?.id??'')).success)throw new AppError('unknown_outcome','IT Glue did not return an object ID.');receipt.steps.push({path:route,id:String(r.data.id),state:'accepted_unverified'});await this.store.finish(p.tenantId,receipt);return r.data;};
  try{const nativeFields=Object.fromEntries(Object.entries(fields).map(([k,v])=>[k.replaceAll('_','-'),v]));const result=await dispatch(path,key==='document_section'?'document-sections':kind!.replaceAll('_','-'),{...nativeFields,...(creating?{'organization-id':org}:{})},creating?'POST':'PATCH');if(name==='itg_document_create'){for(const section of a.sections){await this.record(p,c,a.company,org,`/documents/${result.id}`,String(result.id));await dispatch(`/documents/${result.id}/relationships/sections`,'document-sections',Object.fromEntries(Object.entries(section).map(([k,v])=>[k.replaceAll('_','-'),v])),'POST');}}
   receipt.state='accepted_unverified';await this.store.finish(p.tenantId,receipt);
   if(!creating&&name!=='itg_document_publish')await withReconciliation(async()=>{const readback=(await this.call(p,c,a.company,path)).data;if(String(readback?.id)!==String(result.id))throw bad();if(Object.entries(nativeFields).every(([k,v])=>canonical(readback.attributes?.[k])===canonical(v))){receipt.state='verified';await this.store.finish(p.tenantId,receipt);}});
  }catch(e){receipt.state=dispatched?(receipt.steps.length?'partial':'unknown_outcome'):'failed';await this.store.finish(p.tenantId,receipt);if(!dispatched)throw e;}
  return this.receipt(a.company,org,receipt);
 }
}
