import {createHash,randomUUID} from 'node:crypto';
import {z} from 'zod';
import {AppError,type Principal,type PrincipalStore} from '../../contracts/src/index.js';
import {reauthorize,assertCapability,assertCompanyScope} from '../../policy/src/index.js';
import {assertArea} from '../../policy/src/areas.js';
import {IntentCipher} from '../../storage/src/index.js';
import type {ReadJob,ReadJobStore} from './store.js';
export const reportStartSchema=z.object({request_key:z.string().min(8).max(128),company_id:z.number().int().nonnegative(),sections:z.array(z.enum(['tickets','devices','alerts','documentation'])).min(1).max(4).default(['tickets']),max_items:z.number().int().min(1).max(100).default(25)}).strict();
export const reportIdSchema=z.object({report_id:z.string().uuid()}).strict();
export type ReportInput={schema_version:1;company_id:number;sections:('tickets'|'devices'|'alerts'|'documentation')[];max_items:number};
export interface ReportExecution {signal:AbortSignal;guard:()=>Promise<Principal>}
export type ReportExecutor=(principal:Principal,input:ReportInput,execution:ReportExecution)=>Promise<unknown>;
const TTL=24*60*60*1000;
export const MAX_REPORT_RESULT_BYTES=100_000;
export class DurableReadReports {
 constructor(readonly store:ReadJobStore,readonly cipher:IntentCipher,readonly principals:PrincipalStore,readonly execute:ReportExecutor,readonly now:()=>number=Date.now){}
 private binding(j:ReadJob,kind:'input'|'result'){return`read-report:v1:${j.tenant}:${j.actor}:${j.id}:${kind}`;}
 async authorize(p:Principal,company:number){const fresh=await reauthorize(p,this.principals);assertCapability(fresh,'operational.read');assertArea(fresh,'configuration');assertCompanyScope(fresh,company);return fresh;}
 private checkSections(p:Principal,input:ReportInput){for(const section of input.sections){if(section==='tickets')assertArea(p,'tickets');if(section==='devices'||section==='alerts')assertCapability(p,'rmm.read');if(section==='documentation')assertCapability(p,'documentation.read');}}
 async start(p:Principal,input:unknown){const a=reportStartSchema.parse(input);const fresh=await this.authorize(p,a.company_id);const data:ReportInput={schema_version:1,company_id:a.company_id,sections:[...new Set(a.sections)].sort() as ReportInput['sections'],max_items:a.max_items},now=this.now();this.checkSections(fresh,data);const j:ReadJob={id:randomUUID(),tenant:p.tenantId,actor:p.objectId,requestKey:a.request_key,hash:createHash('sha256').update(JSON.stringify(data)).digest('hex'),company:a.company_id,state:'queued',input:'',result:null,error:null,created:now,updated:now,expires:now+TTL,leaseUntil:0,owner:null,fence:0,attempts:0};j.input=this.cipher.seal(data,this.binding(j,'input'));const saved=await this.store.reserve(j);if(saved.hash!==j.hash)throw new AppError('conflict','Report request key already identifies different inputs.');await this.authorize(p,saved.company);return this.view(saved);}
 private view(j:ReadJob){return{report_id:j.id,state:j.state,company_id:j.company,created_at:new Date(j.created).toISOString(),updated_at:new Date(j.updated).toISOString(),expires_at:new Date(j.expires).toISOString(),schema_version:1,poll_interval_ms:1000,...(j.error?{error_code:j.error}:{})};}
 async load(p:Principal,id:string){reportIdSchema.parse({report_id:id});const j=await this.store.get(p.tenantId,p.objectId,id,this.now());if(!j)throw new AppError('not_found_or_inaccessible','Report is unavailable or expired.');const fresh=await this.authorize(p,j.company);this.checkSections(fresh,this.cipher.open(j.input,this.binding(j,'input')) as ReportInput);return j;}
 async status(p:Principal,id:string){return this.view(await this.load(p,id));}
 async result(p:Principal,id:string){const j=await this.load(p,id),data=j.state==='completed'&&j.result?this.cipher.open(j.result,this.binding(j,'result')):null;const fresh=await this.authorize(p,j.company);this.checkSections(fresh,this.cipher.open(j.input,this.binding(j,'input')) as ReportInput);return{...this.view(j),data};}
 async cancel(p:Principal,id:string){const j=await this.load(p,id);await this.store.cancel(j.tenant,j.actor,j.id,this.now());return this.status(p,id);}
 async run(j:ReadJob,signal:AbortSignal){const guard=async()=>{signal.throwIfAborted();const current=await this.store.get(j.tenant,j.actor,j.id,this.now());if(!current||current.state!=='running'||current.fence!==j.fence||current.owner!==j.owner||current.leaseUntil<=this.now())throw new AppError('precondition_failed','Report lease or cancellation prevents further reads.');const p=await this.principals.get(j.tenant,j.actor);if(!p)throw new AppError('forbidden','Report employee is no longer authorized.');return this.authorize(p,j.company);};const p=await guard(),input=this.cipher.open(j.input,this.binding(j,'input')) as ReportInput;if(input.schema_version!==1||input.company_id!==j.company)throw new AppError('conflict','Stored report schema is unsupported.');this.checkSections(p,input);let onAbort!:()=>void;const interrupted=new Promise<never>((_,reject)=>{onAbort=()=>reject(new AppError('precondition_failed','Report deadline or cancellation interrupted the read.'));signal.addEventListener('abort',onAbort,{once:true});if(signal.aborted)onAbort();});let result:unknown;try{result=await Promise.race([this.execute(p,input,{signal,guard:async()=>{const current=await guard();this.checkSections(current,input);return current;}}),interrupted]);}finally{signal.removeEventListener('abort',onAbort);}const fresh=await guard();this.checkSections(fresh,input);const serialized=JSON.stringify(result);if(typeof serialized!=='string'||Buffer.byteLength(serialized)>MAX_REPORT_RESULT_BYTES)throw new AppError('precondition_failed','Report result exceeds the encrypted result bound; select fewer records.');return this.cipher.seal(result,this.binding(j,'result'));}
}
/** Separate worker: never executes existing write jobs or invokes arbitrary tool names. */
export class DurableReadWorker {
 private timer?:ReturnType<typeof setInterval>;private running?:Promise<boolean>;private abort?:AbortController;private stopped=false;private owner=randomUUID();
 constructor(private reports:DurableReadReports,private leaseMs=30_000,private maxRunMs=120_000,private observe?: (job:ReadJob,signal:AbortSignal,run:()=>Promise<string>)=>Promise<string>){if(leaseMs<30||maxRunMs<leaseMs||maxRunMs>300_000)throw new Error('Invalid report lease or deadline');}
 start(){if(this.timer)return;this.stopped=false;this.timer=setInterval(()=>{if(!this.running&&!this.stopped){this.running=this.tick().finally(()=>{this.running=undefined;});void this.running.catch(()=>{});}},1000);this.timer.unref();}
 async tick(){if(this.stopped)return false;const {store,now}=this.reports;await store.purge(now());const j=await store.claim(this.owner,now(),this.leaseMs);if(!j)return false;const abort=new AbortController();this.abort=abort;const signal=AbortSignal.any([abort.signal,AbortSignal.timeout(this.maxRunMs)]);let renewing=false;
  const renewal=setInterval(()=>{if(renewing)return;renewing=true;void store.renew(j,now(),this.leaseMs).then(ok=>{if(!ok)abort.abort();}).catch(()=>abort.abort()).finally(()=>{renewing=false;});},Math.max(10,Math.floor(this.leaseMs/3)));renewal.unref();
  try{const complete=async()=>{const result=await this.reports.run(j,signal);await store.finish(j,now(),'completed',result,null);return result;};await (this.observe?this.observe(j,signal,complete):complete());}catch{await store.finish(j,now(),'failed',null,signal.aborted?'report_interrupted':'report_read_failed');}finally{clearInterval(renewal);if(this.abort===abort)this.abort=undefined;}return true;
 }
 async close(){this.stopped=true;if(this.timer)clearInterval(this.timer);this.timer=undefined;this.abort?.abort();await this.running;}
}
