import {createHash,randomUUID} from 'node:crypto';
import {inputRequired} from '@modelcontextprotocol/server';
import {z} from 'zod';
import {AppError,type Principal} from '../../contracts/src/index.js';
import {IntentCipher,type SqlClient} from '../../storage/src/index.js';
import type {DurableReadReports} from './index.js';
export const TASKS_EXTENSION='io.modelcontextprotocol/tasks';
export function supportsSelectionMrtr(envelope:Record<string,unknown>|undefined){const caps=envelope?.['io.modelcontextprotocol/clientCapabilities'] as {elicitation?:{form?:unknown}}|undefined;return envelope?.['io.modelcontextprotocol/protocolVersion']==='2026-07-28'&&!!caps?.elicitation&&caps.elicitation.form!==null&&typeof caps.elicitation.form==='object'&&!Array.isArray(caps.elicitation.form);}

export function supportsTasks(protocol:string,capabilities:unknown){const c=capabilities as {extensions?:Record<string,unknown>}|null;const extension=c?.extensions?.[TASKS_EXTENSION];return protocol==='2026-07-28'&&extension!==null&&typeof extension==='object'&&!Array.isArray(extension);}
/** Extension wire adapter, separate from the SDK's incompatible legacy Tasks types. */
export class ReadReportTasks {
 constructor(private reports:DurableReadReports){}
 async create(p:Principal,input:unknown,protocol:string,capabilities:unknown){const started=await this.reports.start(p,input);if(!supportsTasks(protocol,capabilities))return{mode:'ordinary' as const,report:started};return{mode:'task' as const,result:{resultType:'task',...this.task(started)}};}
 private task(r:any){return{taskId:r.report_id,status:r.state==='cancelled'?'cancelled':r.state==='completed'||r.state==='failed'?'completed':'working',createdAt:r.created_at,lastUpdatedAt:r.updated_at,ttlMs:Date.parse(r.expires_at)-Date.parse(r.created_at),pollIntervalMs:r.poll_interval_ms};}
 async dispatch(p:Principal,method:string,params:unknown,protocol:string,capabilities:unknown){if(!supportsTasks(protocol,capabilities))throw new AppError('unsupported_operation','Tasks extension was not advertised for this request; use ordinary report tools.');const {taskId}=z.object({taskId:z.string().uuid()}).strict().parse(params);if(method==='tasks/cancel'){const r=await this.reports.cancel(p,taskId);return{resultType:'complete',...this.task(r)};}if(method!=='tasks/get'&&method!=='tasks/update')throw new AppError('unsupported_operation','Unsupported task method.');const r=await this.reports.result(p,taskId);return{resultType:'complete',...this.task(r),...(['completed','failed'].includes(r.state)?{result:{content:[{type:'text',text:JSON.stringify(r.data??{error_code:r.error_code})}],...(r.state==='failed'?{isError:true}:{structuredContent:r.data})}}:{})};}
}
export interface SelectionReplayStore {reserve(id:string,expires:number):Promise<void>;consume(id:string,now:number):Promise<boolean>}
export class MemorySelectionReplayStore implements SelectionReplayStore {private entries=new Map<string,number>();async reserve(id:string,expires:number){for(const [key,value]of this.entries)if(value<=expires-300_000)this.entries.delete(key);if(this.entries.size>=10000)throw new AppError('throttled','Selection capacity is temporarily full.');this.entries.set(id,expires);}async consume(id:string,now:number){const expires=this.entries.get(id);this.entries.delete(id);for(const [key,value]of this.entries)if(value<=now)this.entries.delete(key);return expires!==undefined&&expires>now;}}
export class PostgresSelectionReplayStore implements SelectionReplayStore {constructor(private db:SqlClient){}async reserve(id:string,expires:number){await this.db.query('DELETE FROM read_selection_handles WHERE expires_ms<$1',[expires-300_000]);await this.db.query('INSERT INTO read_selection_handles(id,expires_ms) VALUES($1,$2)',[id,expires]);}async consume(id:string,now:number){return!!(await this.db.query('DELETE FROM read_selection_handles WHERE id=$1 AND expires_ms>$2 RETURNING id',[id,now])).rows.length;}}
const stable=(v:any):string=>Array.isArray(v)?`[${v.map(stable).join(',')}]`:v&&typeof v==='object'?`{${Object.keys(v).sort().map(k=>`${JSON.stringify(k)}:${stable(v[k])}`).join(',')}}`:JSON.stringify(v);
const fingerprint=(input:unknown)=>createHash('sha256').update(stable(input)).digest('hex');
/** Selection only. No write approval semantics or mutation callback is exposed. */
export class ReadSelectionContinuation {
 constructor(private cipher:IntentCipher,private replay:SelectionReplayStore,private now:()=>number=Date.now){}
 private binding(p:Principal){return`read-selection:v1:${p.tenantId}:${p.objectId}`;}
 async offer(p:Principal,operation:string,input:unknown,candidates:{id:string;label:string}[],modernFormSupported:boolean){const choices=z.array(z.object({id:z.string().min(1).max(100),label:z.string().max(200)}).strict()).min(2).max(20).parse(candidates);if(new Set(choices.map(c=>c.id)).size!==choices.length)throw new AppError('invalid_input','Selection candidates must have unique IDs.');if(!modernFormSupported)return{mode:'ordinary' as const,candidates:choices,requires_selection:true};const nonce=randomUUID(),expires=this.now()+300_000;await this.replay.reserve(nonce,expires);const token=this.cipher.seal({nonce,expires,operation,fingerprint:fingerprint(input),mapping:p.mappingVersion,policy:p.policyVersion,ids:choices.map(c=>c.id)},this.binding(p));return{mode:'mrtr' as const,result:inputRequired({requestState:token,inputRequests:{selection:inputRequired.elicit({message:'Select the intended authorized record by native ID.',requestedSchema:{type:'object',properties:{selected_id:{type:'string',enum:choices.map(c=>c.id)}},required:['selected_id']}})}})};}
 async resume(p:Principal,operation:string,input:unknown,token:string,response:unknown,authorize:(selectedId:string)=>Promise<Principal>){const s=this.cipher.open(token,this.binding(p)) as any;if(s.operation!==operation||s.fingerprint!==fingerprint(input)||s.expires<=this.now()||s.mapping!==p.mappingVersion||s.policy!==p.policyVersion||!Array.isArray(s.ids)||typeof s.nonce!=='string')throw new AppError('conflict','Selection continuation changed or expired.');const r=z.object({action:z.enum(['accept','decline','cancel']),content:z.object({selected_id:z.string()}).optional()}).strict().parse(response);if(r.action!=='accept'){if(!await this.replay.consume(s.nonce,this.now()))throw new AppError('conflict','Selection continuation was already used.');return{status:'cancelled' as const};}const selected=r.content?.selected_id;if(!selected||!s.ids.includes(selected))throw new AppError('invalid_input','Selected ID is not one of the reviewed candidates.');const fresh=await authorize(selected);if(!fresh.active||fresh.tenantId!==p.tenantId||fresh.objectId!==p.objectId||fresh.mappingVersion!==s.mapping||fresh.policyVersion!==s.policy)throw new AppError('conflict','Selection authorization changed.');if(!await this.replay.consume(s.nonce,this.now()))throw new AppError('conflict','Selection continuation was already used.');return{status:'selected' as const,id:selected};}
}
