import {createHash} from 'node:crypto';
import {z} from 'zod';
import {AppError,actorKey,type JournalRecord,type Principal} from '../../contracts/src/index.js';
import {assertCapability,assertCompanyScope,reauthorize} from '../../policy/src/index.js';
import {assertArea} from '../../policy/src/areas.js';
import type {TicketWorkflows} from './index.js';
import {ticketReferenceSchema} from './index.js';

const requestKey=z.string().min(8).max(128).refine(v=>!v.startsWith('job:')&&!v.startsWith('wf:'),'This request-key prefix is reserved.');
export const ticketTagOptionsSchema=z.object({ticket:ticketReferenceSchema,query:z.string().trim().min(1).max(50)}).strict();
export const ticketTagAddSchema=z.object({ticket:ticketReferenceSchema,tag_id:z.number().int().positive().safe(),tag_label:z.string().trim().min(1).max(50),request_key:requestKey}).strict();
export const ticketTagRemoveSchema=z.object({ticket:ticketReferenceSchema,association_id:z.number().int().positive().safe(),tag_id:z.number().int().positive().safe(),tag_label:z.string().trim().min(1).max(50),request_key:requestKey}).strict();

type TagOptions={ticket_id:number;company_id:number;current_tags:{association_id:number;tag_id:number;label:string}[];eligible_tags:{id:number;label:string;group_id:number|null}[];limit:number;remaining:number;valid_until:string};
const normalize=(v:string)=>v.normalize('NFKC').trim().replace(/\s+/g,' ').toLocaleLowerCase('en-US');
const canonical=(v:unknown):string=>Array.isArray(v)?`[${v.map(canonical).join(',')}]`:v&&typeof v==='object'?`{${Object.entries(v).sort(([a],[b])=>a.localeCompare(b)).map(([k,x])=>`${JSON.stringify(k)}:${canonical(x)}`).join(',')}}`:JSON.stringify(v)??'null';
const hash=(v:unknown)=>createHash('sha256').update(canonical(v)).digest('hex');
const unavailable=()=>new AppError('not_found_or_inaccessible','Ticket or tag choice is unavailable.');

/** One ticket tag association at a time; mutations always use the Tickets child route. */
export class TicketTagWorkflows {
 constructor(private readonly core:TicketWorkflows,private readonly resolveOptions:(p:Principal,ticketId:number,query:string,knownTicket?:Record<string,unknown>)=>Promise<TagOptions>,private readonly now:()=>number=Date.now){}
 private async current(p:Principal,write:boolean){const fresh=await reauthorize(p,this.core.principals,{resourceMaxAgeMs:300_000,now:()=>new Date(this.now())});assertCapability(fresh,'operational.read');assertArea(fresh,'tickets',write);if(write)assertCapability(fresh,'tickets.write');return fresh;}
 private async ticket(p:Principal,ref:z.infer<typeof ticketReferenceSchema>){const t=await this.core.resolveTicket(p,ref);assertCompanyScope(p,t.companyID);return t;}
 async options(p:Principal,input:unknown){const a=ticketTagOptionsSchema.parse(input);p=await this.current(p,false);const ticket=await this.ticket(p,a.ticket),data=await this.resolveOptions(p,ticket.id,a.query,ticket);p=await this.current(p,false);if(data.ticket_id!==ticket.id||data.company_id!==ticket.companyID||Date.parse(data.valid_until)<=this.now())throw new AppError('missing_metadata','Current ticket tag options are incomplete or expired.');return{status:'succeeded',...data,provenance:{source:this.core.adapter.source,fetched_at:new Date(this.now()).toISOString()},warnings:['Only active tags matching the supplied search text are offered.']};}
 private view(r:JournalRecord){const operation=r.operation==='ticket_tag_add'?'added':'removed';return{status:r.state,operation_id:r.id,data:r.result??{},can_resume:false,safe_to_redispatch:false,receipt:r.state==='succeeded_verified'?`The ticket tag was ${operation} and verified.`:r.state==='failed'?'The ticket tag was not changed.':'The write outcome is not confirmed. Check the ticket before attempting another change.',provenance:{source:this.core.adapter.source}};}
 private async prior(p:Principal,operation:'ticket_tag_add'|'ticket_tag_remove',key:string,payload:Record<string,unknown>){const payloadHash=hash({definition:`${operation}-v1`,actor:actorKey(p),mapping:p.mappingVersion,policy:p.policyVersion,payload}),prior=await this.core.journal.find(actorKey(p),key);if(!prior)return undefined;if(prior.operation!==operation||prior.payloadHash!==payloadHash||prior.mappingVersion!==p.mappingVersion||prior.resourceId!==p.resourceId||prior.policyVersion!==p.policyVersion)throw new AppError('conflict','This request key belongs to different work.');return prior;}
 private async reserve(p:Principal,operation:'ticket_tag_add'|'ticket_tag_remove',key:string,payload:Record<string,unknown>){const payloadHash=hash({definition:`${operation}-v1`,actor:actorKey(p),mapping:p.mappingVersion,policy:p.policyVersion,payload});const prior=await this.core.journal.find(actorKey(p),key);if(prior){if(prior.operation!==operation||prior.payloadHash!==payloadHash||prior.mappingVersion!==p.mappingVersion||prior.resourceId!==p.resourceId||prior.policyVersion!==p.policyVersion)throw new AppError('conflict','This request key belongs to different work.');return{record:prior,created:false};}return this.core.journal.reserve({actorKey:actorKey(p),requestKey:key,payloadHash,operation,mappingVersion:p.mappingVersion,resourceId:p.resourceId,policyVersion:p.policyVersion,result:{...payload}});}
 async add(p:Principal,input:unknown){
  const a=ticketTagAddSchema.parse(input);p=await this.current(p,true);if(!this.core.adapter.createTicketTagAssociation)throw new AppError('unsupported_operation','Ticket tag writes are unavailable in this environment.');
  const ticket=await this.ticket(p,a.ticket),options=await this.resolveOptions(p,ticket.id,a.tag_label,ticket);if(options.ticket_id!==ticket.id||options.company_id!==ticket.companyID||Date.parse(options.valid_until)<=this.now())throw new AppError('missing_metadata','Current ticket tag options are incomplete or expired.');
  const tag=options.eligible_tags.filter(v=>v.id===a.tag_id&&v.label===a.tag_label);if(tag.length!==1)throw unavailable();const payload={ticket_id:ticket.id,company_id:ticket.companyID,tag_id:a.tag_id,tag_label:tag[0]!.label},prior=await this.prior(p,'ticket_tag_add',a.request_key,payload);if(prior)return this.view(prior);if(options.current_tags.some(v=>v.tag_id===a.tag_id))throw new AppError('conflict','This tag is already associated with the ticket.');if(options.current_tags.length>=30||options.remaining<=0)throw new AppError('precondition_failed','The ticket already has the maximum 30 tags.');
  const reserved=await this.reserve(p,'ticket_tag_add',a.request_key,payload);if(!reserved.created)return this.view(reserved.record);
  let state:JournalRecord['state']='ready',accepted=false;
  try{await this.core.journal.transition(reserved.record.id,'ready','dispatching',{...payload});state='dispatching';const beforeDispatch=async()=>{p=await this.current(p,true);const freshTicket=await this.ticket(p,{kind:'id',id:ticket.id}),fresh=await this.resolveOptions(p,ticket.id,a.tag_label,freshTicket);if(freshTicket.companyID!==ticket.companyID||fresh.company_id!==ticket.companyID||Date.parse(fresh.valid_until)<=this.now())throw new AppError('precondition_failed','Ticket access or tag options changed before dispatch.');const currentTag=fresh.eligible_tags.find(v=>v.id===a.tag_id&&normalize(v.label)===normalize(a.tag_label));if(!currentTag||fresh.current_tags.some(v=>v.tag_id===a.tag_id)||fresh.current_tags.length>=30)throw new AppError('precondition_failed','The selected tag or ticket assignments changed before dispatch. Refresh tag options.');};const saved=await this.core.adapter.createTicketTagAssociation(p,ticket.id,a.tag_id,beforeDispatch);accepted=true;let record=await this.core.journal.transition(reserved.record.id,'dispatching','accepted_unverified',{...payload,association_id:saved.id,verification:{performed:false}});state='accepted_unverified';const after=await this.resolveOptions(p,ticket.id,a.tag_label);const verified=after.ticket_id===ticket.id&&after.company_id===ticket.companyID&&after.current_tags.some(v=>v.association_id===saved.id&&v.tag_id===a.tag_id);if(verified)record=await this.core.journal.transition(record.id,'accepted_unverified','succeeded_verified',{...payload,association_id:saved.id,verification:{performed:true,complete:true}});return this.view(record);
  }catch(error){const code=error instanceof AppError?error.code:'dependency_unavailable';const unknown=accepted||code==='unknown_outcome';try{await this.core.journal.transition(reserved.record.id,state,unknown?'unknown_outcome':'failed',{...payload,error_code:code,verification:{performed:false}});}catch{}const saved=await this.core.journal.get(reserved.record.id,actorKey(p));if(saved)return this.view(saved);throw error;}
 }
 async remove(p:Principal,input:unknown){
  const a=ticketTagRemoveSchema.parse(input);p=await this.current(p,true);if(!this.core.adapter.deleteTicketTagAssociation)throw new AppError('unsupported_operation','Ticket tag deletion is unavailable in this environment.');
  const ticket=await this.ticket(p,a.ticket),payload={ticket_id:ticket.id,company_id:ticket.companyID,association_id:a.association_id,tag_id:a.tag_id,tag_label:a.tag_label},prior=await this.prior(p,'ticket_tag_remove',a.request_key,payload);if(prior)return this.view(prior);const options=await this.resolveOptions(p,ticket.id,a.tag_label,ticket);if(options.ticket_id!==ticket.id||options.company_id!==ticket.companyID||Date.parse(options.valid_until)<=this.now())throw new AppError('missing_metadata','Current ticket tag options are incomplete or expired.');
  const association=options.current_tags.filter(v=>v.association_id===a.association_id&&v.tag_id===a.tag_id&&v.label===a.tag_label);if(association.length!==1)throw unavailable();
  const reserved=await this.reserve(p,'ticket_tag_remove',a.request_key,payload);if(!reserved.created)return this.view(reserved.record);
  let state:JournalRecord['state']='ready',accepted=false;
  try{await this.core.journal.transition(reserved.record.id,'ready','dispatching',{...payload});state='dispatching';const beforeDispatch=async()=>{p=await this.current(p,true);const freshTicket=await this.ticket(p,{kind:'id',id:ticket.id}),fresh=await this.resolveOptions(p,ticket.id,a.tag_label,freshTicket);if(freshTicket.companyID!==ticket.companyID||fresh.company_id!==ticket.companyID||Date.parse(fresh.valid_until)<=this.now())throw new AppError('precondition_failed','Ticket access or tag options changed before dispatch.');const current=fresh.current_tags.filter(v=>v.association_id===a.association_id&&v.tag_id===a.tag_id&&v.label===a.tag_label);if(current.length!==1)throw new AppError('precondition_failed','The selected tag association changed before dispatch. Refresh tag options.');};await this.core.adapter.deleteTicketTagAssociation(p,ticket.id,a.association_id,beforeDispatch);accepted=true;let record=await this.core.journal.transition(reserved.record.id,'dispatching','accepted_unverified',{...payload,verification:{performed:false}});state='accepted_unverified';const after=await this.resolveOptions(p,ticket.id,a.tag_label);const verified=after.ticket_id===ticket.id&&after.company_id===ticket.companyID&&!after.current_tags.some(v=>v.association_id===a.association_id);if(verified)record=await this.core.journal.transition(record.id,'accepted_unverified','succeeded_verified',{...payload,verification:{performed:true,complete:true}});return this.view(record);
  }catch(error){const code=error instanceof AppError?error.code:'dependency_unavailable';const unknown=accepted||code==='unknown_outcome';try{await this.core.journal.transition(reserved.record.id,state,unknown?'unknown_outcome':'failed',{...payload,error_code:code,verification:{performed:false}});}catch{}const saved=await this.core.journal.get(reserved.record.id,actorKey(p));if(saved)return this.view(saved);throw error;}
 }
 async status(p:Principal,input:unknown){const a=z.object({operation_id:z.string().uuid()}).strict().parse(input);p=await this.current(p,false);const r=await this.core.journal.get(a.operation_id,actorKey(p));if(!r||!['ticket_tag_add','ticket_tag_remove'].includes(r.operation)||r.mappingVersion!==p.mappingVersion||r.resourceId!==p.resourceId||r.policyVersion!==p.policyVersion)throw unavailable();if(r.result?.ticket_id)await this.ticket(p,{kind:'id',id:Number(r.result.ticket_id)});return this.view(r);}
}
