import {createHash} from 'node:crypto';
import {z} from 'zod';
import {AppError,actorKey,type JournalRecord,type Principal} from '../../contracts/src/index.js';
import {assertCapability,assertCompanyScope,reauthorize} from '../../policy/src/index.js';
import {assertArea} from '../../policy/src/areas.js';
import type {TicketWorkflows} from './index.js';
import {ticketReferenceSchema} from './index.js';

const requestKey=z.string().min(8).max(128).refine(v=>!v.startsWith('job:')&&!v.startsWith('wf:'),'This request-key prefix is reserved.');
export const ticketChecklistLibraryOptionsSchema=z.object({ticket:ticketReferenceSchema,query:z.string().trim().min(1).max(50)}).strict();
export const ticketChecklistLibraryApplySchema=z.object({ticket:ticketReferenceSchema,library_id:z.number().int().positive().safe(),library_name:z.string().trim().min(1).max(100),request_key:requestKey}).strict();
type LibraryOptions={ticket_id:number;company_id:number;current_item_count:number;limit:number;remaining:number;libraries:{id:number;name:string;description:string|null;item_count:number;fingerprint:string}[];valid_until:string};
const normalize=(v:string)=>v.normalize('NFKC').trim().replace(/\s+/g,' ').toLocaleLowerCase('en-US');
const canonical=(v:unknown):string=>Array.isArray(v)?`[${v.map(canonical).join(',')}]`:v&&typeof v==='object'?`{${Object.entries(v).sort(([a],[b])=>a.localeCompare(b)).map(([k,x])=>`${JSON.stringify(k)}:${canonical(x)}`).join(',')}}`:JSON.stringify(v)??'null';
const hash=(v:unknown)=>createHash('sha256').update(canonical(v)).digest('hex');
const unavailable=()=>new AppError('not_found_or_inaccessible','Ticket or checklist library is unavailable.');

/** Applies one active ticket checklist library through Autotask's parent child route. */
export class TicketChecklistLibraryWorkflows {
 constructor(private readonly core:TicketWorkflows,private readonly resolveOptions:(p:Principal,ticketId:number,query:string,knownTicket?:Record<string,unknown>)=>Promise<LibraryOptions>,private readonly now:()=>number=Date.now){}
 private async current(p:Principal,write:boolean){const fresh=await reauthorize(p,this.core.principals,{resourceMaxAgeMs:300_000,now:()=>new Date(this.now())});assertCapability(fresh,'operational.read');assertArea(fresh,'tickets',write);if(write)assertCapability(fresh,'tickets.write');return fresh;}
 private async ticket(p:Principal,ref:z.infer<typeof ticketReferenceSchema>){const t=await this.core.resolveTicket(p,ref);assertCompanyScope(p,t.companyID);return t;}
 async options(p:Principal,input:unknown){const a=ticketChecklistLibraryOptionsSchema.parse(input);p=await this.current(p,false);const ticket=await this.ticket(p,a.ticket),data=await this.resolveOptions(p,ticket.id,a.query,ticket);p=await this.current(p,false);if(data.ticket_id!==ticket.id||data.company_id!==ticket.companyID||Date.parse(data.valid_until)<=this.now())throw new AppError('missing_metadata','Current checklist library options are incomplete or expired.');return{status:'succeeded',ticket_id:ticket.id,company_id:ticket.companyID,current_item_count:data.current_item_count,limit:data.limit,remaining:data.remaining,libraries:data.libraries.map(({fingerprint,...library})=>({...library,can_apply:library.item_count>0&&library.item_count<=data.remaining})),valid_until:data.valid_until,provenance:{source:this.core.adapter.source,fetched_at:new Date(this.now()).toISOString()},warnings:['Applying a library appends its checklist items to the ticket. Applying the same library again appends another copy.']};}
 private view(r:JournalRecord){return{status:r.state,operation_id:r.id,data:r.result??{},can_resume:false,safe_to_redispatch:false,receipt:r.state==='succeeded_verified'?'The checklist library was applied and its item count was verified.':r.state==='failed'?'The checklist library was not applied.':'The write outcome is not confirmed. Check the ticket checklist before attempting another change.',provenance:{source:this.core.adapter.source}};}
 private async prior(p:Principal,key:string,payload:Record<string,unknown>){const payloadHash=hash({definition:'ticket-checklist-library-apply-v1',actor:actorKey(p),mapping:p.mappingVersion,policy:p.policyVersion,payload}),prior=await this.core.journal.find(actorKey(p),key);if(!prior)return undefined;if(prior.operation!=='ticket_checklist_library_apply'||prior.payloadHash!==payloadHash||prior.mappingVersion!==p.mappingVersion||prior.resourceId!==p.resourceId||prior.policyVersion!==p.policyVersion)throw new AppError('conflict','This request key belongs to different work.');return prior;}
 async apply(p:Principal,input:unknown){
  const a=ticketChecklistLibraryApplySchema.parse(input);p=await this.current(p,true);if(!this.core.adapter.applyTicketChecklistLibrary)throw new AppError('unsupported_operation','Ticket checklist library writes are unavailable in this environment.');
  const ticket=await this.ticket(p,a.ticket),options=await this.resolveOptions(p,ticket.id,a.library_name,ticket);if(options.ticket_id!==ticket.id||options.company_id!==ticket.companyID||Date.parse(options.valid_until)<=this.now())throw new AppError('missing_metadata','Current checklist library options are incomplete or expired.');
  const matches=options.libraries.filter(v=>v.id===a.library_id&&normalize(v.name)===normalize(a.library_name));if(matches.length!==1)throw unavailable();const library=matches[0]!;const intent={ticket_id:ticket.id,company_id:ticket.companyID,library_id:library.id,library_name:library.name,item_count:library.item_count,fingerprint:library.fingerprint},payload={...intent,current_item_count:options.current_item_count};
  const prior=await this.prior(p,a.request_key,intent);if(prior)return this.view(prior);if(library.item_count<1)throw new AppError('precondition_failed','This checklist library has no items to apply.');if(library.item_count>options.remaining)throw new AppError('precondition_failed','The library would exceed the ticket checklist limit of 40 items.');
  const payloadHash=hash({definition:'ticket-checklist-library-apply-v1',actor:actorKey(p),mapping:p.mappingVersion,policy:p.policyVersion,payload:intent}),reserved=await this.core.journal.reserve({actorKey:actorKey(p),requestKey:a.request_key,payloadHash,operation:'ticket_checklist_library_apply',mappingVersion:p.mappingVersion,resourceId:p.resourceId,policyVersion:p.policyVersion,result:{...payload}});if(!reserved.created)return this.view(reserved.record);
  let state:JournalRecord['state']='ready',accepted=false;
  try{await this.core.journal.transition(reserved.record.id,'ready','dispatching',{...payload});state='dispatching';const beforeDispatch=async()=>{p=await this.current(p,true);const freshTicket=await this.ticket(p,{kind:'id',id:ticket.id}),fresh=await this.resolveOptions(p,ticket.id,a.library_name,freshTicket);if(freshTicket.companyID!==ticket.companyID||fresh.company_id!==ticket.companyID||Date.parse(fresh.valid_until)<=this.now())throw new AppError('precondition_failed','Ticket access or checklist library options changed before dispatch.');const selected=fresh.libraries.filter(v=>v.id===library.id&&normalize(v.name)===normalize(library.name));if(selected.length!==1||selected[0]!.fingerprint!==library.fingerprint||fresh.current_item_count!==options.current_item_count||selected[0]!.item_count<1||selected[0]!.item_count>fresh.remaining)throw new AppError('precondition_failed','The library or ticket checklist changed before dispatch. Refresh the options.');};const saved=await this.core.adapter.applyTicketChecklistLibrary(p,ticket.id,library.id,beforeDispatch);accepted=true;let record=await this.core.journal.transition(reserved.record.id,'dispatching','accepted_unverified',{...payload,association_id:saved.id,verification:{performed:false}});state='accepted_unverified';const after=await this.resolveOptions(p,ticket.id,a.library_name);const verified=after.ticket_id===ticket.id&&after.company_id===ticket.companyID&&after.current_item_count===options.current_item_count+library.item_count;if(verified)record=await this.core.journal.transition(record.id,'accepted_unverified','succeeded_verified',{...payload,association_id:saved.id,verification:{performed:true,complete:true,observed_item_count:after.current_item_count}});return this.view(record);
  }catch(error){const code=error instanceof AppError?error.code:'dependency_unavailable';const unknown=accepted||code==='unknown_outcome';try{await this.core.journal.transition(reserved.record.id,state,unknown?'unknown_outcome':'failed',{...payload,error_code:code,verification:{performed:false}});}catch{}const saved=await this.core.journal.get(reserved.record.id,actorKey(p));if(saved)return this.view(saved);throw error;}
 }
 async status(p:Principal,input:unknown){const a=z.object({operation_id:z.string().uuid()}).strict().parse(input);p=await this.current(p,false);const r=await this.core.journal.get(a.operation_id,actorKey(p));if(!r||r.operation!=='ticket_checklist_library_apply'||r.mappingVersion!==p.mappingVersion||r.resourceId!==p.resourceId||r.policyVersion!==p.policyVersion)throw unavailable();if(r.result?.ticket_id)await this.ticket(p,{kind:'id',id:Number(r.result.ticket_id)});return this.view(r);}
}
