import { classifyHistoryStatus } from './history-status.js';
import {createHash} from 'node:crypto';
import type {IntentCipher} from '../../storage/src/intent-cipher.js';
import type { OperationQualification } from '../../autotask/src/index.js';
import { AppError, actorKey, positiveId, type AutotaskPort, type DataRecord, type Principal, type PrincipalStore } from '../../contracts/src/index.js';
import { assertCapability, assertCompanyScope, projectRecord, reauthorize } from '../../policy/src/index.js';
import { assertReferenceCatalog, assertTechnicianMetadata, collectionRequestSchema, dateWindowSchema, domainProjectionFields, evidence, parseDomainInput, projectDomainRecord, referenceContextSchema, referenceKindSchema, revalidatePreparedUpdate, scopeOptions, timeEvidenceWindow, ownWorkRequestSchema } from './index.js';
import type { CollectionRequest, ContactReference, DateWindow, EvidenceCollection, OwnWorkEvidence, OwnWorkRequest, PortCollection, PreparedTicketUpdate, ReferenceCatalog, ReferenceContext, ReferenceKind, ResolvedContact, TechnicianMetadata, TechnicianPort } from './contracts.js';

export type TechnicianOperation = 'references.resolve'|'metadata.resolve'|'Tickets.patch.expanded'|'TicketHistory.query'|'TicketChecklistItems.query'|'ConfigurationItems.get'|'Contacts.get'|'CompanyLocations.get'|'Tasks.query'|'Tasks.get'|'Projects.get'|'TimeEntries.query.own';
export interface TechnicianQualification extends Omit<OperationQualification,'operation'> { operation:TechnicianOperation }
export interface TechnicianHttpRequest {
  operation:TechnicianOperation;
  method:'GET'|'POST'|'PATCH';
  /** Fixed relative routes generated by this adapter, never supplied by an MCP caller. */
  path:string;
  body?:Readonly<Record<string,unknown>>;
  /** Internal names authorized by domain preparation and rechecked by beforeDispatch. */
  validatedNativeFields?:readonly string[];
  /** Server-issued continuation; transport uses GET after validating the original query. */
  continuation?:string;
  /** The shared authenticated transport MUST call this after acquiring its dispatch slot.
   * It must preserve AppError definite/unknown semantics and never retry mutations. */
  beforeDispatch:()=>Promise<void>;
}
export interface TechnicianHttpTransport { request(p:Principal,request:TechnicianHttpRequest):Promise<unknown> }
export interface HttpTechnicianOptions {
  resolveTicketFields?:TechnicianPort['resolveTicketFields'];
  resolveWorkType?:TechnicianPort['resolveWorkType'];
  resolveIssuePair?:TechnicianPort['resolveIssuePair'];
  validateClassification?:TechnicianPort['validateClassification'];
  baseUrl?:string;
  cursorCipher?:IntentCipher;
  assertOpportunity?:(p:Principal,companyId:number,opportunityId:number)=>Promise<void>;
  transport?:TechnicianHttpTransport;
  applicationOperations?:{tenantId:string;operations:readonly TechnicianOperation[]};
  qualifications?:readonly TechnicianQualification[];
  /** Reviewed, permission-scoped providers. No tool-supplied metadata or global defaults. */
  resolveMetadata?:(p:Principal,ticketId:number)=>Promise<TechnicianMetadata>;
  resolveCatalog?:(p:Principal,kind:ReferenceKind,context:ReferenceContext)=>Promise<ReferenceCatalog>;
  resolveContact?:(p:Principal,companyId:number,reference:ContactReference)=>Promise<ResolvedContact>;
  now?:()=>number;
}
const invalidResponse=()=>new AppError('dependency_unavailable','The technician entity response is invalid.');
const object=(v:unknown):v is Record<string,unknown>=>v!==null&&typeof v==='object'&&!Array.isArray(v);
function row(value:unknown):DataRecord {if(!object(value)||!positiveId(value.id))throw invalidResponse();return value as DataRecord;}
function one(value:unknown):DataRecord {if(!object(value))throw invalidResponse();return row(value.item);}
function page(value:unknown):{items:DataRecord[];complete:boolean;next:string|null}{
  if(!object(value)||!Array.isArray(value.items)||value.items.length>1000||!object(value.pageDetails))throw invalidResponse();
  const next=value.pageDetails.nextPageUrl;if(next!==null&&typeof next!=='string')throw invalidResponse();
  return{items:value.items.map(row),complete:next===null,next};
}

/** Qualified contract only. A shared authenticated, bounded transport must be supplied
 * at deployment; this class creates no independent HTTP client or live qualifications. */
export class HttpTechnicianPort implements TechnicianPort {
  readonly source='Autotask' as const;
  constructor(readonly base:AutotaskPort,readonly principals:PrincipalStore,readonly options:HttpTechnicianOptions={}) {
    if(Boolean(options.baseUrl)!==Boolean(options.cursorCipher))throw new AppError('invalid_input','Workday pagination requires both the API base URL and cursor cipher.');
    if(base.source!=='Autotask')throw new AppError('invalid_input','Live technician operations require the live base adapter.');
  }
  private now(){return this.options.now?.()??Date.now();}
  private async actor(p:Principal,write=false){const fresh=await reauthorize(p,this.principals);assertCapability(fresh,'operational.read');if(write)assertCapability(fresh,'tickets.write');return fresh;}
  private qualify(p:Principal,operation:TechnicianOperation):void {
    if(this.options.applicationOperations?.tenantId===p.tenantId&&this.options.applicationOperations.operations.includes(operation))return;
    const now=this.now();const valid=this.options.qualifications?.some(q=>q.operation===operation&&q.evidenceSource==='live'&&q.headerAccepted===true&&q.permissionEnforced===true&&(operation!=='Tickets.patch.expanded'||q.nativeAttribution===true)&&q.tenantId===p.tenantId&&q.policyVersion===p.policyVersion&&q.resourceIds.includes(p.resourceId)&&q.testIds.length>0&&q.testIds.every(t=>typeof t==='string'&&t.trim().length>0)&&typeof q.evidenceReference==='string'&&q.evidenceReference.trim().length>0&&Number.isFinite(Date.parse(q.qualifiedAt))&&Date.parse(q.qualifiedAt)<=now&&Date.parse(q.expiresAt)>now);
    if(!valid)throw new AppError('impersonation_not_qualified','This technician operation has no current tenant, permission, and resource qualification.');
  }
  private async request(p:Principal,operation:TechnicianOperation,method:'GET'|'POST'|'PATCH',path:string,body?:Record<string,unknown>,guard?:()=>Promise<void>,continuation?:string,validatedNativeFields?:readonly string[]):Promise<unknown>{
    p=await this.actor(p,method==='PATCH');if(operation==='TimeEntries.query.own')assertCapability(p,'time.self');this.qualify(p,operation);if(!this.options.transport)throw new AppError('dependency_unavailable','The reviewed shared transport is not configured.');let dispatched=false;
    const beforeDispatch=async()=>{p=await this.actor(p,method==='PATCH');if(operation==='TimeEntries.query.own')assertCapability(p,'time.self');this.qualify(p,operation);if(guard)await guard();dispatched=true;};
    try{const result=await this.options.transport.request(p,{operation,method,path,...(validatedNativeFields?{validatedNativeFields}:{}),...(continuation?{continuation}:{}),...(body?{body:structuredClone(body)}:{}),beforeDispatch});if(!dispatched)throw new AppError(method==='PATCH'?'unknown_outcome':'dependency_unavailable','The transport did not provide the required dispatch guard.');return result;}
    catch(error){if(method==='PATCH'&&dispatched&&!(error instanceof AppError))throw new AppError('unknown_outcome','The ticket update outcome is unknown. Do not replay it.');throw error;}
  }
  private cursorBinding(p:Principal,query:unknown){return 'technician-cursor:v1:'+createHash('sha256').update(JSON.stringify([actorKey(p),p.resourceId,p.mappingVersion,p.policyVersion,[...p.companyIds].sort(),[...p.capabilities].sort(),query])).digest('hex');}
  private nativeCursor(value:string,path:string){
    let url:URL,base:URL;try{url=new URL(value);base=new URL(this.options.baseUrl!);}catch{throw invalidResponse();}
    if(url.origin!==base.origin||url.pathname!==base.pathname+path+'/next'||url.username||url.password||url.hash||[...url.searchParams.keys()].length!==1||!url.searchParams.get('paging')||value.length>8000)throw invalidResponse();
    return url.href;
  }
  private openCursor(p:Principal,query:unknown,cursor?:string):string|undefined{
    if(!cursor)return undefined;
    if(!this.options.cursorCipher)throw new AppError('invalid_input','Workday continuation is not configured.');
    let value:unknown;try{value=this.options.cursorCipher.open(cursor,this.cursorBinding(p,query));}catch{throw new AppError('invalid_input','Workday cursor is invalid or belongs to another employee, date or query.');}
    if(!object(value)||typeof value.next!=='string'||typeof value.expires!=='number'||value.expires<=this.now())throw new AppError('invalid_input','Workday cursor is invalid or expired.');
    return value.next;
  }
  private sealCursor(p:Principal,query:unknown,next:string|null){return next&&this.options.cursorCipher?this.options.cursorCipher.seal({next,expires:this.now()+300_000},this.cursorBinding(p,query)):null;}
  private async queryPages(p:Principal,operation:TechnicianOperation,path:string,body:Record<string,unknown>,maxPages:number,cursor?:string,scope?:unknown){
    const query={operation,path,body,scope};let next=this.openCursor(p,query,cursor),complete=false;const items:DataRecord[]=[],ids=new Set<number>(),seen=new Set<string>();
    for(let i=0;i<maxPages;i++){
      if(next){next=this.nativeCursor(next,path);if(seen.has(next))throw invalidResponse();seen.add(next);}
      const result=page(await this.request(p,operation,'POST',path,body,undefined,next));
      if(result.items.length>100||result.items.some(r=>ids.has(r.id))||new Set(result.items.map(r=>r.id)).size!==result.items.length)throw invalidResponse();
      for(const item of result.items){ids.add(item.id);items.push(item);}
      complete=result.complete;next=result.next??undefined;if(complete)break;
      if(!result.items.length)throw invalidResponse();
      if(!this.options.cursorCipher||!this.options.baseUrl)break;
      next=this.nativeCursor(next!,path);
    }
    return {items,complete,continuation:this.sealCursor(p,query,next??null)};
  }
  async resolveTicketFields(...args:Parameters<NonNullable<TechnicianPort['resolveTicketFields']>>){if(!this.options.resolveTicketFields)throw new AppError('unsupported_operation','Native ticket updates are not configured.');return this.options.resolveTicketFields(...args);}
  async resolveWorkType(...args:Parameters<NonNullable<TechnicianPort['resolveWorkType']>>){if(!this.options.resolveWorkType)throw new AppError('unsupported_operation','Work type updates are not configured.');return this.options.resolveWorkType(...args);}
  async resolveIssuePair(p:Principal,ticketId:number,issue:number|string|undefined,sub:number|string|null|undefined){if(!this.options.resolveIssuePair)throw new AppError('unsupported_operation','Issue classification updates are not configured.');return this.options.resolveIssuePair(p,ticketId,issue,sub);}
  async validateClassification(p:Principal,ticketId:number,selection:{categoryId:number;queueId:number|null;workTypeId?:number|null},override?:string){if(this.options.validateClassification)await this.options.validateClassification(p,ticketId,selection,override);}
  async assertOpportunity(p:Principal,companyId:number,opportunityId:number){p=await this.actor(p,true);if(!this.options.assertOpportunity)throw new AppError('unsupported_operation','Opportunity linking is unavailable.');await this.options.assertOpportunity(p,companyId,opportunityId);}
  async resolveContact(p:Principal,companyId:number,reference:ContactReference):Promise<ResolvedContact>{p=await this.actor(p);if(!this.options.resolveContact)throw new AppError('unsupported_operation','Contact linking is unavailable.');const result=await this.options.resolveContact(p,companyId,reference);p=await this.actor(p);if(!result||!positiveId(result.id)||result.active!==true||result.companyId===undefined)throw new AppError('dependency_unavailable','The contact resolver returned an invalid record.');return structuredClone(result);}
  async getTicket(p:Principal,ticketId:number):Promise<DataRecord>{p=await this.actor(p);if(!positiveId(ticketId))throw new AppError('invalid_input','Invalid ticket identifier.');const ticket=await this.base.get(p,'Tickets',ticketId);assertCompanyScope(p,ticket.companyID);return ticket;}
  async findTicket(p:Principal,ticketNumber:string):Promise<DataRecord>{p=await this.actor(p);if(typeof ticketNumber!=='string'||!ticketNumber.trim()||ticketNumber.length>100)throw new AppError('invalid_input','Invalid ticket number.');const result=await this.base.query(p,{entity:'Tickets',filters:[{field:'ticketNumber',op:'eq',value:ticketNumber},{field:'companyID',op:'in',value:p.companyIds}],pageSize:2});const rows=result.items.filter(t=>p.companyIds.includes(t.companyID as number)&&t.ticketNumber===ticketNumber);if(rows.length!==1||result.nextCursor)throw new AppError('not_found_or_inaccessible','The ticket was not found or is inaccessible.');return this.getTicket(p,rows[0]!.id);}
  async metadata(p:Principal,ticketId:number):Promise<TechnicianMetadata>{p=await this.actor(p);this.qualify(p,'metadata.resolve');const ticket=await this.getTicket(p,ticketId);if(!this.options.resolveMetadata)throw new AppError('missing_metadata','The reviewed technician metadata provider is not configured.');const m=await this.options.resolveMetadata(p,ticketId);p=await this.actor(p);this.qualify(p,'metadata.resolve');assertTechnicianMetadata(m,p,ticket,this.source,this.now());return structuredClone(m);}
  async catalog(p:Principal,kind:ReferenceKind,context:ReferenceContext={}):Promise<ReferenceCatalog>{
    p=await this.actor(p);kind=parseDomainInput(referenceKindSchema,kind);context=parseDomainInput(referenceContextSchema,context);this.qualify(p,'references.resolve');
    if(context.ticketId!==undefined){const ticket=await this.getTicket(p,context.ticketId);if(context.companyId!==undefined&&context.companyId!==ticket.companyID)throw new AppError('not_found_or_inaccessible','The context is inaccessible.');context={...context,companyId:ticket.companyID as number};}
    if(context.companyId!==undefined)assertCompanyScope(p,context.companyId);if(!this.options.resolveCatalog)throw new AppError('missing_metadata','The reviewed reference provider is not configured.');
    const catalog=await this.options.resolveCatalog(p,kind,context);p=await this.actor(p);this.qualify(p,'references.resolve');assertReferenceCatalog(catalog,p,kind,this.source,this.now());return{...structuredClone(catalog),items:structuredClone(scopeOptions(catalog.items,p,context))};
  }
  async collection(p:Principal,ticketId:number,name:PortCollection,request:CollectionRequest={}):Promise<EvidenceCollection>{
    p=await this.actor(p);request=parseDomainInput(collectionRequestSchema,request);if(!Object.hasOwn(domainProjectionFields,name))throw new AppError('invalid_input','Unknown collection.');const ticket=await this.getTicket(p,ticketId);
    if(request.cursor)throw new AppError('invalid_input','A continuation is not qualified for this collection.');if(request.window&&name!=='history')throw new AppError('invalid_input','Only history supports a date window.');
    const scope=`ticket:${ticketId}:${name}`;
    const parentGuard=async()=>{const fresh=await this.getTicket(p,ticketId);if(fresh.companyID!==ticket.companyID||(name==='assets'&&fresh.configurationItemID!==ticket.configurationItemID)||(name==='contact'&&fresh.contactID!==ticket.contactID)||(name==='site'&&fresh.companylocationID!==ticket.companylocationID))throw new AppError('precondition_failed','The ticket parent or association changed.');};
    let rows:DataRecord[];let complete=true;
    if(name==='site'){
      if(ticket.companylocationID===undefined||ticket.companylocationID===null)return evidence([],scope,null,{warnings:['No site is linked to this ticket; a visit address has not been inferred.']});
      if(!positiveId(ticket.companylocationID))throw invalidResponse();
      const item=one(await this.request(p,'CompanyLocations.get','GET',`CompanyLocations/${ticket.companylocationID}`,undefined,parentGuard));
      assertCompanyScope(p,item.companyID);if(item.companyID!==ticket.companyID||item.id!==ticket.companylocationID)throw invalidResponse();rows=[item];
    }else if(name==='contact'){
      if(ticket.contactID===undefined||ticket.contactID===null)return evidence([],scope);
      if(!positiveId(ticket.contactID))throw invalidResponse();
      const item=one(await this.request(p,'Contacts.get','GET',`Contacts/${ticket.contactID}`,undefined,parentGuard));
      const company=await this.base.get(p,'Companies',ticket.companyID as number);const parent=company.parentCompanyID;
      const allowed=[ticket.companyID,...(positiveId(parent)&&parent!==ticket.companyID&&p.companyIds.includes(parent)?[parent]:[])];
      if(!allowed.includes(item.companyID as number)||item.id!==ticket.contactID)throw invalidResponse();rows=[item];
    }else if(name==='assets'){
      if(ticket.configurationItemID===undefined||ticket.configurationItemID===null)return evidence([],scope);
      if(!positiveId(ticket.configurationItemID))throw invalidResponse();const item=one(await this.request(p,'ConfigurationItems.get','GET',`ConfigurationItems/${ticket.configurationItemID}`,undefined,parentGuard));
      assertCompanyScope(p,item.companyID);if(item.companyID!==ticket.companyID||item.id!==ticket.configurationItemID)throw invalidResponse();rows=[item];
    }else if(name==='checklist'){
      const result=page(await this.request(p,'TicketChecklistItems.query','POST','TicketChecklistItems/query',{filter:[{op:'eq',field:'ticketID',value:ticketId}]},parentGuard));
      if(result.items.some(r=>r.ticketID!==ticketId))throw invalidResponse();rows=result.items;complete=result.complete;
    }else{
      // TicketHistory supports a single ticketID equality filter only. No server-side
      // date filter or direct pagination URL is invented; windows apply after retrieval.
      const result=page(await this.request(p,'TicketHistory.query','POST','TicketHistory/query',{filter:[{op:'eq',field:'ticketID',value:ticketId}],...((request.limit??100)>100?{MaxRecords:500}:{})},parentGuard));
      if(result.items.some(r=>r.ticketID!==ticketId))throw invalidResponse();rows=result.items;complete=result.complete;
      rows=rows.map(classifyHistoryStatus);
      if(request.window)rows=rows.filter(r=>!Number.isFinite(Date.parse(String(r.date)))||(Date.parse(String(r.date))>=Date.parse(request.window!.start)&&Date.parse(String(r.date))<Date.parse(request.window!.end)));
    }
    await parentGuard();await this.actor(p);
    const limit=request.limit??100;complete=complete&&rows.length<=limit;rows=rows.slice(0,limit).map(r=>projectDomainRecord(r,domainProjectionFields[name]));
    return evidence(rows,scope,request.window??null,{status:complete?'complete':'partial',complete_within_scope:complete,warnings:[...(name==='history'?['Unclassified history detail is withheld.']:[]),...(!complete?['The collection is incomplete; continuation is not qualified.']:[])]});
  }
  async getTask(p:Principal,taskId:number):Promise<{task:DataRecord;companyId:number}>{p=await this.actor(p);if(!positiveId(taskId))throw new AppError('invalid_input','Invalid task identifier.');const task=one(await this.request(p,'Tasks.get','GET',`Tasks/${taskId}`));if(task.id!==taskId||!positiveId(task.projectID))throw invalidResponse();const project=one(await this.request(p,'Projects.get','GET',`Projects/${task.projectID}`));if(project.id!==task.projectID)throw invalidResponse();assertCompanyScope(p,project.companyID);return{task,companyId:project.companyID as number};}
  async ownWork(p:Principal,window:DateWindow,workDate?:string,request:OwnWorkRequest={}):Promise<OwnWorkEvidence>{
    const paging=parseDomainInput(ownWorkRequestSchema,request);
    p=await this.actor(p);window=parseDomainInput(dateWindowSchema,window);const timeWindow=timeEvidenceWindow(window,workDate);
    const assignedQuery={entity:'Tickets' as const,filters:[{field:'companyID',op:'in' as const,value:p.companyIds},{field:'assignedResourceID',op:'eq' as const,value:p.resourceId}],pageSize:100};
    const binding={assignedQuery,window,workDate};let assignedNext=this.openCursor(p,binding,paging.cursors?.assigned_tickets);const assignedItems:DataRecord[]=[],assignedIds=new Set<number>();
    for(let i=0;i<paging.max_pages;i++){
      const batch=await this.base.query(p,{...assignedQuery,...(assignedNext?{cursor:assignedNext}:{})});
      for(const item of batch.items){if(assignedIds.has(item.id))throw invalidResponse();assignedIds.add(item.id);assignedItems.push(item);}
      assignedNext=batch.nextCursor??undefined;if(!assignedNext)break;
    }
    const assigned={items:assignedItems,nextCursor:assignedNext,continuation:this.sealCursor(p,binding,assignedNext??null)};
    const tickets:DataRecord[]=[];for(const t of assigned.items){assertCompanyScope(p,t.companyID);if(t.assignedResourceID!==p.resourceId)throw invalidResponse();const m=await this.metadata(p,t.id);const state=m.options.status.find(s=>s.id===t.status);if(!state)throw new AppError('missing_metadata','Ticket status meaning is unavailable.');if(!state.completed)tickets.push(projectRecord('Tickets',t,p));}
    const raw=await this.queryPages(p,'Tasks.query','Tasks/query',{filter:[{op:'eq',field:'assignedResourceID',value:p.resourceId},{op:'lt',field:'startDateTime',value:window.end},{op:'gte',field:'endDateTime',value:window.start}],MaxRecords:100},paging.max_pages,paging.cursors?.tasks);
    const tasks:DataRecord[]=[];const projects=new Map<number,DataRecord>();
    for(const task of raw.items){if(task.assignedResourceID!==p.resourceId||!positiveId(task.projectID))throw invalidResponse();let project=projects.get(task.projectID);if(!project){try{project=one(await this.request(p,'Projects.get','GET',`Projects/${task.projectID}`));}catch(error){if(error instanceof AppError&&error.code==='not_found_or_inaccessible')continue;throw error;}if(project.id!==task.projectID)throw invalidResponse();projects.set(task.projectID,project);}if(!p.companyIds.includes(project.companyID as number))continue;if(typeof task.startDateTime!=='string'||typeof task.endDateTime!=='string'||Date.parse(task.startDateTime)>=Date.parse(window.end)||Date.parse(task.endDateTime)<Date.parse(window.start))throw invalidResponse();tasks.push(projectDomainRecord(task,['id','projectID','assignedResourceID','assignedResourceRoleID','title','status','startDateTime','endDateTime']));}
    const actual=await this.queryPages(p,'TimeEntries.query.own','TimeEntries/query',{filter:[{field:'resourceID',op:'eq',value:p.resourceId},{field:'dateWorked',op:'gte',value:timeWindow.start},{field:'dateWorked',op:'lt',value:timeWindow.end}],MaxRecords:100},paging.max_pages,paging.cursors?.time,{window,workDate});
    const time:DataRecord[]=[];let timeComplete=actual.complete;
    for(const t of actual.items){if(typeof t.hoursWorked!=='number'||!Number.isFinite(t.hoursWorked)||t.hoursWorked<=0||t.hoursWorked>24||t.resourceID!==p.resourceId||typeof t.dateWorked!=='string'||!Number.isFinite(Date.parse(t.dateWorked))||Date.parse(t.dateWorked)<Date.parse(timeWindow.start)||Date.parse(t.dateWorked)>=Date.parse(timeWindow.end))throw invalidResponse();
      try{if(positiveId(t.ticketID))await this.getTicket(p,t.ticketID);else if(positiveId(t.taskID)){const task=one(await this.request(p,'Tasks.get','GET',`Tasks/${t.taskID}`));if(task.id!==t.taskID||!positiveId(task.projectID))throw invalidResponse();const project=one(await this.request(p,'Projects.get','GET',`Projects/${task.projectID}`));if(project.id!==task.projectID)throw invalidResponse();assertCompanyScope(p,project.companyID);}else if(!((t.ticketID===null||t.ticketID===undefined)&&(t.taskID===null||t.taskID===undefined)))throw invalidResponse();}catch(error){if(error instanceof AppError&&error.code==='not_found_or_inaccessible')continue;throw error;}time.push(projectRecord('TimeEntries',t,p));}
    p=await this.actor(p);return{assigned_tickets:evidence(tickets,`resource:${p.resourceId}:currently-assigned-open-tickets`,null,{status:assigned.nextCursor?'partial':'complete',complete_within_scope:!assigned.nextCursor,continuation:assigned.continuation,warnings:assigned.nextCursor?['Assigned-ticket evidence is incomplete.']:[]}),tasks:evidence(tasks,`resource:${p.resourceId}:assigned-tasks-overlapping-window`,window,{status:raw.complete?'complete':'partial',complete_within_scope:raw.complete,continuation:raw.continuation,warnings:raw.complete?[]:['Task evidence is incomplete.']}),time:evidence(time,`resource:${p.resourceId}:authorized-ticket-task-and-internal-time-in-window`,timeWindow,{status:timeComplete?'complete':'partial',complete_within_scope:timeComplete,continuation:actual.continuation,warnings:timeComplete?[]:['Recorded-time evidence is incomplete; follow its continuation before reporting a full total.']})};
  }
  async patchTicket(p:Principal,plan:PreparedTicketUpdate):Promise<void>{
    p=await this.actor(p,true);this.qualify(p,'Tickets.patch.expanded');const fresh=await revalidatePreparedUpdate(this,this.principals,p,plan);
    const result=await this.request(p,'Tickets.patch.expanded','PATCH','Tickets',{id:fresh.ticketId,...fresh.changes},async()=>{await revalidatePreparedUpdate(this,this.principals,p,fresh);},undefined,Object.keys(fresh.changes));
    if(!object(result)||result.itemId!==fresh.ticketId)throw new AppError('unknown_outcome','The expanded ticket update acknowledgement could not be verified. Do not replay it.');
  }
}
