import {withReconciliation} from '../../execution/src/index.js';
import {personIdentitySchema,ownerIdentitySchema} from '../../contracts/src/person-identity.js';
import { assertArea } from '../../policy/src/areas.js';
import {ticketFinancialGuidance} from '../../authoring/src/ticket-financial-guidance.js';
import {statusGuidance} from '../../authoring/src/status-guidance.js';
import {classificationGuidance,classificationOverrideSchema} from '../../classification/src/index.js';
import {createHash} from 'node:crypto';
import {z} from 'zod';
import {AppError,actorKey,positiveId,type Principal,type JournalRecord} from '../../contracts/src/index.js';
import {reauthorize,assertCapability,assertCompanyScope} from '../../policy/src/index.js';
import {IntentCipher} from '../../storage/src/intent-cipher.js';
import type {TicketWorkflows} from '../../workflows/src/index.js';
import {canonicalCompanyName} from '../../workflows/src/company-aliases.js';
import type {HttpAutotaskAdapter} from '../../autotask/src/index.js';
import type {OperationalMetadata} from './metadata.js';
export const ticketCreationFields={due_datetime:'dueDateTime',company:'companyID',queue:'queueID',priority:'priority',requester:'contactID',role:'assignedResourceRoleID',category:'ticketCategory',ticket_type:'ticketType',title:'title',description:'description',issue_type:'issueType',sub_issue_type:'subIssueType'} as const;
export const ticketCreationGuidance=ticketFinancialGuidance+' '+statusGuidance+' '+classificationGuidance+' '+'Address every ticket creation field: due date, client, queue, priority, requester, role, ticket category, ticket type, title, description, issue type and sub-issue type. Infer omitted details from the user request, chat, linked records and current tenant choices; prefer explicit user facts over inferred values and tenant defaults. Requester means the client contact (contact_id), not the assigned employee. Use only authorized, active and compatible choices; never invent IDs or identities. For contact_id supply contact_identity with the intended full name or email from the user request; for a numeric owner supply owner_identity. Resolve IDs against current directory data and retain the intended identity even if an ID disagrees. Prefer owner self or an exact full name. Creation assumptions are not identity verification. Infer owner from context when selecting a role; a role requires an eligible owner. When copying a ticket, explicitly preserve its assignedResourceID as owner and assignedResourceRoleID as role when eligible; do not replace a known original role with an employee default. Distinguish fields unsupported by this tool from fields proven read-only by live metadata; never describe source as system-managed merely because it is not an accepted input. Use ticket_create_options for missing choices, without repeating reads already available in context. Create with valid known/inferred/default values; do not block on optional unknown details. Provide creation_assumptions for contextual inferences. After verified creation, show the ticket title/ID and selected values, disclose assumptions and unresolved fields, and ask for adjustments then. If a native required field or client identity cannot be resolved safely, obtain only that prerequisite before creation. Never describe an uncertain write as created or retry it with a new key.';
const id=z.number().int().positive().safe(), choice=z.union([id,z.string().trim().min(1).max(250)]);
export const ticketCreateSchema=z.object({contact_identity:personIdentitySchema.optional(),owner_identity:ownerIdentitySchema.optional(),classification_override:classificationOverrideSchema.optional(),company:z.union([z.number().int().nonnegative().safe(),z.string().trim().min(1).max(250)]),title:z.string().trim().min(1).max(255),description:z.string().max(32000).optional(),priority:choice,queue:choice,status:choice.optional().describe('Select the current tenant status matching actual progress. Supply In Progress or its equivalent when substantive work has already started and remains unfinished; New is the fallback for work not yet started.'),category:choice.optional(),ticket_type:choice.optional(),issue_type:choice.optional(),sub_issue_type:choice.optional(),owner:z.union([id,z.literal('self'),z.string().trim().min(1).max(250)]).optional(),role:choice.optional(),work_type:choice.optional(),due_datetime:z.string().datetime({offset:true}),opportunity_id:id.optional(),contact_id:id.optional().describe('Requester: resolved active client contact ID. Requires contact_identity with the intended full name or email; never reuse an unrelated ID.'),creation_assumptions:z.array(z.string().trim().min(1).max(1000)).max(20).optional().describe('Disclose contextual inferences to the user after creation; never send these as ticket fields.'),request_key:z.string().min(8).max(128).refine(v=>!/^(wf:|sch:|job:)/.test(v))}).strict();
export type TicketCreateInput=z.infer<typeof ticketCreateSchema>;
const canonical=(v:any):string=>Array.isArray(v)?`[${v.map(canonical)}]`:v&&typeof v==='object'?`{${Object.keys(v).sort().map(k=>`${JSON.stringify(k)}:${canonical(v[k])}`).join(',')}}`:JSON.stringify(v);
const hash=(v:unknown)=>createHash('sha256').update(canonical(v)).digest('hex');
const absent=()=>new AppError('not_found_or_inaccessible','Ticket creation receipt unavailable.');
export class TicketCreation {
 constructor(private core:TicketWorkflows,private adapter:HttpAutotaskAdapter,private metadata:OperationalMetadata,private cipher:IntentCipher){}
 private async actor(p:Principal,write=false){p=await reauthorize(p,this.core.principals,{resourceMaxAgeMs:240000});assertCapability(p,'operational.read');assertArea(p,'tickets',write);if(write)assertCapability(p,'tickets.write');return p;}
 private binding(p:Principal,key:string,digest:string){return `${actorKey(p)}:${p.mappingVersion}:${p.resourceId}:${p.policyVersion}:${key}:${digest}`;}
 private async company(p:Principal,value:string|number){if(typeof value==='number'){assertCompanyScope(p,value);await this.core.adapter.get(p,'Companies',value);return value;}const name=canonicalCompanyName(value);const page=await this.core.adapter.query(p,{entity:'Companies',filters:[{field:'companyName',op:'contains',value:name}],pageSize:100});const exact=page.items.filter(r=>String(r.companyName).toLowerCase()===name.toLowerCase());const matches=exact.length?exact:page.items;if(page.nextCursor||matches.length!==1)throw new AppError('invalid_input','Choose an unambiguous company name or ID.');assertCompanyScope(p,matches[0]!.id);return matches[0]!.id;}
 async create(p:Principal,input:unknown){const a=ticketCreateSchema.parse(input);p=await this.actor(p,true);const payloadHash=hash({input:a,actor:actorKey(p),mapping:p.mappingVersion,resource:p.resourceId,policy:p.policyVersion,companies:p.companyIds});const prior=await this.core.journal.find(actorKey(p),a.request_key);if(prior){if(prior.operation!=='ticket_create'||prior.payloadHash!==payloadHash)throw new AppError('conflict','Request key belongs to another operation or input.');return this.status(p,prior.id);}
  const companyId=await this.company(p,a.company),body=await this.metadata.prepareTicketCreate(p,{...a,company:companyId});
  const reserved=await this.core.journal.reserve({actorKey:actorKey(p),requestKey:a.request_key,payloadHash,operation:'ticket_create',mappingVersion:p.mappingVersion,resourceId:p.resourceId,policyVersion:p.policyVersion,encryptedIntent:this.cipher.seal({body,assumptions:[...(a.creation_assumptions??[]),...(a.classification_override?[`User classification override: ${a.classification_override}`]:[])],defaulted_fields:Object.entries(ticketCreationFields).filter(([field,native])=>body[native]!==undefined&&((a as Record<string,unknown>)[field==='requester'?'contact_id':field]===undefined||(field==='description'&&!a.description?.trim()))).map(([field])=>field)},this.binding(p,a.request_key,payloadHash)),intentExpiresAt:new Date(Date.now()+7*86400000).toISOString(),result:{company_id:companyId}});if(!reserved.created)return this.status(p,reserved.record.id);
  let state:JournalRecord['state']='ready',nativeId:number|undefined;
  try{await this.core.journal.transition(reserved.record.id,'ready','dispatching');state='dispatching';const saved=await this.adapter.createTicket(p,body,async()=>{await this.actor(p,true);const current=await this.metadata.prepareTicketCreate(p,{...a,company:companyId});if(canonical(current)!==canonical(body))throw new AppError('conflict','Ticket defaults or opportunity association changed before dispatch.');});nativeId=saved.id;
   await this.core.journal.transition(reserved.record.id,state,'accepted_unverified',{company_id:companyId,ticket_id:nativeId});state='accepted_unverified';return await withReconciliation(()=>this.status(p,reserved.record.id));
  }catch(e){const definite=e instanceof AppError&&['invalid_input','forbidden','not_found_or_inaccessible','conflict','precondition_failed','missing_metadata','identity_mapping_invalid','identity_validation_unavailable','throttled'].includes(e.code);if(state==='dispatching')try{await this.core.journal.transition(reserved.record.id,state,definite?'failed':'unknown_outcome',{company_id:companyId,...(nativeId?{ticket_id:nativeId}:{}),error_code:e instanceof AppError?e.code:'dependency_unavailable'});}catch{}
   try{return await this.status(p,reserved.record.id);}catch{return{status:'unknown_outcome',operation_id:reserved.record.id,safe_to_redispatch:false};}
  }
 }
 async status(p:Principal,id:string){p=await this.actor(p);let r=await this.core.journal.get(id,actorKey(p));if(!r||r.operation!=='ticket_create')throw absent();if(r.mappingVersion!==p.mappingVersion||r.resourceId!==p.resourceId||r.policyVersion!==p.policyVersion)throw absent();assertCompanyScope(p,r.result?.company_id);
  if(positiveId(r.result?.ticket_id)&&r.encryptedIntent&&r.intentExpiresAt&&Date.parse(r.intentExpiresAt)>Date.now()&&['accepted_unverified','unknown_outcome'].includes(r.state)){
   const {body}=this.cipher.open(r.encryptedIntent,this.binding(p,r.requestKey,r.payloadHash)) as {body:Record<string,unknown>};
   try{const row=await this.core.adapter.get(p,'Tickets',r.result.ticket_id);if(row.companyID!==r.result.company_id)throw absent();const matches=Object.entries(body).every(([k,v])=>k==='dueDateTime'?typeof row[k]==='string'&&Date.parse(row[k])===Date.parse(v as string):canonical(row[k]??null)===canonical(v));if(matches){await this.actor(p);r=await this.core.journal.transition(r.id,r.state,'succeeded_verified',{...r.result,verified:true});}}catch{/* A failed read cannot authorize another creation. */}
  }
  // Return the original verified snapshot from encrypted intent, never plaintext journal storage.
  // This is what was verified at creation, not a claim about subsequent external edits.
  let verifiedSavedFields:Record<string,unknown>|undefined;let creationReview:{assumptions:string[];defaulted_fields:string[];unresolved_fields:string[]}|undefined;
  if(r.state==='succeeded_verified'&&r.encryptedIntent&&r.intentExpiresAt&&Date.parse(r.intentExpiresAt)>Date.now()){
   try{const saved=this.cipher.open(r.encryptedIntent,this.binding(p,r.requestKey,r.payloadHash)) as {body:Record<string,unknown>;assumptions?:string[];defaulted_fields?:string[]};verifiedSavedFields=saved.body;creationReview={assumptions:saved.assumptions??[],defaulted_fields:saved.defaulted_fields??[],unresolved_fields:Object.entries(ticketCreationFields).filter(([,native])=>saved.body[native]===undefined||saved.body[native]===null||saved.body[native]==='').map(([field])=>field)};}catch{/* Receipt remains valid if its encrypted snapshot is unavailable. */}
  }
  return{status:r.state,operation_id:r.id,data:r.result,...(verifiedSavedFields?{verified_saved_fields:verifiedSavedFields,creation_review:creationReview,verified_saved_fields_scope:'Original fields verified at creation; not current state after later edits.'}:{}),safe_to_redispatch:false,can_resume:false,receipt:r.state==='succeeded_verified'?'Ticket created and supplied fields verified. No Won Quote conversion was performed.':r.state==='failed'?'Ticket creation was rejected.':'Ticket creation is unverified or uncertain. Inspect this operation before any retry.'};
 }
}
