#!/usr/bin/env python3
"""Build planning coverage from factual API observations; no live account access."""
import json,pathlib,collections,re
R=pathlib.Path(__file__).resolve().parents[1]
rmm=json.loads((R/'rmm-endpoints.json').read_text());itg=json.loads((R/'itglue-endpoints.json').read_text())
def phase(o,provider):
 m=o['method'];p=o['path']
 if provider=='rmm':
  if 'resetApiKeys' in p:return 'excluded','Credential reset is operator-only; not an assistant tool.'
  if '/quickjob' in p:return 'P3','Reviewed component execution with durable job tracking.'
  if any(x in p for x in ['/variable','/proxy','/account/users','/activity-logs','/dnet-site-mappings']):return 'P4','Account administration or potentially secret-bearing fields; separate capability.'
  if m!='GET':return 'P3','Explicit operational write with scope and outcome verification.'
  return 'P1','Scoped device, site, audit, alert, patch or job context.'
 res=o['resource']
 if res in ['Passwords','Password Folders','Password Categories']:return 'P4','Separate secret-access design and key configuration; no generic secret propagation.'
 if res in ['Exports','Groups','Resource Accesses','Users','User Metrics','Logs']:return 'P4','Account-wide, access-control, audit or bulk-export scope; separate operator capability.'
 if m=='DELETE':return 'P4','Destructive operation deferred beyond initial delivery.'
 if res in ['Configuration Types','Configuration Statuses','Contact Types','Flexible Asset Fields','Flexible Asset Types','Manufacturers','Models','Organization Statuses','Organization Types'] and m!='GET':return 'P4','Schema/reference administration changes are separate from document authoring.'
 if m=='GET':return 'P1','Scoped documentation/reference retrieval; protect included relationships.'
 return 'P2','Explicit documentation/asset write; verify source-of-truth and parent relationships.'
coverage=[]
for provider,ops in [('rmm',rmm),('itglue',itg)]:
 for o in ops:
  ph,why=phase(o,provider)
  coverage.append({'provider':provider,'method':o['method'],'path':o['path'],'resource':o.get('resource',','.join(o.get('tags',[]))),'phase':ph,'disposition':why,'documentation_group':o.get('documentation_group'),'source':o.get('source_url',o.get('source')),'native_access':'not_checked','live_tested':False})
(R/'endpoint-coverage.json').write_text(json.dumps(coverage,indent=2)+'\n')
lines=['# Complete captured endpoint inventory','', 'Generated by `scripts/build_inventory.py`. Counts describe the captured documentation, not enabled MCP tools. IT Glue includes top-level and organization-scoped aliases. Every route has a planned disposition; later phases are not commitments to expose every endpoint.','', 'RMM: 59 operations, 55 paths, 118 schemas. IT Glue: 209 route declarations across 37 resources.','', 'P1 = reads; P2 = documentation writes; P3 = RMM actions; P4 = separately scoped administration/secrets/deletions.','', '| Provider | Resource | Method | Route | Phase |', '| --- | --- | --- | --- | --- |']
for o in coverage:lines.append(f"| {o['provider']} | {o['resource']} | {o['method']} | `{o['path']}` | {o['phase']} |")
(R/'API-INVENTORY.md').write_text('\n'.join(lines)+'\n')
# Curated user-facing tool design. Multiple routes intentionally share one constrained tool.
def route(m,p):return {'method':m,'path':p}
tools=[]
def add(name,provider,phase,args,routes,purpose):
 tools.append({'name':name,'provider':provider,'phase':phase,'arguments':args,'native_routes':[route(*x) for x in routes],'purpose':purpose,'status':'proposed_not_registered'})
add('rmm_site_search','rmm','P1',['company','page_size','cursor'],[('GET','/v2/account/sites')],'Resolve authorized sites using verified company mappings; apply name search locally only when explicitly labelled.')
add('rmm_site_get','rmm','P1',['company','site_uid'],[('GET','/v2/site/{siteUid}')],'Read projected site details; no proxy secrets.')
add('rmm_device_search','rmm','P1',['company','site_uid?','hostname?','page_size','cursor'],[('GET','/v2/site/{siteUid}/devices')],'Find scoped devices; never claim a hostname is a server-side filter without schema support.')
add('rmm_device_get','rmm','P1',['company','device_uid'],[('GET','/v2/device/{deviceUid}')],'Read identity, last-seen, last-audit and available status evidence.')
add('rmm_device_audit_get','rmm','P1',['company','device_uid','kind:device|printer|esxihost'],[('GET','/v2/audit/device/{deviceUid}'),('GET','/v2/audit/printer/{deviceUid}'),('GET','/v2/audit/esxihost/{deviceUid}')],'Retrieve the matching device-class audit with timestamps; reject mismatched class.')
add('rmm_software_search','rmm','P1',['company','device_uid','name?','page_size','cursor'],[('GET','/v2/audit/device/{deviceUid}/software')],'Read audited software; installed software does not prove use or cloud-consent activity.')
add('rmm_alert_search','rmm','P1',['company','site_uid?','device_uid?','state:open|resolved','page_size','cursor'],[('GET','/v2/site/{siteUid}/alerts/open'),('GET','/v2/site/{siteUid}/alerts/resolved'),('GET','/v2/device/{deviceUid}/alerts/open'),('GET','/v2/device/{deviceUid}/alerts/resolved')],'Find alerts in exactly the requested scope/state.')
add('rmm_alert_get','rmm','P1',['company','alert_uid'],[('GET','/v2/alert/{alertUid}')],'Verify alert device/site before returning evidence.')
add('rmm_patch_search','rmm','P1',['company','site_uid?','device_uid?','page_size','cursor'],[('GET','/v2/site/{siteUid}/patches'),('GET','/v2/device/{deviceUid}/patches')],'Read native patch records; no inferred patch approval or installation action.')
add('rmm_component_search','rmm','P1',['name?','page_size','cursor'],[('GET','/v2/account/components')],'Return locally approved catalog entries, not unrestricted executable components.')
add('rmm_job_get','rmm','P1',['company','job_uid','device_uid'],[('GET','/v2/job/{jobUid}'),('GET','/v2/job/{jobUid}/results/{deviceUid}')],'Read a job with proven device scope; job completion is not business success.')
add('rmm_job_output_get','rmm','P1',['company','job_uid','device_uid','stream:stdout|stderr','offset','length'],[('GET','/v2/job/{jobUid}/results/{deviceUid}/stdout'),('GET','/v2/job/{jobUid}/results/{deviceUid}/stderr')],'Return bounded, sanitized untrusted output after scope checks.')
add('rmm_quickjob_run','rmm','P3',['company','device_uid','component_uid','job_name','variables','request_key'],[('PUT','/v2/device/{deviceUid}/quickjob')],'Execute one reviewed existing component on one verified device; receipt stores native job UID.')
for action in ['resolve','mute','unmute']:
 add('rmm_alert_'+action,'rmm','P3',['company','alert_uid','expected','request_key'],[('POST','/v2/alert/{alertUid}/'+action)],'Explicit alert state change; does not prove remediation.')
add('rmm_device_udf_update','rmm','P3',['company','device_uid','fields','expected','request_key'],[('POST','/v2/device/{deviceUid}/udf')],'Change reviewed UDF fields only, preserving native semantics.')
add('rmm_device_warranty_update','rmm','P3',['company','device_uid','warranty','expected','request_key'],[('POST','/v2/device/{deviceUid}/warranty')],'Save supplied warranty facts using exact native request schema.')
for name,res,path in [('organization','Organizations','organizations'),('configuration','Configurations','configurations'),('contact','Contacts','contacts'),('flexible_asset','Flexible Assets','flexible_assets')]:
 add('itg_'+name+'_search','itglue','P1',['company','filters','page_size','cursor'],[('GET','/'+path)],'Resolve organization scope; expose only documented filters and permitted fields.')
 add('itg_'+name+'_get','itglue','P1',['company','id'],[('GET','/'+path+'/:id')],'Validate parent organization and project included relationships before returning.')
add('itg_document_search','itglue','P1',['company','folder_id?','all_folders','page_size','cursor'],[('GET','/organizations/:organization_id/relationships/documents')],'Distinguish root-folder default from explicit all-folder retrieval.')
add('itg_document_get','itglue','P1',['company','document_id'],[('GET','/documents/:id'),('GET','/documents/:document_id/relationships/sections')],'Read document with sections as untrusted content; sanitize HTML.')
add('itg_checklist_search','itglue','P1',['company','filters','page_size','cursor'],[('GET','/organizations/:organization_id/relationships/checklists')],'Retrieve existing checklists; no undocumented task-completion endpoint.')
add('itg_checklist_get','itglue','P1',['company','id'],[('GET','/checklists/:id')],'Read permitted task relationships and native checklist state.')
add('itg_document_create','itglue','P2',['company','folder_id?','name','sections','request_key'],[('POST','/documents'),('POST','/documents/:document_id/relationships/sections')],'Multi-step draft creation; publish only through a separately requested action.')
add('itg_document_update','itglue','P2',['company','document_id','fields','expected','request_key'],[('PATCH','/documents/:id')],'Preserve sections and formatting through exact reviewed fields.')
add('itg_document_section_update','itglue','P2',['company','document_id','section_id','fields','expected','request_key'],[('PATCH','/documents/:document_id/relationships/sections/:id')],'Validate section type and parent; do not overwrite unrelated sections.')
add('itg_document_publish','itglue','P2',['company','document_id','expected','request_key'],[('PATCH','/documents/:id/publish')],'Native document publishing is explicit; never infer public sharing.')
for name,path in [('flexible_asset','flexible_assets'),('configuration','configurations')]:
 for action,method,suffix in [('create','POST',''),('update','PATCH','/:id')]:
  add('itg_'+name+'_'+action,'itglue','P2',['company','id?','fields','expected?','request_key'],[(method,'/'+path+suffix)],'Check source-of-truth ownership and field/relationship schema before writes.')
add('itg_checklist_update','itglue','P2',['company','id','fields','expected','request_key'],[('PATCH','/checklists/:id')],'Only documented checklist attributes; no promise of creating or completing individual tasks.')
(R/'proposed-tools.json').write_text(json.dumps(tools,indent=2)+'\n')
lines=['# Proposed MCP tool contracts','', 'These are design inputs, not registered tools or final JSON Schemas. `?` indicates an optional argument. Endpoint catalogs retain method/path observations and source URLs. Consult the vendor source for exact native types, required fields and schemas; copied descriptions/examples are excluded. Common authorization, cursor, receipt and output contracts are defined in IMPLEMENTATION-PLAN.md.','', '| Proposed tool | Phase | Arguments | Native route(s) |', '| --- | --- | --- | --- |']
for o in tools:lines.append('| '+o['name']+' | '+o['phase']+' | '+', '.join(o['arguments'])+' | '+'; '.join('`'+r['method']+' '+r['path']+'`' for r in o['native_routes'])+' |')
(R/'TOOL-CONTRACTS.md').write_text('\n'.join(lines)+'\n')
print(json.dumps({'coverage':len(coverage),'proposed_tools':len(tools),'phases':dict(collections.Counter(o['phase'] for o in coverage))}))
