import {z} from 'zod';
import type {Principal} from '../../contracts/src/index.js';
import * as c from './contracts.js';
import {BusinessService} from './index.js';

const entityPrefix:Partial<Record<c.BusinessEntity,string>>={CompanyToDos:'crm_todo',Contracts:'contract',ContractServices:'contract_service',ContractBlocks:'contract_block',ContractCharges:'contract_charge',ContractServiceAdjustments:'contract_service_adjustment',ContractServiceBundleAdjustments:'contract_service_bundle_adjustment',ContractServiceBundleUnits:'contract_service_bundle_unit',ContractServiceUnits:'contract_service_unit',Invoices:'invoice',Projects:'project',Phases:'phase',Tasks:'task',TaskPredecessors:'task_predecessor',ProjectNotes:'project_note',TaskNotes:'task_note',ConfigurationItems:'asset',ConfigurationItemDnsRecords:'asset_dns_record',ConfigurationItemNotes:'asset_note',Subscriptions:'subscription',Products:'product',InventoryProducts:'inventory_product',InventoryItems:'inventory_item',InventoryStockedItems:'inventory_stocked_item',InventoryStockedItemsAdd:'inventory_add',InventoryStockedItemsRemove:'inventory_remove',InventoryStockedItemsTransfer:'inventory_transfer',InventoryTransfers:'inventory_transfer_record',PurchaseOrders:'purchase_order',PurchaseOrderItems:'purchase_order_item',PurchaseOrderItemReceiving:'purchase_receipt'};
export const businessToolDefinitions:Record<string,{entity:c.BusinessEntity;action:'search'|'get'|'create'|'update'|'delete'}>={};
const commandOnly=new Set<c.BusinessEntity>(['InventoryStockedItemsAdd','InventoryStockedItemsRemove','InventoryStockedItemsTransfer']);
const writeOnly=new Set<c.BusinessEntity>(['ContractServiceAdjustments','ContractServiceBundleAdjustments',...commandOnly]);
for(const entity of c.businessEntities){const prefix=entityPrefix[entity]!;if(!commandOnly.has(entity)&&!writeOnly.has(entity)){businessToolDefinitions[`${prefix}_search`]={entity,action:'search'};businessToolDefinitions[`${prefix}_get`]={entity,action:'get'};}for(const action of c.documentedWrites[entity]??[])businessToolDefinitions[`${prefix}_${action}`]={entity,action};}
export const businessOperations:Record<string,{write:boolean;capabilities:string[]}>=Object.fromEntries([...Object.entries(businessToolDefinitions).map(([name,v])=>[name,{write:['create','update','delete'].includes(v.action),capabilities:['operational.read','finance.read',...(v.action!=='search'&&v.action!=='get'?['finance.write',v.entity==='CompanyToDos'?'sales.write':v.entity.startsWith('Contract')||v.entity==='Invoices'?'finance.write':v.entity.startsWith('Project')||['Phases','Tasks','TaskPredecessors','ProjectNotes','TaskNotes'].includes(v.entity)?'projects.write':v.entity.startsWith('Inventory')||['Products','PurchaseOrders','PurchaseOrderItems','PurchaseOrderItemReceiving'].includes(v.entity)?'procurement.write':'configuration.write']:[])]}]),...['business_schema','business_operation_status','contract_context','project_context','invoice_context','invoice_export','billing_true_up'].map(name=>[name,{write:false,capabilities:['operational.read','finance.read']}])]);

const schemaFor=(action:string)=>action==='search'?c.searchSchema:action==='get'?c.getSchema:action==='create'?c.createSchema:action==='update'?c.updateSchema:c.deleteSchema;
const parentArgument:Partial<Record<c.BusinessEntity,string>>={ContractServices:'contract_id',ContractBlocks:'contract_id',ContractCharges:'contract_id',ContractServiceAdjustments:'contract_id',ContractServiceBundleAdjustments:'contract_id',ContractServiceBundleUnits:'contract_id',ContractServiceUnits:'contract_id',Phases:'project_id',Tasks:'project_id',TaskPredecessors:'task_id',ProjectNotes:'project_id',TaskNotes:'task_id',ConfigurationItemDnsRecords:'configuration_item_id',ConfigurationItemNotes:'configuration_item_id',Subscriptions:'configuration_item_id',PurchaseOrderItems:'purchase_order_id',PurchaseOrderItemReceiving:'purchase_order_item_id'};
const catalogEntities=new Set<c.BusinessEntity>(['Products','InventoryProducts','InventoryItems','InventoryTransfers']);
const commandFieldHint:Partial<Record<c.BusinessEntity,string>>={InventoryStockedItemsAdd:'quantityBeingAdded',InventoryStockedItemsRemove:'quantityBeingRemoved',InventoryStockedItemsTransfer:'quantityBeingTransferred'};
const description=(entity:c.BusinessEntity,action:string)=>`${entity==='CompanyToDos'?'CRM to-do: completedDate marks completion; there is no isComplete field. Search preserves owner and completion filters; no open-only default. Create requires explicit assignedToResourceID, actionType, startDateTime and endDateTime from business_schema. Delete requires expected companyID, activityDescription, assignedToResourceID, startDateTime, endDateTime and completedDate. ':''}${['ProjectNotes','TaskNotes'].includes(entity)?'Supply publish and noteType explicitly from business_schema; do not guess audience or set contact authorship. Parent changes and note deletion are unavailable. ':''}${action==='search'?`For a known native ID use ${entityPrefix[entity]}_get with id. ${c.searchIdAlias[entity]?`This search also accepts ${c.searchIdAlias[entity]} as an exact record ID; required parent filters still apply. `:''}${c.searchTextField[entity]?`text searches ${c.searchTextField[entity]} only, not the native ID. `:'Text search is unavailable. '}`:''}${action} ${entity} through its documented Autotask REST route. Updates accept native editable fields from current tenant metadata, including userDefinedFields name/value pairs; read business_schema and the record first. Autotask read-only and create-only restrictions apply; company and parent scope are checked.${parentArgument[entity]?` Supply ${parentArgument[entity]} to scope this child operation.`:''}${catalogEntities.has(entity)?' This tenant catalog entity has no company field; company filters are unavailable.':''}${commandFieldHint[entity]?` This is a write-only command; use native ${commandFieldHint[entity]} and expect accepted_unverified because no get route is documented.`:''}${writeOnly.has(entity)&&!commandFieldHint[entity]?' This is write-only because no get route is documented.':''} Writes require a stable request_key and expected values for updates. Never repeat an accepted_unverified or unknown_outcome mutation under a new key.`;

export function businessTools(s:BusinessService){
  const generated=Object.entries(businessToolDefinitions).map(([name,v])=>({name,schema:v.action==='search'?c.searchSchemaFor(v.entity):schemaFor(v.action),description:description(v.entity,v.action),write:['create','update','delete'].includes(v.action),destructive:['update','delete'].includes(v.action),idempotent:true,run:async(p:Principal,a:unknown)=>v.action==='search'?s.search(p,v.entity,a):v.action==='get'?s.get(p,v.entity,a):s.write(p,v.entity,v.action,a)}));
  return [...generated,
    {name:'business_schema',schema:c.schemaSchema,description:'Read current metadata for one reviewed business entity and its allowed fields. No write is performed.',run:(p:Principal,a:unknown)=>s.schema(p,a)},
    {name:'business_operation_status',schema:c.receiptSchema,description:'Read a business write receipt and verify a known native ID when possible. Never retries a write.',run:(p:Principal,a:unknown)=>s.operationStatus(p,a)},
    {name:'contract_context',schema:z.object({id:c.id}).strict(),description:'Read a contract and its bounded service, block, charge and unit collections. Service adjustment routes are write-only in the captured API contract.',run:(p:Principal,a:unknown)=>s.contractContext(p,a)},
    {name:'project_context',schema:z.object({id:c.id}).strict(),description:'Read a project and bounded phases and tasks with independent completeness markers.',run:(p:Principal,a:unknown)=>s.projectContext(p,a)},
    {name:'invoice_context',schema:z.object({id:c.id}).strict(),description:'Read an invoice header and authorized financial fields. Posting, approval and customer delivery are not performed.',run:(p:Principal,a:unknown)=>s.invoiceContext(p,a)},
    {name:'invoice_export',schema:c.invoiceExportSchema,description:'Read the documented Invoices/{id}/InvoicePdf rendering for an authorized invoice. This is a read export and does not post, approve or send.',run:(p:Principal,a:unknown)=>s.invoiceExport(p,a)},
    {name:'billing_true_up',schema:z.object({contract_id:c.id,page_size:z.number().int().min(1).max(100).default(50)}).strict(),description:'Read contract services and effective-dated units to identify quantity evidence. It does not calculate or apply a billing adjustment; adjustment endpoints have no captured read route.',run:(p:Principal,a:unknown)=>s.trueUp(p,a)},
  ];
}
