BEGIN;
ALTER TABLE operation_journal DROP CONSTRAINT IF EXISTS operation_journal_intent_check;
ALTER TABLE operation_journal ADD CONSTRAINT operation_journal_intent_check CHECK (
 (encrypted_intent IS NULL AND intent_expires_at IS NULL)
 OR (encrypted_intent IS NOT NULL AND intent_expires_at IS NOT NULL AND isfinite(intent_expires_at)
 AND operation IN ('business_configurationitemdnsrecords_delete','business_configurationitemnotes_create','business_configurationitemnotes_update','business_configurationitems_create','business_configurationitems_update','business_contractblocks_create','business_contractblocks_update','business_contractcharges_create','business_contractcharges_update','business_contracts_create','business_contracts_update','business_contractserviceadjustments_create','business_contractservicebundleadjustments_create','business_contractservices_create','business_contractservices_update','business_inventoryitems_create','business_inventoryitems_update','business_inventoryproducts_create','business_inventoryproducts_delete','business_inventoryproducts_update','business_inventorystockeditemsadd_create','business_inventorystockeditemsremove_create','business_inventorystockeditemstransfer_create','business_inventorytransfers_create','business_invoices_update','business_phases_create','business_phases_update','business_products_create','business_products_update','business_projects_create','business_projects_update','business_purchaseorderitemreceiving_create','business_purchaseorderitems_create','business_purchaseorderitems_update','business_purchaseorders_create','business_purchaseorders_update','business_subscriptions_delete','business_subscriptions_update','business_taskpredecessors_create','business_taskpredecessors_delete','business_taskpredecessors_update','business_tasks_create','business_tasks_update','checklist_item_create','checklist_item_delete','checklist_item_update','expense_item_add','expense_report_create','expense_report_submit','resource_availability_update','sales_companynotes_create','sales_opportunities_create','sales_opportunities_update','sales_quoteitems_create','sales_quoteitems_delete','sales_quoteitems_update','sales_quotelocations_create','sales_quotes_create','sales_quotes_update','service_call_cancel','service_call_create','service_call_update','opportunity_attachment_upload','opportunity_attachment_delete','ticket_attachment_delete','ticket_attachment_upload','ticket_create','ticket_update','ticket_document_work','ticket_handoff','ticket_resolve','time_correct','time_delete','time_log_internal','time_log_task','time_log_ticket','time_off_cancel','time_off_request')
 AND length(encrypted_intent) <= 174806
 AND encrypted_intent ~ '^v1\.[A-Za-z0-9_-]{16}\.[A-Za-z0-9_-]+\.[A-Za-z0-9_-]{22}$')
);
ALTER TABLE artifact_catalog DROP CONSTRAINT IF EXISTS artifact_catalog_check1;
ALTER TABLE artifact_catalog ADD CONSTRAINT artifact_catalog_check1 CHECK (COALESCE((jsonb_typeof(record)='object' AND record->>'id'=id::text AND record->>'actorKey'=actor_key AND record->>'state'=state
    AND record ?& ARRAY['id','actorKey','resourceId','mappingVersion','policyVersion','scopeHash','companyId','kind','collection','mime','bytes','sha256','createdAt','expiresAt','state','source','complete','rows','references']
    AND (record->>'bytes')::bigint=byte_length AND jsonb_array_length(record->'references') BETWEEN 1 AND 1001
    AND (record->>'resourceId')::bigint BETWEEN 1 AND 9007199254740991 AND (record->>'mappingVersion')::bigint BETWEEN 1 AND 9007199254740991
    AND (((record ? 'ticketId') AND NOT (record ? 'opportunityId') AND (record->>'ticketId')::bigint BETWEEN 1 AND 9007199254740991) OR ((record ? 'opportunityId') AND NOT (record ? 'ticketId') AND (record->>'opportunityId')::bigint BETWEEN 1 AND 9007199254740991 AND record->>'kind'='staged_upload' AND record->>'collection'='upload' AND record->>'source'='client_upload' AND jsonb_array_length(record->'references')=1 AND record->'references'->0->>'entity'='Opportunities' AND record->'references'->0->>'id'=record->>'opportunityId')) AND (record->>'companyId')::bigint BETWEEN 0 AND 9007199254740991
    AND record->>'scopeHash' ~ '^[a-f0-9]{64}$' AND record->>'sha256' ~ '^[a-f0-9]{64}$'
    AND record->>'kind' IN ('csv','staged_upload') AND record->>'source' IN ('fixture','Autotask','client_upload')
    AND (record->>'createdAt')::timestamptz=created_at AND (record->>'expiresAt')::timestamptz=expires_at),false));
INSERT INTO schema_migrations(version) VALUES('012_opportunity_attachments') ON CONFLICT DO NOTHING;
COMMIT;
