import { AppError, type DataRecord, type Principal, type PrincipalStore } from '../../contracts/src/index.js';
import { assertCapability, reauthorize } from '../../policy/src/index.js';
import type { Availability, BillingApprovalLevel, ExpenseItem, ExpenseReport, TimeEntry, TimeOffApprover, TimeOffRequest, WorkManagementPort } from './contracts.js';

export interface FixtureWorkManagementRecords { time: TimeEntry[]; billingApprovals: BillingApprovalLevel[]; reports: ExpenseReport[]; items: ExpenseItem[]; availability: Availability; timeOff: TimeOffRequest[]; approvers: TimeOffApprover[]; tasks: DataRecord[] }
export function fixtureWorkManagementRecords(): FixtureWorkManagementRecords { return { time: [], billingApprovals: [], reports: [], items: [], availability: { id: 9001, resourceID: 101, mondayAvailableHours: 8, tuesdayAvailableHours: 8, wednesdayAvailableHours: 8, thursdayAvailableHours: 8, fridayAvailableHours: 8, saturdayAvailableHours: 0, sundayAvailableHours: 0, weeklyBillableHoursGoal: 40 }, timeOff: [], approvers: [], tasks: [{ id: 3001, projectID: 2001, assignedResourceID: 101, assignedResourceRoleID: 501, billingCodeID: 601, status: 1 } ] }; }

/** Fictitious records for policy and recovery tests. No network requests occur. */
export class FixtureWorkManagementPort implements WorkManagementPort {
  readonly source = 'fixture' as const; readonly calls: { operation: string; resourceId: number }[] = []; readonly records: FixtureWorkManagementRecords;
  constructor(private readonly principals: PrincipalStore, records?: Partial<FixtureWorkManagementRecords>) { this.records = { ...fixtureWorkManagementRecords(), ...structuredClone(records) } as FixtureWorkManagementRecords; }
  private async current(p: Principal, write = false, capability: 'time.self'|'time.approve'|'expenses.write'|'scheduling.write' = 'time.self') { const fresh = await reauthorize(p, this.principals, { resourceMaxAgeMs: 300_000 }); assertCapability(fresh, 'operational.read'); if (write) assertCapability(fresh, capability); return fresh; }
  private hit(p: Principal, operation: string) { this.calls.push({ operation, resourceId: p.resourceId }); }
  async searchTime(p: Principal, input: { scope: 'ticket'|'task'|'internal'|'all'; parentId?: number; resourceId: number; from?: string; to?: string; pageSize: number; cursor?: string }) { p = await this.current(p); if(input.scope==='all'||input.resourceId!==p.resourceId&&input.resourceId!==0)assertCapability(p,'time.approve'); this.hit(p, 'TimeEntries.query'); let rows = this.records.time.filter(r => (input.resourceId === 0 || r.resourceID === input.resourceId) && (input.scope === 'ticket' ? r.ticketID === input.parentId : input.scope === 'task' ? r.taskID === input.parentId : input.scope === 'internal' ? (r.ticketID === undefined || r.ticketID === null) && (r.taskID === undefined || r.taskID === null) : true)); if (input.from) rows = rows.filter(r => r.dateWorked >= `${input.from}T00:00:00`); if (input.to) rows = rows.filter(r => r.dateWorked <= `${input.to}T23:59:59.999`); const after = input.cursor ? Number(input.cursor) : 0; rows = rows.filter(r => r.id > after).sort((a,b) => a.id-b.id); const page = rows.slice(0, input.pageSize); return { items: structuredClone(page), nextCursor: rows.length > page.length ? String(page.at(-1)!.id) : null, complete: true, fetchedAt: new Date().toISOString() }; }
  async searchBillingApprovals(p:Principal,timeEntryId:number){p=await this.current(p);assertCapability(p,'time.approve');this.hit(p,'BillingItemApprovalLevels.query');return structuredClone(this.records.billingApprovals.filter(r=>r.timeEntryID===timeEntryId));}
  async getBillingApproval(p:Principal,id:number){p=await this.current(p);assertCapability(p,'time.approve');const row=this.records.billingApprovals.find(r=>r.id===id);if(!row)throw new AppError('not_found_or_inaccessible','Billing approval not found.');this.hit(p,'BillingItemApprovalLevels.get');return structuredClone(row);}
  async createBillingApproval(p:Principal,payload:{timeEntryID:number;approvalLevel:number;approvalResourceID:number;approvalDateTime:string},beforeDispatch?:()=>Promise<void>){p=await this.current(p,true,'time.approve');if(payload.approvalResourceID!==p.resourceId)throw new AppError('forbidden','The approval actor changed.');if(beforeDispatch)await beforeDispatch();const id=Math.max(5000,...this.records.billingApprovals.map(r=>r.id))+1;this.records.billingApprovals.push({...structuredClone(payload),id});const time=this.records.time.find(r=>r.id===payload.timeEntryID);if(time)time.billingApprovalLevelMostRecent=payload.approvalLevel;this.hit(p,'BillingItemApprovalLevels.create');return{id};}
  async getTime(p: Principal, id: number) { p = await this.current(p); this.hit(p, 'TimeEntries.get'); const row = this.records.time.find(r => r.id === id); if (!row) throw new AppError('not_found_or_inaccessible', 'Time entry not found or inaccessible.'); return structuredClone(row); }
  async createTime(p: Principal, payload: Record<string, unknown>, beforeDispatch?: () => Promise<void>) { p = await this.current(p, true); if (beforeDispatch) await beforeDispatch(); const id = Math.max(1000, ...this.records.time.map(r=>r.id)) + 1; this.records.time.push({ ...structuredClone(payload), id } as TimeEntry); this.hit(p, 'TimeEntries.create'); return { id }; }
  async updateTime(p: Principal, id: number, changes: Record<string, unknown>, beforeDispatch?: () => Promise<void>) { p = await this.current(p, true); const row = this.records.time.find(r => r.id === id); if (!row) throw new AppError('not_found_or_inaccessible', 'Time entry not found or inaccessible.'); if (beforeDispatch) await beforeDispatch(); Object.assign(row, structuredClone(changes)); this.hit(p, 'TimeEntries.update'); return { id }; }
  async deleteTime(p: Principal, id: number, beforeDispatch?: () => Promise<void>) { p = await this.current(p, true); const i = this.records.time.findIndex(r=>r.id===id); if (i<0) throw new AppError('not_found_or_inaccessible','Time entry not found or inaccessible.'); if (beforeDispatch) await beforeDispatch(); this.records.time.splice(i,1); this.hit(p,'TimeEntries.delete'); }
  async getTask(p: Principal, id: number) { p = await this.current(p); const row = this.records.tasks.find(r=>r.id===id); if (!row) throw new AppError('not_found_or_inaccessible','Task not found or inaccessible.'); this.hit(p,'Tasks.get'); return structuredClone(row); }
  async getProject(p: Principal, id: number) { p = await this.current(p); if (id !== 2001) throw new AppError('not_found_or_inaccessible','Project not found or inaccessible.'); this.hit(p,'Projects.get'); return { id, companyID: 10 }; }
  async getExpenseReport(p: Principal, id: number) { p = await this.current(p); const row = this.records.reports.find(r=>r.id===id); if (!row || row.submitterID!==p.resourceId) throw new AppError('not_found_or_inaccessible','Expense report not found or inaccessible.'); this.hit(p,'ExpenseReports.get'); return structuredClone(row); }
  async getExpenseItem(p: Principal, id: number) { p = await this.current(p); const row = this.records.items.find(r=>r.id===id); if (!row) throw new AppError('not_found_or_inaccessible','Expense item not found or inaccessible.'); const report = this.records.reports.find(r=>r.id===row.expenseReportID); if (!report || report.submitterID!==p.resourceId) throw new AppError('not_found_or_inaccessible','Expense item not found or inaccessible.'); this.hit(p,'ExpenseItems.get'); return structuredClone(row); }
  async createExpenseReport(p: Principal, payload: Record<string, unknown>, beforeDispatch?: () => Promise<void>) { p = await this.current(p,true,'expenses.write'); if (beforeDispatch) await beforeDispatch(); const id=Math.max(2000,...this.records.reports.map(r=>r.id))+1; this.records.reports.push({...structuredClone(payload),id,status:1} as ExpenseReport); this.hit(p,'ExpenseReports.create'); return {id}; }
  async createExpenseItem(p: Principal, reportId: number, payload: Record<string, unknown>, beforeDispatch?: () => Promise<void>) { p = await this.current(p,true,'expenses.write'); await this.getExpenseReport(p,reportId); if (beforeDispatch) await beforeDispatch(); const id=Math.max(3000,...this.records.items.map(r=>r.id))+1; this.records.items.push({...structuredClone(payload),id} as ExpenseItem); this.hit(p,'ExpenseItems.create'); return {id}; }
  async updateExpenseReport(p: Principal, id: number, changes: Record<string, unknown>, beforeDispatch?: () => Promise<void>) { p = await this.current(p,true,'expenses.write'); const row=this.records.reports.find(r=>r.id===id); if (!row || row.submitterID!==p.resourceId) throw new AppError('not_found_or_inaccessible','Expense report not found or inaccessible.'); if (beforeDispatch) await beforeDispatch(); if (changes.submit===true) row.status=2; Object.assign(row,structuredClone(changes)); this.hit(p,'ExpenseReports.update'); return {id}; }
  async getAvailability(p: Principal) { p=await this.current(p); if(this.records.availability.resourceID!==p.resourceId) throw new AppError('not_found_or_inaccessible','Availability not found or inaccessible.'); this.hit(p,'ResourceDailyAvailabilities.get'); return structuredClone(this.records.availability); }
  async updateAvailability(p: Principal,id:number,changes:Record<string,unknown>) { p=await this.current(p,true,'scheduling.write'); if(id!==this.records.availability.id||this.records.availability.resourceID!==p.resourceId) throw new AppError('conflict','Availability changed.'); Object.assign(this.records.availability,structuredClone(changes)); this.hit(p,'ResourceDailyAvailabilities.update'); return {id}; }
  async searchTimeOff(p: Principal,input:{resourceId:number;from?:string;to?:string;pageSize:number;cursor?:string}) { p=await this.current(p);if(input.resourceId!==p.resourceId)assertCapability(p,'time.approve'); this.hit(p,'TimeOffRequests.query'); let rows=this.records.timeOff.filter(r=>r.resourceID===input.resourceId); if(input.from)rows=rows.filter(r=>r.requestDate>=input.from!);if(input.to)rows=rows.filter(r=>r.requestDate<=`${input.to}T23:59:59.999`);const after=input.cursor?Number(input.cursor):0;rows=rows.filter(r=>r.id>after);const page=rows.slice(0,input.pageSize);return {items:structuredClone(page),nextCursor:rows.length>page.length?String(page.at(-1)!.id):null,complete:true,fetchedAt:new Date().toISOString()}; }
  async searchTimeOffApprovers(p:Principal,input:{approverId?:number;resourceId?:number;pageSize:number;cursor?:string}){p=await this.current(p);assertCapability(p,'time.approve');if(input.approverId!==undefined&&input.approverId!==p.resourceId)throw new AppError('forbidden','Only the current approver can be selected.');this.hit(p,'ResourceTimeOffApprovers.query');const rows=this.records.approvers.filter(r=>(input.approverId===undefined||r.approverResourceID===input.approverId)&&(input.resourceId===undefined||r.resourceID===input.resourceId)).sort((a,b)=>a.id-b.id).filter(r=>r.id>Number(input.cursor??0));const page=rows.slice(0,input.pageSize);return{items:structuredClone(page),nextCursor:rows.length>page.length?String(page.at(-1)!.id):null,complete:true,fetchedAt:new Date().toISOString()};}
  async approveTimeOff(p:Principal,id:number,beforeDispatch?:()=>Promise<void>){p=await this.current(p,true,'time.approve');if(beforeDispatch)await beforeDispatch();const row=this.records.timeOff.find(r=>r.id===id);if(!row)throw new AppError('not_found_or_inaccessible','Time-off request not found.');const levels=this.records.approvers.filter(a=>a.resourceID===row.resourceID).map(a=>a.approvalLevel);const next=Math.min(...levels.filter(level=>level>(row.lastApprovedLevel??0)));row.lastApprovedLevel=next;row.approveRejectResourceID=p.resourceId;if(next===Math.max(...levels))row.status=2;this.hit(p,'TimeOffRequestsApprove.create');return{id};}
  async rejectTimeOff(p:Principal,id:number,reason:string,beforeDispatch?:()=>Promise<void>){p=await this.current(p,true,'time.approve');if(beforeDispatch)await beforeDispatch();const row=this.records.timeOff.find(r=>r.id===id);if(!row)throw new AppError('not_found_or_inaccessible','Time-off request not found.');row.status=4;row.rejectReason=reason;row.approveRejectResourceID=p.resourceId;this.hit(p,'TimeOffRequestsReject.create');return{id};}
  async createTimeOff(p: Principal,payload:Record<string,unknown>,beforeDispatch?: () => Promise<void>) { p=await this.current(p,true,'scheduling.write'); if (beforeDispatch) await beforeDispatch(); const id=Math.max(4000,...this.records.timeOff.map(r=>r.id))+1;this.records.timeOff.push({...structuredClone(payload),id} as TimeOffRequest);this.hit(p,'TimeOffRequests.create');return {id}; }
  async updateTimeOff(p: Principal,id:number,changes:Record<string,unknown>,beforeDispatch?: () => Promise<void>) { p=await this.current(p,true,'scheduling.write');const row=this.records.timeOff.find(r=>r.id===id);if(!row||row.resourceID!==p.resourceId)throw new AppError('not_found_or_inaccessible','Time-off request not found or inaccessible.'); if (beforeDispatch) await beforeDispatch();Object.assign(row,structuredClone(changes));this.hit(p,'TimeOffRequests.update');return {id}; }
  async getTimeOff(p: Principal,id:number) { p=await this.current(p);const row=this.records.timeOff.find(r=>r.id===id);if(!row||row.resourceID!==p.resourceId&&!p.capabilities.includes('time.approve'))throw new AppError('not_found_or_inaccessible','Time-off request not found or inaccessible.');this.hit(p,'TimeOffRequests.get');return structuredClone(row); }
}
