import {withReconciliation} from '../../execution/src/index.js';
import { assertArea, assertOperationArea } from '../../policy/src/areas.js';
import { createHash, randomUUID } from 'node:crypto';
import { AppError, actorKey, type JournalRecord, type Principal } from '../../contracts/src/index.js';
import { assertCapability, assertCompanyScope, reauthorize } from '../../policy/src/index.js';
import type { IntentCipher } from '../../storage/src/intent-cipher.js';
import type { TicketWorkflows } from '../../workflows/src/index.js';
import * as c from './contracts.js';
export * from './contracts.js';
export * from './http.js';
export * from './fixtures.js';
export * from './tools.js';

const canonical = (v: unknown): string => Array.isArray(v) ? `[${v.map(canonical).join(',')}]` : v && typeof v === 'object' ? `{${Object.keys(v as object).sort().map(k => `${JSON.stringify(k)}:${canonical((v as Record<string, unknown>)[k])}`).join(',')}}` : JSON.stringify(v);
const hash = (v: unknown) => createHash('sha256').update(canonical(v)).digest('hex');
const absent = () => new AppError('not_found_or_inaccessible', 'The work record was not found or is inaccessible.');
const definitive = new Set(['invalid_input','forbidden','not_found_or_inaccessible','missing_metadata','precondition_failed','conflict','throttled','unsupported_operation']);

export interface WorkManagementOptions { now?: () => number; identityMaxAgeMs?: number; validateTime?: (principal: Principal, payload: Readonly<Record<string, unknown>>) => Promise<boolean>; validateExpense?: (principal: Principal, payload: Readonly<Record<string, unknown>>) => Promise<boolean>; validateTimeOff?: (principal: Principal, payload: Readonly<Record<string, unknown>>) => Promise<boolean>; resolveExpenseStatuses?: (principal: Principal) => Promise<{ inProgress: number; rejected: number; submitted?: number }>; resolveTimeOffStatuses?: (principal: Principal) => Promise<{ submitted: number; canceled: number; approved?: number; rejected?: number }>; }

/** Fixed time, expense, availability and time-off workflows. The port owns
 * server-reviewed metadata and fixed HTTP routes; clients never choose routes,
 * actor headers, or arbitrary fields. */
export class WorkManagementService {
  constructor(private readonly core: TicketWorkflows, readonly port: c.WorkManagementPort, private readonly cipher: IntentCipher, private readonly options: WorkManagementOptions = {}) {}
  private now() { return this.options.now?.() ?? Date.now(); }
  private async current(input: Principal, capability: 'read'|'time'|'expenses'|'scheduling' = 'read') {
    const p = await reauthorize(input, this.core.principals, { resourceMaxAgeMs: this.options.identityMaxAgeMs ?? 300_000, now: () => new Date(this.now()) });
    assertCapability(p, 'operational.read');
    if (capability === 'time') { assertArea(p,'time',true); assertCapability(p, 'time.self'); }
    if (capability === 'expenses') assertCapability(p, 'expenses.write');
    if (capability === 'scheduling') assertCapability(p, 'scheduling.write');
    return p;
  }
  private async timeRowScope(p: Principal, row: c.TimeEntry) {
    if (typeof row.ticketID === 'number') await this.core.resolveTicket(p, { kind: 'id', id: row.ticketID });
    if (typeof row.taskID === 'number') { assertArea(p,'projects');
      const task = await this.port.getTask(p, row.taskID);
      if (typeof task.companyID === 'number') assertCompanyScope(p, task.companyID);
      else if (typeof task.projectID === 'number') {
        const project = await this.port.getProject(p, task.projectID);
        if (typeof project.companyID !== 'number') throw absent();
        assertCompanyScope(p, project.companyID);
      } else throw absent();
    }
  }
  private async ownTime(p: Principal, id: number) { const row = await this.port.getTime(p, id); if (row.resourceID !== p.resourceId) throw absent(); await this.timeRowScope(p, row); return row; }
  private async parentScope(p: Principal, kind: 'ticket'|'task'|'internal', input: Record<string, unknown>) { if (kind === 'ticket') { await this.core.resolveTicket(p, { kind: 'id', id: Number(input.ticket_id) }); } else if (kind === 'task') { assertArea(p,'projects'); const task = await this.port.getTask(p, Number(input.task_id)); if (typeof task.companyID === 'number') assertCompanyScope(p, task.companyID); else if (typeof task.projectID === 'number') { const project = await this.port.getProject(p, task.projectID); if (typeof project.companyID !== 'number') throw absent(); assertCompanyScope(p, project.companyID); } else throw absent(); } }
  private async validateTime(p: Principal, payload: Record<string, unknown>) { if (!this.options.validateTime) { if (this.port.source === 'fixture') return; throw new AppError('missing_metadata', 'Reviewed time-entry eligibility is unavailable.'); } let valid: unknown; try { valid = await this.options.validateTime(structuredClone(p), Object.freeze(structuredClone(payload))); } catch { throw new AppError('dependency_unavailable', 'Time-entry eligibility could not be verified.'); } if (valid !== true) throw new AppError('precondition_failed', 'The proposed time-entry fields are not currently eligible.'); }
  private async validateTimeOff(p: Principal, payload: Record<string, unknown>) { if (!this.options.validateTimeOff) { if (this.port.source === 'fixture') return; throw new AppError('missing_metadata', 'Reviewed time-off type eligibility is unavailable.'); } let valid: unknown; try { valid = await this.options.validateTimeOff(structuredClone(p), Object.freeze(structuredClone(payload))); } catch { throw new AppError('dependency_unavailable', 'Time-off eligibility could not be verified.'); } if (valid !== true) throw new AppError('precondition_failed', 'The requested time-off type is not currently eligible.'); }
  private payload(input: Record<string, unknown>, kind: 'ticket'|'task'|'internal') {
    const start = input.start as string|undefined, end = input.end as string|undefined;
    const hours = input.minutes !== undefined ? Number(input.minutes) / 60 : (Date.parse(end!) - Date.parse(start!)) / 3_600_000;
    const body: Record<string, unknown> = { resourceID: 0, roleID: input.role_id, billingCodeID: input.billing_code_id, hoursWorked: hours, dateWorked: new Date(`${input.work_date}T00:00:00.000Z`).toISOString(), summaryNotes: input.summary, ...(input.internal_notes === undefined ? {} : { internalNotes: input.internal_notes }), ...(input.is_non_billable === undefined ? {} : { isNonBillable: input.is_non_billable }), ...(input.show_on_invoice === undefined ? {} : { showOnInvoice: input.show_on_invoice }), ...(start ? { startDateTime: start, endDateTime: end } : {}) };
    if (kind === 'ticket') body.ticketID = input.ticket_id;
    if (kind === 'task') body.taskID = input.task_id;
    if (kind === 'internal') { delete body.roleID; delete body.billingCodeID; body.internalBillingCodeID = input.internal_billing_code_id; body.isNonBillable = true; }
    return body;
  }
  async searchTime(principal: Principal, input: unknown) { assertArea(principal,'time',false);
    const a = c.timeSearchSchema.parse(input), p = await this.current(principal); if (a.resource === 'team') assertCapability(p, 'time.team');
    if (a.parent_id !== undefined) await this.parentScope(p, a.scope, { [a.scope === 'ticket' ? 'ticket_id' : 'task_id']: a.parent_id });
    const page = await this.port.searchTime(p, { scope: a.scope, parentId: a.parent_id, resourceId: a.resource === 'team' ? 0 : p.resourceId, from: a.from, to: a.to, pageSize: a.page_size, cursor: a.cursor });
    if (a.parent_id !== undefined) await this.parentScope(p, a.scope, { [a.scope === 'ticket' ? 'ticket_id' : 'task_id']: a.parent_id });
    for (const row of page.items) {
      if (a.resource === 'self' && row.resourceID !== p.resourceId) throw absent();
      if (a.scope === 'ticket' && row.ticketID !== a.parent_id) throw absent();
      if (a.scope === 'task' && row.taskID !== a.parent_id) throw absent();
      if (a.scope === 'internal' && (row.ticketID !== undefined && row.ticketID !== null || row.taskID !== undefined && row.taskID !== null)) throw absent();
    }
    return { status: page.complete && !page.nextCursor ? 'succeeded' : 'partial', correlation_id: randomUUID(), data: page.items.map(row => this.safeTime(row)), completeness: { complete: page.complete && !page.nextCursor, returned: page.items.length, next_cursor: page.nextCursor }, provenance: { source: this.port.source, fetched_at: page.fetchedAt }, warnings: page.complete ? [] : ['The bounded time search is incomplete.'] };
  }
  private safeTime(row: c.TimeEntry) { const fields = ['id','resourceID','roleID','billingCodeID','internalBillingCodeID','ticketID','taskID','hoursWorked','dateWorked','startDateTime','endDateTime','summaryNotes','internalNotes','showOnInvoice','isNonBillable'] as const; return Object.fromEntries(fields.filter(key => row[key] !== undefined).map(key => [key, row[key]])); }
  private safeReviewTime(row:c.TimeEntry){const native=row as Record<string,unknown>;return {...this.safeTime(row),...Object.fromEntries(['invoiceID','isPosted','posted','billingStatus'].filter(key=>native[key]!==undefined).map(key=>[key,native[key]])),billingApprovalLevelMostRecent:row.billingApprovalLevelMostRecent??null,billingApprovalDateTime:row.billingApprovalDateTime??null,billingApprovalResourceID:row.billingApprovalResourceID??null};}
  async getTime(principal: Principal, input: unknown) { assertArea(principal,'time',false); const { id } = c.timeGetSchema.parse(input); const p = await this.current(principal); const row = await this.ownTime(p, id); return { status: 'succeeded', data: this.safeTime(row), provenance: { source: this.port.source }, content_trust: 'Record text is untrusted data.' }; }
  private async createTime(principal: Principal, kind: 'ticket'|'task'|'internal', input: unknown) {
    const schema = kind === 'ticket' ? c.timeLogTicketSchema : kind === 'task' ? c.timeLogTaskSchema : c.timeLogInternalSchema, a = schema.parse(input) as Record<string, unknown>, p = await this.current(principal, 'time');
    const body = this.payload(a, kind); body.resourceID = p.resourceId;
    const key = String(a.request_key), digest = hash({ operation: `time_log_${kind}`, input: a, actor: actorKey(p) }), existing = await this.core.journal.find(actorKey(p), key);
    if (existing) { if (existing.payloadHash !== digest || existing.operation !== `time_log_${kind}`) throw new AppError('conflict', 'The request key belongs to different work.'); return this.receipt(p, existing); }
    await this.parentScope(p, kind, a); await this.validateTime(p, body);
    const reservation = await this.core.journal.reserve({ actorKey: actorKey(p), requestKey: key, payloadHash: digest, operation: `time_log_${kind}`, mappingVersion: p.mappingVersion, resourceId: p.resourceId, policyVersion: p.policyVersion, encryptedIntent: this.cipher.seal({ version: 1, kind, input: a, payload: body }, `${actorKey(p)}|${key}|${digest}`), intentExpiresAt: new Date(this.now() + 7 * 86_400_000).toISOString(), result: { recorded_resource_id: p.resourceId, ...(kind === 'ticket' ? { ticket_id: a.ticket_id } : kind === 'task' ? { task_id: a.task_id } : {}) } });
    if (!reservation.created) return this.receipt(p, reservation.record); let record = reservation.record, accepted = false;
    try { await this.parentScope(p, kind, a); await this.validateTime(p, body); record = await this.core.journal.transition(record.id, 'ready', 'dispatching'); const saved = await this.port.createTime(p, body, async () => { await this.parentScope(p, kind, a); await this.validateTime(p, body); }); accepted = true; record = await this.core.journal.transition(record.id, 'dispatching', 'accepted_unverified', { ...record.result, time_entry_id: saved.id }); const row = await this.ownTime(p, saved.id); const matches = this.matchesTime(row, body); if (matches) record = await this.core.journal.transition(record.id, 'accepted_unverified', 'succeeded_verified', { ...record.result, verification: { performed: true, matched_fields: Object.keys(body) } }); }
    catch (e) { const code = e instanceof AppError ? e.code : 'dependency_unavailable'; const state = accepted ? 'accepted_unverified' : definitive.has(code) ? 'failed' : 'unknown_outcome'; try { record = await this.core.journal.transition(record.id, record.state, state, { ...record.result, error_code: code }); } catch {} }
    return this.receipt(p, record);
  }
  async logTicket(p: Principal, input: unknown) { return this.createTime(p, 'ticket', input); }
  async logTask(p: Principal, input: unknown) { return this.createTime(p, 'task', input); }
  async logInternal(p: Principal, input: unknown) { return this.createTime(p, 'internal', input); }
  private matchesTime(row: c.TimeEntry, body: Record<string, unknown>) { return Object.entries(body).every(([key, value]) => { const actual = (row as Record<string, unknown>)[key]; if (key === 'hoursWorked') return typeof actual === 'number' && Math.abs(actual - Number(value)) < 1e-8; if (key === 'dateWorked' || key === 'startDateTime' || key === 'endDateTime') return value === null ? actual == null : typeof actual === 'string' && typeof value === 'string' && Date.parse(actual) === Date.parse(value); return canonical(actual ?? null) === canonical(value ?? null); }); }
  private assertTimeEditable(row: c.TimeEntry) { const value = row as Record<string, unknown>; if (row.billingApprovalDateTime || value.invoiceID !== undefined && value.invoiceID !== null || typeof value.billingApprovalLevelMostRecent === 'number' && value.billingApprovalLevelMostRecent > 0 || typeof value.billingApprovalResourceID === 'number' && value.billingApprovalResourceID > 0 || value.isPosted === true || value.posted === true || value.billingStatus === 'Posted' || value.billingStatus === 'Billed') throw new AppError('precondition_failed', 'Approved, posted, invoiced, or billed time entries cannot be corrected or deleted.'); }
  private assertTimeExpected(row: c.TimeEntry, expected: Record<string, unknown>) { for (const [k, v] of Object.entries(expected)) { const field = k === 'hoursWorked' ? row.hoursWorked : k === 'dateWorked' ? row.dateWorked : k === 'summaryNotes' ? row.summaryNotes : k === 'internalNotes' ? row.internalNotes ?? null : row[k]; if (v !== undefined && canonical(field) !== canonical(v)) throw new AppError('conflict', 'The time entry changed; refresh it before editing.'); } }
  private async mutateTime(principal: Principal, action: 'correct'|'delete', input: unknown) {
    const a = (action === 'correct' ? c.timeCorrectSchema : c.timeDeleteSchema).parse(input) as { id: number; expected: Record<string, unknown>; request_key: string; changes?: Record<string, unknown> }, p = await this.current(principal, 'time');
    const key = a.request_key, operation = `time_${action}`, digest = hash({ operation, input: a, actor: actorKey(p) }), prior = await this.core.journal.find(actorKey(p), key);
    if (prior) { if (prior.payloadHash !== digest || prior.operation !== operation) throw new AppError('conflict', 'The request key belongs to different work.'); return this.receipt(p, prior); }
    const before = await this.ownTime(p, a.id); this.assertTimeEditable(before); this.assertTimeExpected(before, a.expected as Record<string, unknown>);
    const reservation = await this.core.journal.reserve({ actorKey: actorKey(p), requestKey: key, payloadHash: digest, operation, mappingVersion: p.mappingVersion, resourceId: p.resourceId, policyVersion: p.policyVersion, encryptedIntent: this.cipher.seal({ version: 1, action, input: a }, `${actorKey(p)}|${key}|${digest}`), intentExpiresAt: new Date(this.now() + 7 * 86_400_000).toISOString(), result: { time_entry_id: a.id, recorded_resource_id: p.resourceId } }); if (!reservation.created) return this.receipt(p, reservation.record); let record = reservation.record, accepted = false;
    try { const fresh = await this.ownTime(p, a.id); this.assertTimeEditable(fresh); this.assertTimeExpected(fresh, a.expected as Record<string, unknown>); record = await this.core.journal.transition(record.id, 'ready', 'dispatching'); const beforeDispatch = async () => { const current = await this.ownTime(p, a.id); this.assertTimeEditable(current); this.assertTimeExpected(current, a.expected as Record<string, unknown>); if (action === 'correct') { const eligibility: Record<string, unknown> = { ...a.changes, resourceID: p.resourceId }; if (current.ticketID !== undefined && current.ticketID !== null) eligibility.ticketID = current.ticketID; if (current.taskID !== undefined && current.taskID !== null) eligibility.taskID = current.taskID; await this.validateTime(p, eligibility); } }; if (action === 'correct') await this.port.updateTime(p, a.id, a.changes ?? {}, beforeDispatch); else await this.port.deleteTime(p, a.id, beforeDispatch); accepted = true; const row = action === 'correct' ? await this.ownTime(p, a.id) : undefined; const verified = action === 'correct' && row !== undefined && this.matchesTime(row, a.changes ?? {}); record = await this.core.journal.transition(record.id, 'dispatching', verified ? 'succeeded_verified' : 'accepted_unverified', { ...record.result, verification: { performed: verified, note: action === 'delete' ? 'Deletion accepted; the adapter does not claim a verified absence read.' : 'Saved fields did not fully match readback.' } }); }
    catch (e) { const code = e instanceof AppError ? e.code : 'dependency_unavailable'; const state = accepted ? 'accepted_unverified' : definitive.has(code) ? 'failed' : 'unknown_outcome'; try { record = await this.core.journal.transition(record.id, record.state, state, { ...record.result, error_code: code }); } catch {} }
    return this.receipt(p, record);
  }
  async correctTime(p: Principal, input: unknown) { return this.mutateTime(p, 'correct', input); }
  async deleteTime(p: Principal, input: unknown) { return this.mutateTime(p, 'delete', input); }
  private async receipt(p: Principal, r: JournalRecord) { assertOperationArea(p,r.operation,false); await this.current(p); if (r.actorKey !== actorKey(p) || r.resourceId !== p.resourceId || r.mappingVersion !== p.mappingVersion || r.policyVersion !== p.policyVersion) throw absent(); return { status: r.state, operation_id: r.id, correlation_id: randomUUID(), data: r.result ?? {}, safe_to_redispatch: false, can_automatically_retry: false, provenance: { source: this.port.source, schema_version: 'work-management-v1' } }; }
  private async prior(p: Principal, operation: string, key: string, intent: Record<string, unknown>, hashInput: unknown = intent) { const digest = hash({ operation, input: hashInput, actor: actorKey(p) }), row = await this.core.journal.find(actorKey(p), key); if (row && (row.payloadHash !== digest || row.operation !== operation)) throw new AppError('conflict', 'The request key belongs to different work.'); return row; }

  private async expenseStatuses(p: Principal) { if (this.options.resolveExpenseStatuses) return this.options.resolveExpenseStatuses(p); if (this.port.source === 'fixture') return { inProgress: 1, rejected: 4, submitted: 2 }; throw new AppError('missing_metadata', 'Reviewed expense-report statuses are unavailable.'); }
  private async timeOffStatuses(p: Principal) { if (this.options.resolveTimeOffStatuses) return this.options.resolveTimeOffStatuses(p); if (this.port.source === 'fixture') return { submitted: 1, canceled: 3, approved: 2, rejected: 4 }; throw new AppError('missing_metadata', 'Reviewed time-off statuses are unavailable.'); }
  private async expenseParentScope(p: Principal, a: { company_id?: number; ticket_id?: number; task_id?: number }) {
    if (a.company_id !== undefined) assertCompanyScope(p, a.company_id);
    if (a.ticket_id !== undefined) { const ticket = await this.core.resolveTicket(p, { kind: 'id', id: a.ticket_id }); if (a.company_id !== undefined && ticket.companyID !== a.company_id) throw new AppError('conflict', 'The expense company does not match its ticket.'); }
    if (a.task_id !== undefined) {
      const task = await this.port.getTask(p, a.task_id);
      if (typeof task.companyID === 'number') { assertCompanyScope(p, task.companyID); if (a.company_id !== undefined && task.companyID !== a.company_id) throw new AppError('conflict', 'The expense company does not match its task.'); }
      else if (typeof task.projectID === 'number') {
        const project = await this.port.getProject(p, task.projectID);
        if (typeof project.companyID !== 'number') throw absent();
        assertCompanyScope(p, project.companyID);
        if (a.company_id !== undefined && project.companyID !== a.company_id) throw new AppError('conflict', 'The expense company does not match its task.');
      } else throw absent();
    }
  }
  private matchesExpense(row: c.ExpenseItem, body: Record<string, unknown>) { return Object.entries(body).every(([key, value]) => { const actual = (row as Record<string, unknown>)[key]; if (key === 'expenseDate') return typeof actual === 'string' && typeof value === 'string' && Date.parse(actual) === Date.parse(value); return canonical(actual ?? null) === canonical(value ?? null); }); }
  private matchesReport(row: c.ExpenseReport, body: Record<string, unknown>) { return Object.entries(body).every(([key, value]) => { const actual = (row as Record<string, unknown>)[key]; if (key === 'weekEnding') return typeof actual === 'string' && Date.parse(actual) === Date.parse(String(value)); return canonical(actual ?? null) === canonical(value ?? null); }); }
  private matchesTimeOff(row: c.TimeOffRequest, body: Record<string, unknown>) { return Object.entries(body).every(([key, value]) => { const actual = (row as Record<string, unknown>)[key]; if (['requestDate','startTime','endTime'].includes(key)) return typeof actual === 'string' && typeof value === 'string' && Date.parse(actual) === Date.parse(value); return canonical(actual ?? null) === canonical(value ?? null); }); }
  async createExpenseReport(principal: Principal, input: unknown) { assertArea(principal,'expenses',true); const a = c.expenseReportCreateSchema.parse(input), p = await this.current(principal, 'expenses'), statuses = await this.expenseStatuses(p), body = { name: a.name, weekEnding: `${a.week_ending}T00:00:00.000Z`, submitterID: p.resourceId }; if (typeof statuses.inProgress !== 'number') throw new AppError('missing_metadata', 'The reviewed In Progress expense-report status is unavailable.'); return this.mutation(p, 'expense_report_create', a.request_key, body, () => this.port.createExpenseReport(p, body, async () => { const fresh = await this.expenseStatuses(p); if (fresh.inProgress !== statuses.inProgress) throw new AppError('conflict', 'Expense-report status metadata changed before creation.'); }), async id => { const [row, fresh] = await Promise.all([this.port.getExpenseReport(p, id), this.expenseStatuses(p)]); return this.matchesReport(row, body) && fresh.inProgress === statuses.inProgress && row.status === fresh.inProgress; }); }
  async addExpenseItem(principal: Principal, input: unknown) { assertArea(principal,'expenses',true); const a = c.expenseItemAddSchema.parse(input), p = await this.current(principal, 'expenses'), body = { expenseReportID: a.report_id, expenseDate: `${a.expense_date}T00:00:00.000Z`, description: a.description, expenseCategory: a.category_id, workType: a.work_type_id, expenseCurrencyExpenseAmount: a.amount, expenseCurrencyID: a.currency_id, paymentType: a.payment_type_id, haveReceipt: a.receipt, isBillableToCompany: a.billable, ...(a.ticket_id === undefined ? {} : { ticketID: a.ticket_id }), ...(a.task_id === undefined ? {} : { taskID: a.task_id }), ...(a.company_id === undefined ? {} : { companyID: a.company_id }) }; const existing = await this.prior(p, 'expense_item_add', a.request_key, body); if (existing) return this.receipt(p, existing); await this.expenseParentScope(p, a); const report = await this.port.getExpenseReport(p, a.report_id), statuses = await this.expenseStatuses(p); if (report.submitterID !== p.resourceId || ![statuses.inProgress, statuses.rejected].includes(report.status)) throw new AppError('precondition_failed', 'Expense items can only be added to your In Progress or Rejected report.'); if (this.options.validateExpense && !(await this.options.validateExpense(p, body))) throw new AppError('precondition_failed', 'The expense item does not satisfy the reviewed expense policy.'); return this.mutation(p, 'expense_item_add', a.request_key, body, () => this.port.createExpenseItem(p, a.report_id, body, async () => { await this.expenseParentScope(p, a); const fresh = await this.port.getExpenseReport(p, a.report_id), currentStatuses = await this.expenseStatuses(p); if (fresh.submitterID !== p.resourceId || ![currentStatuses.inProgress, currentStatuses.rejected].includes(fresh.status)) throw new AppError('conflict', 'The expense report changed before adding the item.'); if (this.options.validateExpense && !(await this.options.validateExpense(p, body))) throw new AppError('precondition_failed', 'The expense item does not satisfy the reviewed expense policy.'); }), async id => this.matchesExpense(await this.port.getExpenseItem(p, id), body)); }
  async submitExpenseReport(principal: Principal, input: unknown) { assertArea(principal,'expenses',true); const a = c.expenseReportSubmitSchema.parse(input), p = await this.current(principal, 'expenses'), intent = { report_id: a.report_id, expected_status: a.expected_status, submit: true }, existing = await this.prior(p, 'expense_report_submit', a.request_key, intent); if (existing) return this.receipt(p, existing); const report = await this.port.getExpenseReport(p, a.report_id); if (report.submitterID !== p.resourceId) throw new AppError('precondition_failed', 'Only your expense report may be submitted.'); if (report.status !== a.expected_status) throw new AppError('conflict', 'The expense report changed before submission.'); const statuses = await this.expenseStatuses(p); if (typeof statuses.submitted !== 'number') throw new AppError('missing_metadata', 'The reviewed Submitted expense-report status is unavailable.'); if (![statuses.inProgress, statuses.rejected].includes(report.status)) throw new AppError('precondition_failed', 'Only an In Progress or Rejected expense report may be submitted.'); return this.mutation(p, 'expense_report_submit', a.request_key, intent, () => this.port.updateExpenseReport(p, a.report_id, { submit: true }, async () => { const fresh = await this.port.getExpenseReport(p, a.report_id), currentStatuses = await this.expenseStatuses(p); if (typeof currentStatuses.submitted !== 'number' || currentStatuses.submitted !== statuses.submitted || fresh.submitterID !== p.resourceId || fresh.status !== a.expected_status || ![currentStatuses.inProgress, currentStatuses.rejected].includes(fresh.status)) throw new AppError('conflict', 'The expense report changed before submission.'); }), async id => { const [fresh, currentStatuses] = await Promise.all([this.port.getExpenseReport(p, id), this.expenseStatuses(p)]); return typeof currentStatuses.submitted === 'number' && currentStatuses.submitted === statuses.submitted && fresh.status === currentStatuses.submitted; }); }
  async expenseReportStatus(principal: Principal, input: unknown) { assertArea(principal,'expenses',false); const a = c.expenseReportStatusSchema.parse(input), p = await this.current(principal); const report = await this.port.getExpenseReport(p, a.report_id); if (report.submitterID !== p.resourceId) throw absent(); return { status: 'succeeded', data: report, provenance: { source: this.port.source } }; }
  private async mutation(p: Principal, operation: string, key: string, intent: Record<string, unknown>, dispatch: () => Promise<{ id: number }>, verify?: (id: number) => Promise<boolean>, hashInput: unknown = intent) { const digest = hash({ operation, input: hashInput, actor: actorKey(p) }), prior = await this.core.journal.find(actorKey(p), key); if (prior) { if (prior.payloadHash !== digest || prior.operation !== operation) throw new AppError('conflict', 'The request key belongs to different work.'); return this.receipt(p, prior); } const r = await this.core.journal.reserve({ actorKey: actorKey(p), requestKey: key, payloadHash: digest, operation, mappingVersion: p.mappingVersion, resourceId: p.resourceId, policyVersion: p.policyVersion, encryptedIntent: this.cipher.seal(intent, `${actorKey(p)}|${key}|${digest}`), intentExpiresAt: new Date(this.now() + 7 * 86_400_000).toISOString(), result: { ...(Object.hasOwn(intent, 'time_entry_id') ? { time_entry_id: intent.time_entry_id } : {}), ...(Object.hasOwn(intent, 'time_off_id') ? { time_off_id: intent.time_off_id } : {}), ...(Object.hasOwn(intent, 'availability_id') ? { availability_id: intent.availability_id } : Object.hasOwn(intent, 'report_id') ? { report_id: intent.report_id } : Object.hasOwn(intent, 'expenseReportID') ? { report_id: intent.expenseReportID } : Object.hasOwn(intent, 'id') ? { id: intent.id } : { resource_id: intent.resourceID }), ...(Object.hasOwn(intent, 'expected_status') ? { expected_status: intent.expected_status } : {}) } }); if (!r.created) return this.receipt(p, r.record); let row = r.record; try { row = await this.core.journal.transition(row.id, 'ready', 'dispatching'); const saved = await dispatch(); row = await this.core.journal.transition(row.id, 'dispatching', 'accepted_unverified', { ...row.result, native_id: saved.id }); if (verify && await withReconciliation(()=>verify(saved.id))) row = await this.core.journal.transition(row.id, 'accepted_unverified', 'succeeded_verified', { ...row.result, verification: { performed: true } }); } catch (e) { const code = e instanceof AppError ? e.code : 'dependency_unavailable'; try { row = await this.core.journal.transition(row.id, row.state, definitive.has(code) ? 'failed' : row.state === 'accepted_unverified' ? 'accepted_unverified' : 'unknown_outcome', { ...row.result, error_code: code }); } catch {} } return this.receipt(p, row); }
  private matchesAvailabilityExpected(row: c.Availability, expected: Record<string, unknown>) { const fields: Record<string, keyof c.Availability> = { monday: 'mondayAvailableHours', tuesday: 'tuesdayAvailableHours', wednesday: 'wednesdayAvailableHours', thursday: 'thursdayAvailableHours', friday: 'fridayAvailableHours', saturday: 'saturdayAvailableHours', sunday: 'sundayAvailableHours', weekly_billable_goal: 'weeklyBillableHoursGoal', travel_availability: 'travelAvailability' }; return Object.entries(expected).every(([key, value]) => canonical((row[fields[key]!] ?? null)) === canonical(value ?? null)); }
  async availability(principal: Principal, input: unknown = {}) { c.availabilitySearchSchema.parse(input); const p = await this.current(principal); const row = await this.port.getAvailability(p); if (row.resourceID !== p.resourceId) throw absent(); return { status: 'succeeded', data: row, provenance: { source: this.port.source } }; }
  async updateAvailability(principal: Principal, input: unknown) { assertArea(principal,'scheduling',true); const a = c.availabilityUpdateSchema.parse(input), p = await this.current(principal, 'scheduling'), body = { mondayAvailableHours: a.monday, tuesdayAvailableHours: a.tuesday, wednesdayAvailableHours: a.wednesday, thursdayAvailableHours: a.thursday, fridayAvailableHours: a.friday, saturdayAvailableHours: a.saturday, sundayAvailableHours: a.sunday, ...(a.weekly_billable_goal === undefined ? {} : { weeklyBillableHoursGoal: a.weekly_billable_goal }), ...(a.travel_availability === undefined ? {} : { travelAvailability: a.travel_availability }) }, intent = { availability_id: a.expected_id, expected: a.expected, ...body }, existing = await this.prior(p, 'resource_availability_update', a.request_key, intent); if (existing) return this.receipt(p, existing); const current = await this.port.getAvailability(p); if (current.resourceID !== p.resourceId || current.id !== a.expected_id || !this.matchesAvailabilityExpected(current, a.expected)) throw new AppError('conflict', 'Availability changed; refresh before updating.'); return this.mutation(p, 'resource_availability_update', a.request_key, intent, () => this.port.updateAvailability(p, a.expected_id, body, async () => { const fresh = await this.port.getAvailability(p); if (fresh.resourceID !== p.resourceId || fresh.id !== a.expected_id || !this.matchesAvailabilityExpected(fresh, a.expected)) throw new AppError('conflict', 'Availability changed; refresh before updating.'); }), async id => { const row = await this.port.getAvailability(p); return row.id === id && Object.entries(body).every(([k,v]) => canonical((row as Record<string, unknown>)[k]) === canonical(v)); }); }
  async timeOffSearch(principal: Principal, input: unknown) { assertArea(principal,'scheduling',false); const a = c.timeOffSearchSchema.parse(input), p = await this.current(principal), page = await this.port.searchTimeOff(p, { resourceId: p.resourceId, from: a.from, to: a.to, pageSize: a.page_size, cursor: a.cursor }); for (const row of page.items) if (row.resourceID !== p.resourceId) throw absent(); return { status: page.complete && !page.nextCursor ? 'succeeded' : 'partial', data: page.items, completeness: { complete: page.complete && !page.nextCursor, returned: page.items.length, next_cursor: page.nextCursor }, provenance: { source: this.port.source, fetched_at: page.fetchedAt } }; }
  async timeOffRequest(principal: Principal, input: unknown) { assertArea(principal,'scheduling',true); const a = c.timeOffRequestSchema.parse(input), p = await this.current(principal, 'scheduling'), statuses = await this.timeOffStatuses(p), body = { resourceID: p.resourceId, requestDate: `${a.request_date}T00:00:00.000Z`, hours: a.hours, timeOffRequestType: a.type_id, status: statuses.submitted }; await this.validateTimeOff(p, body); return this.mutation(p, 'time_off_request', a.request_key, body, () => this.port.createTimeOff(p, body, async () => { const fresh = await this.timeOffStatuses(p); if (fresh.submitted !== statuses.submitted) throw new AppError('conflict', 'Time-off status metadata changed before creation.'); await this.validateTimeOff(p, body); }), async id => this.matchesTimeOff(await this.port.getTimeOff(p, id), body)); }
  async timeOffCancel(principal: Principal, input: unknown) { assertArea(principal,'scheduling',true); const a = c.timeOffCancelSchema.parse(input), p = await this.current(principal, 'scheduling'), statuses = await this.timeOffStatuses(p), intent = { id: a.id, expected_status: a.expected_status, status: statuses.canceled }, existing = await this.prior(p, 'time_off_cancel', a.request_key, intent, a); if (existing) return this.receipt(p, existing); const row = await this.port.getTimeOff(p, a.id); if (row.resourceID !== p.resourceId || row.status !== a.expected_status) throw new AppError('conflict', 'The time-off request changed before cancellation.'); return this.mutation(p, 'time_off_cancel', a.request_key, intent, () => this.port.updateTimeOff(p, a.id, { status: statuses.canceled }, async () => { const freshStatuses = await this.timeOffStatuses(p), fresh = await this.port.getTimeOff(p, a.id); if (freshStatuses.canceled !== statuses.canceled || fresh.resourceID !== p.resourceId || fresh.status !== a.expected_status) throw new AppError('conflict', 'The time-off request changed before cancellation.'); }), async id => (await this.port.getTimeOff(p, id)).status === statuses.canceled, a); }
  private async approverAssignments(p: Principal, resourceId: number) {
    const page = await this.port.searchTimeOffApprovers(p, {resourceId, pageSize: 100});
    if (page.nextCursor || !page.complete || page.items.some(row => row.resourceID !== resourceId || !Number.isInteger(row.approvalLevel) || row.approvalLevel < 1 || row.approvalLevel > 3)) throw new AppError('dependency_unavailable', 'The resource approver list is incomplete or invalid.');
    if (!page.items.some(row => row.approverResourceID === p.resourceId)) throw absent();
    return page.items;
  }
  private nextTimeOffLevel(row: c.TimeOffRequest, assignments: c.TimeOffApprover[]) {
    const previous = row.lastApprovedLevel ?? 0;
    if (!Number.isInteger(previous) || previous < 0 || previous > 3) throw new AppError('dependency_unavailable', 'The last approved time-off level is invalid.');
    const next = [...new Set(assignments.map(item => item.approvalLevel))].filter(level => level > previous).sort((a,b) => a-b)[0];
    return {previous, next: next ?? null};
  }
  async teamTimeReview(principal: Principal, input: unknown) {
    assertArea(principal,'time');
    const a = c.teamTimeReviewSchema.parse(input), p = await this.current(principal);
    assertCapability(p,'time.approve');
    const page = await this.port.searchTime(p,{scope:'all',resourceId:a.resource_id,from:a.from,to:a.to,pageSize:a.page_size,cursor:a.cursor});
    for(const row of page.items){if(row.resourceID!==a.resource_id)throw absent();await this.timeRowScope(p,row);}
    const entries=page.items.map(row=>this.safeReviewTime(row));
    return {status:page.complete&&!page.nextCursor?'succeeded':'partial',data:{resource_id:a.resource_id,from:a.from,to:a.to,entries,returned_page_hours:page.items.reduce((sum,row)=>sum+row.hoursWorked,0),native_timesheet_status:'unavailable_via_rest'},completeness:{complete:page.complete&&!page.nextCursor,returned:entries.length,next_cursor:page.nextCursor},provenance:{source:this.port.source,fetched_at:page.fetchedAt},limitations:['The REST API exposes time entries but does not expose timesheet approval or posting. Hours cover only this returned page.']};
  }
  async billingApprovalReview(principal: Principal, input: unknown) {
    assertArea(principal,'time');assertArea(principal,'finance');
    const a=c.billingApprovalReviewSchema.parse(input),p=await this.current(principal);
    assertCapability(p,'time.approve');
    const row=await this.port.getTime(p,a.time_entry_id);await this.timeRowScope(p,row);
    const levels=await this.port.searchBillingApprovals(p,a.time_entry_id);
    if(levels.some(level=>level.timeEntryID!==a.time_entry_id))throw absent();
    return {status:'succeeded',data:{time_entry:this.safeReviewTime(row),approval_levels:levels,latest_level:Math.max(0,...levels.map(level=>level.approvalLevel)),native_timesheet_status:'unavailable_via_rest'},provenance:{source:this.port.source},limitations:['A billing approval level is not a timesheet approval or posting action. The parent time entry approval date and resource can lag the level record.']};
  }
  async billingApprovalRecord(principal: Principal, input: unknown) {
    assertArea(principal,'time',true);assertArea(principal,'finance',true);
    const a=c.billingApprovalRecordSchema.parse(input),p=await this.current(principal);
    assertCapability(p,'time.approve');assertCapability(p,'finance.read');assertCapability(p,'finance.write');
    const operation='time_billing_approval_record',intent={id:a.time_entry_id,time_entry_id:a.time_entry_id,expected_previous_level:a.expected_previous_level,approval_level:a.approval_level,approval_resource_id:p.resourceId};
    const prior=await this.prior(p,operation,a.request_key,intent,a);if(prior)return this.receipt(p,prior);
    const preflight=async()=>{
      const row=await this.port.getTime(p,a.time_entry_id);await this.timeRowScope(p,row);
      if((row as Record<string,unknown>).invoiceID!=null||(row as Record<string,unknown>).isPosted===true||(row as Record<string,unknown>).posted===true||['Posted','Billed'].includes(String((row as Record<string,unknown>).billingStatus)))throw new AppError('precondition_failed','Posted or invoiced time cannot receive an approval level through this workflow.');
      const levels=await this.port.searchBillingApprovals(p,a.time_entry_id);
      if(levels.some(level=>level.timeEntryID!==a.time_entry_id))throw absent();
      const latest=Math.max(0,...levels.map(level=>level.approvalLevel));
      if(latest!==a.expected_previous_level||(row.billingApprovalLevelMostRecent??0)!==a.expected_previous_level||levels.some(level=>level.approvalLevel===a.approval_level))throw new AppError('conflict','Billing approval state changed; review the time entry again.');
    };
    await preflight();
    const approvalDateTime=new Date(this.now()).toISOString();
    return this.mutation(p,operation,a.request_key,intent,()=>this.port.createBillingApproval(p,{timeEntryID:a.time_entry_id,approvalLevel:a.approval_level,approvalResourceID:p.resourceId,approvalDateTime},preflight),async id=>{
      const level=await this.port.getBillingApproval(p,id),row=await this.port.getTime(p,a.time_entry_id);
      return level.timeEntryID===a.time_entry_id&&level.approvalLevel===a.approval_level&&level.approvalResourceID===p.resourceId&&row.billingApprovalLevelMostRecent===a.approval_level;
    },a);
  }
  async timeOffApproverResources(principal: Principal, input: unknown) {
    assertArea(principal,'scheduling');const a=c.timeOffApproverResourcesSchema.parse(input),p=await this.current(principal);assertCapability(p,'time.approve');
    const page=await this.port.searchTimeOffApprovers(p,{approverId:p.resourceId,pageSize:a.page_size,cursor:a.cursor});
    if(page.items.some(row=>row.approverResourceID!==p.resourceId))throw absent();
    return {status:page.complete&&!page.nextCursor?'succeeded':'partial',data:page.items,completeness:{complete:page.complete&&!page.nextCursor,returned:page.items.length,next_cursor:page.nextCursor},provenance:{source:this.port.source,fetched_at:page.fetchedAt}};
  }
  async timeOffReview(principal: Principal, input: unknown) {
    assertArea(principal,'scheduling');const a=c.timeOffReviewSchema.parse(input),p=await this.current(principal);assertCapability(p,'time.approve');
    const assignments=await this.approverAssignments(p,a.resource_id),statuses=await this.timeOffStatuses(p);
    const page=await this.port.searchTimeOff(p,{resourceId:a.resource_id,from:a.from,to:a.to,pageSize:a.page_size,cursor:a.cursor});
    await this.approverAssignments(p,a.resource_id);
    const items=page.items.map(row=>{if(row.resourceID!==a.resource_id)throw absent();const {previous,next}=this.nextTimeOffLevel(row,assignments);return{...row,next_approval_level:next,can_act:row.status===statuses.submitted&&next!==null&&assignments.some(item=>item.approvalLevel===next&&item.approverResourceID===p.resourceId),reviewed_last_level:previous};});
    return {status:page.complete&&!page.nextCursor?'succeeded':'partial',data:items,completeness:{complete:page.complete&&!page.nextCursor,returned:items.length,next_cursor:page.nextCursor},provenance:{source:this.port.source,fetched_at:page.fetchedAt}};
  }
  private async timeOffDecision(principal: Principal, action:'approve'|'reject', input: unknown) {
    assertArea(principal,'scheduling',true);
    const a=(action==='approve'?c.timeOffApproveSchema:c.timeOffRejectSchema).parse(input) as {request_id:number;expected_status:number;expected_last_approved_level:number;reason?:string;request_key:string};
    const p=await this.current(principal,'scheduling');assertCapability(p,'time.approve');
    const operation=`time_off_${action}`,intent={id:a.request_id,time_off_id:a.request_id,expected_status:a.expected_status,expected_last_approved_level:a.expected_last_approved_level,...(a.reason?{reason:a.reason}:{})};
    const prior=await this.prior(p,operation,a.request_key,intent,a);if(prior)return this.receipt(p,prior);
    const preflight=async()=>{
      const row=await this.port.getTimeOff(p,a.request_id),statuses=await this.timeOffStatuses(p),assignments=await this.approverAssignments(p,row.resourceID);
      const {previous,next}=this.nextTimeOffLevel(row,assignments);
      if(row.status!==a.expected_status||row.status!==statuses.submitted||previous!==a.expected_last_approved_level||next===null||!assignments.some(item=>item.approvalLevel===next&&item.approverResourceID===p.resourceId))throw new AppError('conflict','The time-off request or its next approver changed; review it again.');
      if(action==='reject'&&typeof statuses.rejected!=='number')throw new AppError('missing_metadata','The native Rejected time-off status is unavailable.');
      return {next,rejected:statuses.rejected,resourceId:row.resourceID};
    };
    const reviewed=await preflight();
    return this.mutation(p,operation,a.request_key,intent,()=>action==='approve'?this.port.approveTimeOff(p,a.request_id,async()=>{await preflight();}):this.port.rejectTimeOff(p,a.request_id,a.reason!,async()=>{await preflight();}),async id=>{
      const row=await this.port.getTimeOff(p,id);
      return row.resourceID===reviewed.resourceId&&(action==='approve'?row.lastApprovedLevel===reviewed.next:row.status===reviewed.rejected&&(row.rejectReason===a.reason||row.reason===a.reason));
    },a);
  }
  async timeOffApprove(p:Principal,input:unknown){return this.timeOffDecision(p,'approve',input);}
  async timeOffReject(p:Principal,input:unknown){return this.timeOffDecision(p,'reject',input);}
  async operationStatus(principal: Principal, input: unknown) { const { operation_id } = c.operationStatusSchema.parse(input), p = await this.current(principal), record = await this.core.journal.get(operation_id, actorKey(p)); if (!record || !['time_','expense_','resource_','time_off_'].some(prefix => record.operation.startsWith(prefix))) throw absent(); return this.receipt(p, record); }
}
