import { z } from 'zod';
import type { Principal } from '../../contracts/src/index.js';
import type { WorkManagementService } from './index.js';
import * as c from './contracts.js';

/** MCP-facing fixed tool definitions. Runtime capability filtering remains the
 * caller's responsibility; each service method repeats authorization. */
export interface WorkManagementTool { name: string; schema: z.ZodObject<any>; description: string; write: boolean; destructive?: boolean; capabilities: readonly string[]; run: (principal: Principal, input: unknown) => Promise<unknown> }
export function workManagementTools(service: WorkManagementService): WorkManagementTool[] {
  return [
    { name: 'time_search', schema: c.timeSearchSchema, description: 'Read actual ticket, project-task, or internal time. Team scope requires time.team; no duration is inferred.', write: false, capabilities: ['operational.read'], run: (p: Principal, a: unknown) => service.searchTime(p, a) },
    { name: 'time_get', schema: c.timeGetSchema, description: 'Read one time entry owned by the signed-in employee after parent and resource scope checks.', write: false, capabilities: ['operational.read', 'time.self'], run: (p: Principal, a: unknown) => service.getTime(p, a) },
    { name: 'time_log_ticket', schema: c.timeLogTicketSchema, description: 'Record explicitly supplied time on a ticket for the signed-in employee using the root TimeEntries endpoint.', write: true, capabilities: ['operational.read', 'time.self'], run: (p: Principal, a: unknown) => service.logTicket(p, a) },
    { name: 'time_log_task', schema: c.timeLogTaskSchema, description: 'Record explicitly supplied time on a project task. Start and stop times are preserved when supplied.', write: true, capabilities: ['operational.read', 'time.self'], run: (p: Principal, a: unknown) => service.logTask(p, a) },
    { name: 'time_log_internal', schema: c.timeLogInternalSchema, description: 'Record explicitly supplied general or internal time with an internal allocation code. No ticket or task is implied.', write: true, capabilities: ['operational.read', 'time.self'], run: (p: Principal, a: unknown) => service.logInternal(p, a) },
    { name: 'time_correct', schema: c.timeCorrectSchema, description: 'Correct mutable, unposted, unbilled time only when expected fields still match.', write: true, destructive: true, capabilities: ['operational.read', 'time.self'], run: (p: Principal, a: unknown) => service.correctTime(p, a) },
    { name: 'time_delete', schema: c.timeDeleteSchema, description: 'Delete mutable, unposted, unbilled time after an explicit expected-value check; deletion remains unverified until independently reconciled.', write: true, destructive: true, capabilities: ['operational.read', 'time.self'], run: (p: Principal, a: unknown) => service.deleteTime(p, a) },
    { name: 'time_timesheet_review', schema: c.teamTimeReviewSchema, description: 'Review one employee\'s native time entries and billing approval fields over a date range. Returns page-scoped hours; native timesheet submission and posting state are not exposed by REST.', write: false, capabilities: ['operational.read', 'time.approve'], run: (p: Principal, a: unknown) => service.teamTimeReview(p, a) },
    { name: 'time_billing_approval_review', schema: c.billingApprovalReviewSchema, description: 'Inspect one scoped time entry and its complete billing approval-level history; this is not timesheet approval or posting.', write: false, capabilities: ['operational.read', 'time.approve', 'finance.read'], run: (p: Principal, a: unknown) => service.billingApprovalReview(p, a) },
    { name: 'time_billing_approval_record', schema: c.billingApprovalRecordSchema, description: 'Create exactly one next billing approval-level row for a reviewed time entry. Does not approve or post a timesheet; use the request key for recovery.', write: true, capabilities: ['operational.read', 'time.approve', 'finance.read', 'finance.write'], run: (p: Principal, a: unknown) => service.billingApprovalRecord(p, a) },
    { name: 'expense_report_create', schema: c.expenseReportCreateSchema, description: 'Create an In Progress expense report for the signed-in employee using reviewed tenant status metadata.', write: true, capabilities: ['operational.read', 'expenses.write'], run: (p: Principal, a: unknown) => service.createExpenseReport(p, a) },
    { name: 'expense_item_add', schema: c.expenseItemAddSchema, description: 'Add a receipt-backed expense item to the employee\'s In Progress or Rejected report with parent company scope checks.', write: true, capabilities: ['operational.read', 'expenses.write'], run: (p: Principal, a: unknown) => service.addExpenseItem(p, a) },
    { name: 'expense_report_submit', schema: c.expenseReportSubmitSchema, description: 'Submit the employee\'s In Progress or Rejected expense report after an expected-status check.', write: true, destructive: true, capabilities: ['operational.read', 'expenses.write'], run: (p: Principal, a: unknown) => service.submitExpenseReport(p, a) },
    { name: 'expense_report_status', schema: c.expenseReportStatusSchema, description: 'Read one expense report only when it belongs to the signed-in employee.', write: false, capabilities: ['operational.read', 'expenses.write'], run: (p: Principal, a: unknown) => service.expenseReportStatus(p, a) },
    { name: 'resource_availability', schema: c.availabilitySearchSchema, description: 'Read the signed-in employee\'s daily availability record.', write: false, capabilities: ['operational.read', 'time.self'], run: (p: Principal, a: unknown) => service.availability(p, a) },
    { name: 'resource_availability_update', schema: c.availabilityUpdateSchema, description: 'Update the signed-in employee\'s daily availability after an expected-record check.', write: true, destructive: true, capabilities: ['operational.read', 'scheduling.write'], run: (p: Principal, a: unknown) => service.updateAvailability(p, a) },
    { name: 'time_off_search', schema: c.timeOffSearchSchema, description: 'Read the signed-in employee\'s time-off requests with bounded filters and pagination.', write: false, capabilities: ['operational.read', 'time.self'], run: (p: Principal, a: unknown) => service.timeOffSearch(p, a) },
    { name: 'time_off_request', schema: c.timeOffRequestSchema, description: 'Request time off for the signed-in employee using reviewed tenant status metadata.', write: true, capabilities: ['operational.read', 'scheduling.write'], run: (p: Principal, a: unknown) => service.timeOffRequest(p, a) },
    { name: 'time_off_cancel', schema: c.timeOffCancelSchema, description: 'Cancel the signed-in employee\'s time-off request after an expected-status check.', write: true, destructive: true, capabilities: ['operational.read', 'scheduling.write'], run: (p: Principal, a: unknown) => service.timeOffCancel(p, a) },
    { name: 'time_off_approver_resources', schema: c.timeOffApproverResourcesSchema, description: 'List resources whose time-off requests the signed-in leadership user is configured to approve, with native approval levels.', write: false, capabilities: ['operational.read', 'time.approve'], run: (p: Principal, a: unknown) => service.timeOffApproverResources(p, a) },
    { name: 'time_off_review', schema: c.timeOffReviewSchema, description: 'Review one assigned employee\'s time-off requests and identify the next approval level and actionable requests.', write: false, capabilities: ['operational.read', 'time.approve'], run: (p: Principal, a: unknown) => service.timeOffReview(p, a) },
    { name: 'time_off_approve', schema: c.timeOffApproveSchema, description: 'Approve one time-off request as the signed-in configured approver at the expected next level; one-shot native action with readback.', write: true, capabilities: ['operational.read', 'time.approve', 'scheduling.write'], run: (p: Principal, a: unknown) => service.timeOffApprove(p, a) },
    { name: 'time_off_reject', schema: c.timeOffRejectSchema, description: 'Reject one time-off request as the signed-in configured approver with an explicit reason and expected state; one-shot native action.', write: true, destructive: true, capabilities: ['operational.read', 'time.approve', 'scheduling.write'], run: (p: Principal, a: unknown) => service.timeOffReject(p, a) },
    { name: 'work_operation_status', schema: c.operationStatusSchema, description: 'Read an unverified or completed work-management mutation receipt. Never repeats a write.', write: false, capabilities: ['operational.read'], run: (p: Principal, a: unknown) => service.operationStatus(p, a) },
  ];
}

export const workManagementOperations: Record<string, { write: boolean; capabilities: string[] }> = {
  time_search: { write: false, capabilities: ['operational.read'] }, time_get: { write: false, capabilities: ['operational.read', 'time.self'] },
  time_log_ticket: { write: true, capabilities: ['operational.read', 'time.self'] }, time_log_task: { write: true, capabilities: ['operational.read', 'time.self'] }, time_log_internal: { write: true, capabilities: ['operational.read', 'time.self'] }, time_correct: { write: true, capabilities: ['operational.read', 'time.self'] }, time_delete: { write: true, capabilities: ['operational.read', 'time.self'] },
  time_timesheet_review: { write: false, capabilities: ['operational.read', 'time.approve'] }, time_billing_approval_review: { write: false, capabilities: ['operational.read', 'time.approve', 'finance.read'] }, time_billing_approval_record: { write: true, capabilities: ['operational.read', 'time.approve', 'finance.read', 'finance.write'] },
  expense_report_create: { write: true, capabilities: ['operational.read', 'expenses.write'] }, expense_item_add: { write: true, capabilities: ['operational.read', 'expenses.write'] }, expense_report_submit: { write: true, capabilities: ['operational.read', 'expenses.write'] }, expense_report_status: { write: false, capabilities: ['operational.read', 'expenses.write'] },
  resource_availability: { write: false, capabilities: ['operational.read', 'time.self'] }, resource_availability_update: { write: true, capabilities: ['operational.read', 'scheduling.write'] }, time_off_search: { write: false, capabilities: ['operational.read', 'time.self'] }, time_off_request: { write: true, capabilities: ['operational.read', 'scheduling.write'] }, time_off_cancel: { write: true, capabilities: ['operational.read', 'scheduling.write'] }, work_operation_status: { write: false, capabilities: ['operational.read'] },
  time_off_approver_resources: { write: false, capabilities: ['operational.read', 'time.approve'] }, time_off_review: { write: false, capabilities: ['operational.read', 'time.approve'] }, time_off_approve: { write: true, capabilities: ['operational.read', 'time.approve', 'scheduling.write'] }, time_off_reject: { write: true, capabilities: ['operational.read', 'time.approve', 'scheduling.write'] },
};
export const WORK_MANAGEMENT_OPERATIONS = Object.freeze(Object.keys(workManagementOperations));
